import type { Metadata } from 'next';
import { Database, GitBranch, KeyRound, Server, Settings2, ShieldCheck, Terminal } from 'lucide-react';
import { PreviewNav } from '../_components/PreviewNav';
import { PreviewFooter } from '../_components/PreviewFooter';
import { GITHUB_URL, GithubIcon } from '../_components/ui';
import { SectionHead } from '../_components/ui';
import { DeploymentExplorer, InfrastructureScene } from '../_components/platform/PlatformScenes';
import { DocLink, PlatformBreadcrumb, PlatformClosing, PlatformFAQ, REPO } from '../_components/platform/PlatformParts';
import { CommunityShowcase } from '../_components/platform/PlatformProof';
import '../_components/platform/platform.css';
import '../_components/platform/platform-polish.css';

export const metadata:Metadata={title:'Self-hosting — Helpin',description:'Run Helpin Community on your infrastructure with Docker Compose. Keep support, docs, and agents together, configure your connections, and manage the installation with the Helpin CLI.',alternates:{canonical:'/new/self-hosting'},robots:{index:false,follow:false}};
const FAQS=[
 ['What is included in Helpin Community?', 'Community 0.1 beta includes support, docs, and agents. Shared customer records support those workflows. Full Projects, CRM, Meetings, and Automation surfaces are not part of the default Community scope; availability depends on the edition and enabled modules.'],
 ['What do I need to run it?', 'The documented bundle uses Docker Engine and Docker Compose v2, Bash, and OpenSSL. Start with at least 8 GiB RAM available to Docker and 20 GiB free disk for evaluation; production requirements depend on your workload. The CLI supports Linux and macOS on amd64 and arm64.'],
 ['How do I get the installer?', 'Follow the installation guide for the current distribution options. The CLI download flow requires a published Community release with matching CLI and bundle assets, plus a published website installer. Manual bundle installation is also supported. If a release bundle is not yet available, use the source development guide.'],
 ['Can we use our own models?', 'Configure supported API-key connections and agent profiles in AI settings. Self-hosting the application does not automatically make model inference local: requests follow the providers you configure. Knowledge embeddings and some non-agent AI features have separate server settings.'],
 ['Does Helpin manage our backups or upgrades?', 'Your team operates the installation. The backup guide covers databases, files, configuration, and encryption keys. Community 0.1 validates clean installs and same-release restore; tested cross-version upgrades are a later release requirement. The CLI does not currently provide an upgrade command.'],
 ['Can we use Kubernetes or run fully air-gapped?', 'The documented Community installation uses Docker Compose. Kubernetes manifests in the repository are not a supported Community Helm installation. A fully air-gapped deployment is not a validated Community promise; container images, model providers, and external integrations each have their own connectivity requirements.'],
 ['Does the CLI configure public HTTPS for us?', 'Server mode prepares public URL settings and a Caddy configuration. You manage DNS, the host proxy, certificates, and network access. The doctor command checks readiness, but your team should also verify the widget and attachment journey from the public website.'],
 ['What is the open-source license?', 'Helpin is licensed under AGPL-3.0. You can inspect and modify the source under its terms. The repository includes the license, contribution guidance, release information, and the current Community roadmap.'],
] as const;
export default function SelfHostingPage(){return <><PreviewNav/><div className="platform-page self-hosting-page">
 <section className="platform-hero"><div className="wrap"><PlatformBreadcrumb label="Open source & self-hosting"/><div className="platform-hero-grid"><div className="platform-hero-copy"><span className="eyebrow">Open source, on your infrastructure</span><h1>Run your customer workspace <span>on your infrastructure.</span></h1><p className="lede">Bring support, docs, and agents to the servers you control. Own the customer history, choose your model connections, and manage the installation with the Helpin CLI.</p><div className="cta-row"><a className="btn btn-primary" href={`${REPO}/community/README.md`} target="_blank" rel="noopener noreferrer">Self-host Helpin →</a><a className="btn btn-secondary" href={GITHUB_URL} target="_blank" rel="noopener noreferrer"><GithubIcon/>View the code →</a></div><div className="platform-hero-points"><span><GitBranch size={14}/>AGPL-3.0</span><span><Server size={14}/>Docker Compose</span><span><Terminal size={14}/>Community beta</span></div></div><InfrastructureScene/></div></div></section>
 <nav className="platform-page-nav" aria-label="On this page"><div className="wrap"><strong>Self-hosting</strong><a href="#community">What’s included</a><a href="#cli">Helpin CLI</a><a href="#deployment">Deployment</a><a href="#ownership">Data & connections</a><a href="#self-hosting-faq">Questions</a></div></nav>
 <section id="community"><div className="wrap"><div className="platform-centered"><SectionHead eyebrow="Start with the customer" title="Keep the customer workflow together." lede="Answer customers, publish the knowledge behind each reply, and put agents to work—all in the installation your team runs."/></div><CommunityShowcase/><p className="platform-scope-note">Community 0.1 beta focuses on support, docs, and agents. <a href={`${REPO}/ROADMAP.md`} target="_blank" rel="noopener noreferrer">See the current scope and roadmap →</a></p></div></section>
 <section id="cli" className="platform-soft"><div className="wrap"><div className="platform-split platform-cli-layout"><figure className="platform-cli-art"><img src="/new/product/helpin-cli-tilted-1920-v1.webp" srcSet="/new/product/helpin-cli-tilted-1920-v1.webp 1920w, /new/product/helpin-cli-tilted-4k-v1.webp 3840w" sizes="(max-width: 960px) calc(100vw - 48px), 680px" width={3840} height={2160} loading="lazy" alt="Tilted Helpin CLI terminal showing installation checks, diagnostics, status, and logs."/></figure><div><SectionHead eyebrow="Helpin CLI" title="Run your instance from one terminal." lede="Install the bundle, check the services, and follow the logs. Use the CLI to handle the routine work of running Helpin."/><DocLink href={`${REPO}/docs/community/cli.md`}>Read the CLI guide</DocLink></div></div><div className="platform-command-grid">{[
  ['helpin install','Get the installation ready.','Choose local or server mode. Verify the bundle, generate secrets, and check application readiness.'],
  ['helpin doctor','See what needs attention.','Check Docker, configuration, services, API readiness, HTTPS, and secret-file permissions.'],
  ['helpin logs','Look into the services.','Follow logs for the installation or selected services. Use status to inspect containers and image identities.'],
 ].map(([command,title,body])=><article key={command}><code><span>$</span> {command}</code><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
 <section id="deployment" className="platform-dark"><div className="wrap"><div className="platform-centered"><SectionHead eyebrow="From your machine to your server" title="Start locally. Put it on your domains when you’re ready." lede="Use local defaults to explore Helpin, or configure a public server with your own dashboard, help-center, and attachment URLs."/></div><DeploymentExplorer/><DocLink href={`${REPO}/docs/community/deployment.md`}>Read the public deployment guide</DocLink></div></section>
 <section id="ownership"><div className="wrap"><div className="platform-section-intro"><SectionHead eyebrow="You operate the workspace" title="Keep control after the install." lede="Choose how the installation connects, protect the customer history, and keep the operating details in reach."/><span className="platform-side-note"><ShieldCheck size={23}/>Your infrastructure.<br/>Your operating choices.</span></div><div className="platform-feature-grid">{[
  {Icon:Database,title:'Keep the history and files together.',body:'Operate the application databases and S3-compatible file storage. Back up the data, configuration, and encryption keys as one installation.',href:`${REPO}/docs/community/backups.md`,label:'Backup & restore guide'},
  {Icon:KeyRound,title:'Choose how AI connects.',body:'Set up supported provider connections and agent profiles. Configure embeddings and other server AI features separately for the capabilities you use.',href:`${REPO}/docs/community/configuration.md`,label:'Configuration reference'},
  {Icon:Settings2,title:'Configure the customer-facing services.',body:'Set public URLs, widget origins, and application mail. Enable optional integrations when your team needs them.',href:`${REPO}/docs/community/deployment.md`,label:'Deployment reference'},
 ].map(({Icon,title,body,href,label})=><article key={title}><Icon size={24}/><h3>{title}</h3><p>{body}</p><DocLink href={href}>{label}</DocLink></article>)}</div></div></section>
 <section id="self-hosting-faq"><div className="wrap platform-faq-grid"><SectionHead eyebrow="Before you install" title="Know what you’re running."/><PlatformFAQ items={FAQS}/></div></section>
 <PlatformClosing id="self-hosting-final-title" title="Make the workspace yours." description="Start with the Community installation guide. Keep the customer workflow close to your team and your infrastructure." hosting/>
 </div><PreviewFooter/></>;}
