apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: teampulse-prod-doppler
  namespace: teampulse
spec:
  tokenSecret:
    name: doppler-token-teampulse
  managedSecret:
    name: teampulse-secrets
    namespace: teampulse
