import { useState } from 'react';
import { QuietPageHeader, QuietSection, QuietTextAction } from '@/components/design-system/quiet';
import { ArrowRight01Icon } from '@/lib/icons';
import { type Playbook, type Situation, type View } from './workspace-data';
import { Field, LineTabs, Person, Progress, ResourceLink, StateText } from './workspace-ui';

export function AutomationWorkspace({ view, book, books, situations, onNavigate, onOpen }: { view:View; book?:Playbook; books:Playbook[]; situations:Situation[]; onNavigate:(view:View,id?:string,tab?:string)=>void; onOpen:(id:string)=>void }) {
  const [tab,setTab]=useState('Configuration');
  if(view==='agents') return <><QuietPageHeader title="CRM Assistant" description="A shared executor for sales and customer-success work."/><div className="book-metadata"><StateText value="Enabled"/><span>Workspace agent</span><span>Used by {books.length} playbooks</span></div><div className="work-detail-layout"><div className="work-detail-main"><QuietSection title="Responsibilities" className="flush-section"><p className="work-prose">Understand customer context, prepare grounded next steps, and carry out approved actions. Preserve human decisions and existing commitments.</p></QuietSection><QuietSection title="Tool permissions" className="flush-section"><table className="work-table" aria-label="Agent tool permissions"><thead><tr><th>Capability</th><th>Access</th></tr></thead><tbody>{[['Read permitted customer context','Allowed'],['Read relevant signals and linked work','Allowed'],['Prepare responses and handoffs','Allowed'],['Send customer messages','Approval required'],['Create or update a CRM deal','Approval required'],['Create a follow-up task','Approval required'],['Change pricing or contract terms','Not permitted']].map(([a,b])=><tr key={a}><td>{a}</td><td><span className={b==='Allowed'?'text-quiet-positive':b==='Not permitted'?'muted':'text-quiet-accent'}>{b}</span></td></tr>)}</tbody></table></QuietSection><QuietSection title="Used in these playbooks" className="flush-section">{books.map(b=><ResourceLink key={b.id} title={b.name} meta={b.goal} onClick={()=>onNavigate('playbook',b.id)}/>)}</QuietSection></div><aside className="work-detail-rail"><QuietSection title="Execution boundaries" className="rail-section"><Field label="Context"><span>Workspace and record permissions</span></Field><Field label="Approval"><span>Exact action and payload</span></Field><Field label="Customer contact"><span>Shared contact policy</span></Field><Field label="Failed actions"><span>Return to the responsible person</span></Field><p className="work-small">The same agent is reused across playbooks. A new category does not require a new agent.</p></QuietSection></aside></div></>;
  if(view==='activity') return <><QuietPageHeader title="Activity" description="What ran, what needs approval, and what needs recovery."/><div className="work-top-gap"><ActivityTable situations={situations} onOpen={onOpen}/></div></>;
  if(!book) return <><QuietPageHeader title="Flows" description="Shared execution behind your customer processes."/><div className="work-top-gap"><table className="work-table" aria-label="CRM flows"><thead><tr><th>Flow</th><th>When</th><th>Using</th><th>Status</th></tr></thead><tbody>{books.map(b=><tr key={b.id} onClick={()=>onNavigate('flows',b.id)}><td><button><strong>{b.name}</strong></button><small>Connected CRM playbook</small></td><td>{b.trigger}</td><td>CRM Assistant</td><td><StateText value={b.enabled?'Enabled':'Disabled'}/></td></tr>)}</tbody></table></div></>;
  return <><QuietPageHeader title={book.name} description="The execution configuration behind this CRM playbook." actions={<QuietTextAction onClick={()=>onNavigate('edit',book.id)}>Edit connected configuration <ArrowRight01Icon className="size-3.5"/></QuietTextAction>}/><div className="book-metadata"><StateText value={book.enabled?'Enabled':'Disabled'}/><span>Published version {book.version}</span><span>CRM → Shared Automation</span></div><LineTabs label="Flow detail views" value={tab} onChange={setTab} items={[{value:'Configuration',label:'Configuration'},{value:'Activity',label:'Activity'}]}/>{tab==='Activity'?<div className="work-top-gap"><ActivityTable situations={situations.filter(s=>s.playbook===book.id)} onOpen={onOpen}/></div>:<div className="work-detail-layout"><div className="work-detail-main"><QuietSection title="When and where" className="flush-section"><Field label="When"><span>{book.trigger}</span></Field><Field label="Only if"><span>{book.audience}; no matching active process</span></Field><Field label="Using"><QuietTextAction onClick={()=>onNavigate('agents')}>CRM Assistant <ArrowRight01Icon className="size-3.5"/></QuietTextAction></Field><Field label="On"><span>The linked customer situation and permitted CRM records</span></Field></QuietSection><QuietSection title="Execution and checkpoints" className="flush-section"><Progress steps={book.steps} progress={-1}/></QuietSection></div><aside className="work-detail-rail"><QuietSection title="Connected process" className="rail-section"><ResourceLink title={book.name} meta="Open the business-facing playbook" onClick={()=>onNavigate('playbook',book.id)}/><Field label="Owner"><Person name={book.owner}/></Field><Field label="Approval"><span>{book.approval}</span></Field><Field label="Checkpoint"><span>{book.delay}</span></Field></QuietSection><QuietSection title="Control" className="rail-section"><p className="work-small">Customer policy is configured once, in the connected playbook. Changes are reviewed and published together.</p><ResourceLink title="View CRM Assistant" meta="Tools, permissions, and shared responsibilities" onClick={()=>onNavigate('agents')}/></QuietSection></aside></div>}</>;
}
function ActivityTable({situations,onOpen}:{situations:Situation[];onOpen:(id:string)=>void}) {
  return <table className="work-table" aria-label="Automation activity"><thead><tr><th>Customer</th><th>Latest result</th><th>Execution state</th><th>Customer work</th></tr></thead><tbody>{situations.filter(s=>s.playbook).map(s=><tr key={s.id} onClick={()=>onOpen(s.id)}><td><strong>{s.company}</strong></td><td>{s.history[0]}</td><td><StateText value={s.status==='Needs approval'?'Awaiting approval':s.status==='Delivery failed'?'Delivery failed':s.status==='Paused'?'Paused':'Succeeded'}/></td><td><StateText value={s.status}/></td></tr>)}</tbody></table>;
}
