import { useState } from 'react';
import { QuietIdentityHeader, QuietSection, QuietTextAction } from '@/components/design-system/quiet';
import { ArrowRight01Icon } from '@/lib/icons';
import { ME, ownerName, type Playbook, type Situation } from './workspace-data';
import { Field, LineTabs, Person, Progress, ResourceLink, StateText } from './workspace-ui';

export function CustomerWorkspace({ company, situations, books, focus, onOpen, onBook, onResource }: { company:string; situations:Situation[]; books:Playbook[]; focus?:string; onOpen:(id:string)=>void; onBook:(id:string)=>void; onResource:(title:string,body:string)=>void }) {
  const [tab,setTab]=useState('Customer work');
  const members=situations.filter(s=>s.company===company);
  const [selected,setSelected]=useState(focus||members[0]?.id);
  const current=members.find(s=>s.id===selected)||members[0];
  const book=current?.configuration||books.find(b=>b.id===current?.playbook);
  const accountOwner=company==='Northstar'?'Sara Ahmed':ME;
  return <><QuietIdentityHeader className="work-identity" avatar={<span className="work-company-mark">{company.slice(0,2)}</span>} title={company} meta={<>{company.toLowerCase()}.example <span className="meta-divider"/> {company==='Harbor'||company==='Orbit'?'Prospect':'Customer'}</>} actions={current&&<QuietTextAction onClick={()=>onOpen(current.id)}>Open next action <ArrowRight01Icon className="size-3.5"/></QuietTextAction>}/>
    <LineTabs label="Customer record views" value={tab} onChange={setTab} items={[{value:'Customer work',label:'Customer work',count:members.length},{value:'Activity',label:'Activity'},{value:'Linked work',label:'Linked work',count:members.filter(s=>s.task).length}]}/>
    <div className="work-detail-layout"><div className="work-detail-main">
      {tab==='Customer work'&&<><QuietSection title="Active situations and outcomes" className="flush-section"><div className="customer-situations">{members.map(s=><button key={s.id} className={current?.id===s.id?'customer-situation current':'customer-situation'} onClick={()=>setSelected(s.id)}><span><strong>{s.title}</strong><small>{s.next}</small></span><StateText value={s.status}/></button>)}</div></QuietSection>{current&&<><QuietSection title="Customer objective" className="flush-section" action={<QuietTextAction onClick={()=>onOpen(current.id)}>Open situation <ArrowRight01Icon className="size-3.5"/></QuietTextAction>}><p className="work-prose">{current.goal}</p><div className="goal-owner"><span className="work-small">Responsible</span><Person name={current.owner}/></div>{current.outcome&&<p className="work-prose text-quiet-positive">{current.outcome}</p>}</QuietSection>{book&&<QuietSection title="Process progress" className="flush-section" action={<QuietTextAction onClick={()=>onBook(book.id)}>{book.name}<ArrowRight01Icon className="size-3.5"/></QuietTextAction>}><Progress steps={book.steps} progress={current.progress}/></QuietSection>}</>}</>}
      {tab==='Activity'&&<QuietSection title="Customer work history" className="flush-section"><ol className="history-lines">{members.flatMap(s=>s.history.map((event,i)=><li key={`${s.id}-${i}`}><strong>{event}</strong><small>{s.title}</small></li>))}</ol></QuietSection>}
      {tab==='Linked work'&&<QuietSection title="Existing work across Helpin" className="flush-section">{members.some(s=>s.task)?members.filter(s=>s.task).map(s=><ResourceLink key={s.id} title={s.task!} meta={`Related to ${s.title}`} onClick={()=>onResource(s.task!,`Owner: ${s.taskOwner||'Omar Farooq'}\nStatus: In progress\nDue: ${s.taskDue||'September 8'}\n\n${s.task?.split(' · ')[1]}\n\nThe customer outcome is tracked separately.`)}/>):<p className="work-prose">No linked tasks or tickets are needed for this customer’s current work.</p>}</QuietSection>}
    </div><aside className="work-detail-rail"><QuietSection title="Relationship" className="rail-section"><Field label="Account owner"><Person name={accountOwner}/></Field><Field label="Success owner"><Person name={company==='Northstar'?'Sara Ahmed':ME}/></Field><Field label="Primary contact"><span>{members[0]?.author||'Customer team'}</span></Field>{company==='Northstar'&&<><Field label="Renewal"><span>September 30, 2026</span></Field><Field label="Annual contract"><span>$48,000 USD</span></Field><p className="work-small">From the sample customer agreement.</p></>}</QuietSection><QuietSection title="Connected playbooks" className="rail-section">{books.filter(b=>members.some(s=>s.playbook===b.id)).map(b=><ResourceLink key={b.id} title={b.name} meta={`Managed by ${ownerName(b.owner)}`} onClick={()=>onBook(b.id)}/>)}</QuietSection></aside></div>
  </>;
}
