export const categories = ['Retention', 'Expansion', 'Renewal', 'Conversion', 'Onboarding', 'Adoption', 'Prospecting', 'Needs context'] as const;
export type Category = typeof categories[number];
export type WorkState = 'Open' | 'Handled' | 'Dismissed';
export type Signal = {
  id: string; company: string; category: Category; title: string; consequence: string;
  owner: string; basis: string; priority: number; age: string; source: string; author: string;
  quote: string; next: string; state: WorkState; reviewed: boolean; history: string[];
  deadline?: string; context?: string; task?: string; doc?: string;
};
// Illustrative customer situations, not live customer records or verbatim real quotes.
export const seed: Signal[] = [
  { id: 'northstar-retention', company: 'Northstar', category: 'Retention', title: 'Customer is considering leaving after repeated sync failures', consequence: 'An unresolved reliability issue may put the account at risk. The customer has asked for a recovery plan.', owner: 'Muhammad Azhar', basis: 'Inherited · customer-success owner', priority: 22, age: '25m ago', source: 'Support conversation', author: 'Anna Lee · Operations lead', quote: 'This is the third time the sync has stopped this month. We need a clear recovery plan by Monday, or we will have to look at another platform.', next: 'Confirm the recovery plan with engineering, then respond to Anna with an owner and timeline.', deadline: 'Recovery plan requested by Sep 7', context: 'A separate Sep 4 email asks about adding 20 seats. Expansion interest does not resolve this reliability concern.', task: 'ENG-248 · Restore reliable CRM sync', state: 'Open', reviewed: false, history: [] },
  { id: 'content-expansion', company: 'Content studio', category: 'Expansion', title: 'Wants the Inbox add-on, but cannot complete the purchase', consequence: 'The customer has expressed purchase intent. Pricing and checkout access are the blockers; an annual upgrade is not confirmed.', owner: 'Muhammad Azhar', basis: 'Inherited · company owner', priority: 17, age: '1h ago', source: 'Support conversation', author: 'Maya Chen · Workspace admin', quote: 'We want to add Inbox, but the purchase button is disabled. Can you share the price and payment options? Is there a discount if we pay annually?', next: 'Check purchase eligibility and reply with the add-on price and available payment terms.', doc: 'Inbox add-on · Pricing & eligibility', state: 'Open', reviewed: false, history: [] },
  { id: 'meridian-renewal', company: 'Meridian', category: 'Renewal', title: 'Procurement needs the renewal terms before Friday', consequence: 'The renewal is waiting on commercial terms. The customer provided a procurement deadline, not a cancellation notice.', owner: 'Muhammad Azhar', basis: 'Inherited · deal owner', priority: 16, age: '2h ago', source: 'Email', author: 'Sam Rivera · Procurement', quote: 'Please send the revised renewal terms by Friday, September 11, so we can include them in this approval cycle.', next: 'Confirm the renewal terms and send the revised proposal to Sam.', deadline: 'Terms requested by Sep 11', state: 'Open', reviewed: false, history: [] },
  { id: 'orbit-conversion', company: 'Orbit', category: 'Conversion', title: 'Security approval is the last blocker to signing', consequence: 'The buyer reports readiness to proceed, subject to security approval. There is no confirmed close date.', owner: 'Muhammad Azhar', basis: 'Inherited · deal owner', priority: 13, age: '3h ago', source: 'Meeting', author: 'Leo Martin · VP of Sales', quote: 'The team is happy with the trial. Once our security team approves the questionnaire, we are ready to move forward.', next: 'Check the questionnaire status and confirm who owns the remaining answers.', state: 'Open', reviewed: true, history: ['Reviewed by Muhammad Azhar · Today, 10:12 AM'] },
  { id: 'luma-adoption', company: 'Luma', category: 'Adoption', title: 'Team has stopped using shared inbox assignments', consequence: 'The admin reports a workflow gap that may limit adoption. Account cancellation has not been mentioned.', owner: 'Muhammad Azhar', basis: 'Inherited · customer-success owner', priority: 10, age: '5h ago', source: 'Email', author: 'Priya Shah · Customer operations', quote: 'Most of the team went back to assigning messages in Slack. They are unsure who gets notified when an inbox assignment changes.', next: 'Clarify notification behavior and offer a short walkthrough for the team.', state: 'Open', reviewed: false, history: [] },
  { id: 'content-expansion-seats', company: 'Content studio', category: 'Expansion', title: 'A second team is asking about five additional seats', consequence: 'This is a separate seat request, not the Inbox purchase. Confirm the seat count before quoting.', owner: 'Muhammad Azhar', basis: 'Explicit · assigned by Sara Ahmed', priority: 9, age: 'Yesterday', source: 'Email', author: 'Noah Park · Team lead', quote: 'Our editorial team would also like access. Could you quote five extra seats on our current plan?', next: 'Confirm the five-seat requirement and send the applicable seat pricing.', state: 'Open', reviewed: false, history: [] },
  { id: 'brightside-onboarding', company: 'Brightside', category: 'Onboarding', title: 'Import errors are blocking the team’s first workspace', consequence: 'The rollout is paused until the import succeeds. An onboarding owner needs to validate the failed records.', owner: 'Sara Ahmed', basis: 'Inherited · customer-success owner', priority: 15, age: '45m ago', source: 'Support conversation', author: 'Alex Kim · Workspace admin', quote: 'The contact import keeps failing. We cannot invite the rest of the team until these records are in the workspace.', next: 'Inspect the failed import and help Alex complete the workspace setup.', state: 'Open', reviewed: false, history: [] },
  { id: 'fieldwork-retention', company: 'Fieldwork', category: 'Retention', title: 'Admin asks how to export data before cancellation', consequence: 'The customer has asked about leaving. Their reason and final decision still need confirmation.', owner: 'Sara Ahmed', basis: 'Inherited · customer-success owner', priority: 19, age: '2h ago', source: 'Support conversation', author: 'Jamie Moore · Account admin', quote: 'What is the process to export our records before cancelling? We are reviewing our tools this month.', next: 'Ask what is driving the review and provide accurate export guidance.', state: 'Open', reviewed: false, history: [] },
  { id: 'atlas-prospecting', company: 'Atlas', category: 'Prospecting', title: 'New inquiry asks about a 40-person sales workspace', consequence: 'A prospective buyer has described a team size and use case. Budget and buying timeline are unknown.', owner: '', basis: 'No signal owner', priority: 8, age: '4h ago', source: 'Email', author: 'Chris Evans · Sales operations', quote: 'We are looking for a shared workspace for our sales team of 40. Do you support shared account notes and inboxes?', next: 'Assign an owner to qualify the team’s needs and respond to the inquiry.', state: 'Open', reviewed: false, history: [] },
  { id: 'unresolved-context', company: 'Unresolved customer', category: 'Needs context', title: 'Pricing request could not be matched to a customer', consequence: 'The sender could not be confidently linked to a customer. Confirm identity before treating this as an opportunity.', owner: '', basis: 'No signal owner', priority: 3, age: 'Yesterday', source: 'Email', author: 'Taylor · External sender', quote: 'Could you send us the pricing we discussed?', next: 'Verify the sender and link the right customer before deciding how to follow up.', state: 'Open', reviewed: false, history: [] },
  { id: 'cedar-handled', company: 'Cedar', category: 'Expansion', title: 'Requested seat pricing has been sent', consequence: 'The current request has been addressed. Any subsequent customer response should be evaluated separately.', owner: 'Muhammad Azhar', basis: 'Inherited · company owner', priority: 9, age: 'Yesterday', source: 'Email', author: 'Jordan Wu · Workspace admin', quote: 'Can you share the cost of three more seats?', next: 'No further signal-level action is recorded for this request.', state: 'Handled', reviewed: true, history: ['Handled by Muhammad Azhar · Yesterday, 3:40 PM', 'Outcome: Sent the three-seat quote and payment link.'] },
];
