import { useState } from 'react';
import { QuietEmptyState, QuietPageHeader, QuietPrimaryAction, QuietSearchInput, QuietSection, QuietTextAction } from '@/components/design-system/quiet';
import { ArrowRight01Icon } from '@/lib/icons';
import { ME, isAttention, ownerName, type Playbook, type Scene, type Situation } from './workspace-data';
import { Field, LineTabs, Person, Picker, Progress, ResourceLink, StateText, SurfaceState } from './workspace-ui';

export function PlaybooksWorkspace({ books, situations, onOpen, onNew, scene, onRetry }: { books: Playbook[]; situations: Situation[]; onOpen: (id:string)=>void; onNew: ()=>void; scene: Scene; onRetry: ()=>void }) {
  const [query,setQuery]=useState('');
  const [status,setStatus]=useState('Any status');
  const [owner,setOwner]=useState('All owners');
  const rows=books.filter(b=>`${b.name} ${b.description}`.toLowerCase().includes(query.toLowerCase())&&(status==='Any status'||b.enabled===(status==='Enabled'))&&(owner==='All owners'||b.owner===ME));
  return <><QuietPageHeader title="Playbooks" description="Repeatable customer processes, with people in control." actions={<QuietPrimaryAction disabled={scene==='Read-only'} onClick={onNew}>Create playbook</QuietPrimaryAction>}/>
    <div className="queue-toolbar playbook-toolbar"><QuietSearchInput aria-label="Search playbooks" placeholder="Search playbooks…" value={query} onChange={e=>setQuery(e.target.value)} containerClassName="signal-search"/><div className="queue-filters"><Picker label="Playbook status" value={status} options={['Any status','Enabled','Disabled']} onChange={setStatus}/><Picker label="Playbook owner" value={owner} options={['All owners','Owned by me']} onChange={setOwner}/></div></div>
    <SurfaceState scene={scene} onRetry={onRetry} emptyTitle="No playbooks in this view"><table className="work-table playbooks-table" aria-label="Playbooks"><thead><tr>{['Playbook','Owner','Status','Active customers','Needs attention'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{rows.map(b=>{const members=situations.filter(s=>s.playbook===b.id);return <tr key={b.id} onClick={()=>onOpen(b.id)}><td><button className="table-signal-title"><strong>{b.name}</strong></button><span className="work-next">{b.description}</span></td><td><Person name={b.owner}/></td><td><StateText value={b.enabled?'Enabled':'Disabled'}/></td><td className="tabular-nums">{members.filter(s=>s.status!=='Resolved').length}</td><td>{members.some(isAttention)?<span className="text-quiet-accent">{members.filter(isAttention).length} to review</span>:<span className="muted">None</span>}</td></tr>;})}</tbody></table>{!rows.length&&<QuietEmptyState title="No matching playbooks" description="Try a different name, owner, or status." action={<QuietTextAction onClick={()=>{setQuery('');setStatus('Any status');setOwner('All owners');}}>Clear filters</QuietTextAction>}/>}</SurfaceState>
    <div className="work-footnote">Customer processes live here. Their execution is shared with Automation.</div>
  </>;
}

export function PlaybookDetail({ book, situations, initialTab='Overview', readOnly, onEdit, onApply, onToggle, onOpen, onFlow }: {
  book: Playbook; situations: Situation[]; initialTab?: string; readOnly: boolean; onEdit: ()=>void; onApply: ()=>void; onToggle: ()=>void; onOpen: (id:string)=>void; onFlow: ()=>void;
}) {
  const [tab,setTab]=useState(initialTab);
  const [filter,setFilter]=useState('All customers');
  const [query,setQuery]=useState('');
  const members=situations.filter(s=>s.playbook===book.id);
  const active=members.filter(s=>s.status!=='Resolved');
  const completed=members.filter(s=>s.status==='Resolved');
  const filtered=members.filter(s=>(filter==='All customers'||filter==='Active'&&s.status!=='Resolved'||filter==='Completed'&&s.status==='Resolved'||filter==='Needs attention'&&isAttention(s))&&s.company.toLowerCase().includes(query.toLowerCase()));
  return <><QuietPageHeader title={book.name} description={book.description} actions={<><QuietTextAction disabled={readOnly||!book.enabled} onClick={onApply}>Apply to customer</QuietTextAction><QuietPrimaryAction disabled={readOnly} onClick={onEdit}>Edit playbook</QuietPrimaryAction></>}/>
    <div className="book-metadata"><StateText value={book.enabled?'Enabled':'Disabled'}/><span>{book.category}</span><span>Published version {book.version}</span></div>
    <LineTabs label="Playbook views" value={tab} onChange={setTab} items={[{value:'Overview',label:'Overview'},{value:'Customers',label:'Customers',count:members.length},{value:'Outcomes',label:'Outcomes',count:completed.length}]}/>
    {tab==='Overview'&&<div className="work-detail-layout"><div className="work-detail-main"><QuietSection title="Customer outcome" className="flush-section"><p className="work-prose">{book.goal}</p></QuietSection><QuietSection title="How this playbook runs" className="flush-section" action={<QuietTextAction onClick={onFlow}>Open flow <ArrowRight01Icon className="size-3.5"/></QuietTextAction>}><Progress steps={book.steps} progress={-1}/></QuietSection><QuietSection title="When work stops" className="flush-section"><p className="work-prose">{book.stop}.</p></QuietSection></div><aside className="work-detail-rail"><QuietSection title="Configuration" className="rail-section"><Field label="Owner"><Person name={book.owner}/></Field><Field label="Starts when"><span>{book.trigger}</span></Field><Field label="Applies to"><span>{book.audience}</span></Field><Field label="Approval"><span>{book.approval}</span></Field><Field label="Follow-up"><span>{book.delay}</span></Field></QuietSection><QuietSection title="In progress" className="rail-section"><ResourceLink title={`${active.length} active customers`} meta={`${active.filter(isAttention).length} need a decision or action`} onClick={()=>setTab('Customers')}/><ResourceLink title={`${completed.length} recorded outcomes`} meta="Customer results, not agent runs" onClick={()=>setTab('Outcomes')}/></QuietSection><QuietSection title="Enrollment" className="rail-section"><p className="work-small">{book.enabled?'New matching customers can enter this playbook.':'New customers will not enter this playbook.'} Active customer work is controlled separately.</p><QuietTextAction disabled={readOnly} onClick={onToggle}>{book.enabled?'Disable new enrollments':'Enable new enrollments'}</QuietTextAction></QuietSection></aside></div>}
    {tab==='Customers'&&<><div className="queue-toolbar"><QuietSearchInput aria-label="Search participating customers" placeholder="Search customers…" value={query} onChange={e=>setQuery(e.target.value)} containerClassName="signal-search"/><Picker label="Participating customer state" value={filter} options={['All customers','Active','Needs attention','Completed']} onChange={setFilter}/></div><table className="work-table" aria-label="Participating customers"><thead><tr>{['Customer','Owner','Progress','Next step','Status'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.map(s=><tr key={s.id} onClick={()=>onOpen(s.id)}><td><button className="table-signal-title"><strong>{s.company}</strong></button><small>{s.title}</small></td><td><Person name={s.owner}/></td><td><div className="mini-progress"><span style={{width:`${Math.min(s.progress/book.steps.length,1)*100}%`}}/></div><small>{Math.min(s.progress,book.steps.length)} of {book.steps.length} milestones</small></td><td>{s.next}</td><td><StateText value={s.status}/></td></tr>)}</tbody></table>{!filtered.length&&<QuietEmptyState title="No customers match this view" description="Change the filter or search to find their work." action={<QuietTextAction onClick={()=>{setFilter('All customers');setQuery('');}}>Clear filters</QuietTextAction>}/>}</>}
    {tab==='Outcomes'&&<><QuietSection title="Recorded customer results" className="flush-section"><p className="work-prose">{completed.length} {completed.length===1?'customer has':'customers have'} a confirmed outcome. {active.length} remain in progress.</p></QuietSection><table className="work-table" aria-label="Playbook outcomes"><thead><tr><th>Customer</th><th>Outcome</th><th>Confirmed by</th><th>Evidence</th></tr></thead><tbody>{completed.map(s=><tr key={s.id} onClick={()=>onOpen(s.id)}><td><button><strong>{s.company}</strong></button></td><td>{s.outcome}</td><td>{ownerName(s.owner)}</td><td><QuietTextAction onClick={e=>{e.stopPropagation();onOpen(s.id);}}>View confirmation <ArrowRight01Icon className="size-3.5"/></QuietTextAction></td></tr>)}</tbody></table>{!completed.length&&<QuietEmptyState title="No confirmed outcomes yet" description="Completed runs are not counted as customer outcomes. Results appear when confirmed by evidence or an explicit decision."/>}</>}
  </>;
}
