import { useState } from 'react';
import { QuietPageHeader, QuietPrimaryAction, QuietSection, QuietTextAction } from '@/components/design-system/quiet';
import { Field, Picker, TextField } from './workspace-ui';
import { people, type Playbook, type Step } from './workspace-data';

export function PlaybookEditor({ book, readOnly, onCancel, onPreview }: { book: Playbook; readOnly: boolean; onCancel: ()=>void; onPreview: (book:Playbook)=>void }) {
  const [draft,setDraft]=useState<Playbook>(()=>structuredClone(book));
  const [section,setSection]=useState('Basics');
  const [error,setError]=useState('');
  const update=(patch:Partial<Playbook>)=>setDraft(old=>({...old,...patch}));
  const patchStep=(index:number,patch:Partial<Step>)=>update({steps:draft.steps.map((step,i)=>i===index?{...step,...patch}:step)});
  const preview=()=>{if(!draft.name.trim()||!draft.goal.trim()||draft.steps.some(s=>!s.name.trim())){setError('Add a name, customer outcome, and a name for every step.');return;}setError('');onPreview(draft);};
  return <><QuietPageHeader title={book.version===0?'Create playbook':`Edit ${book.name}`} description="Changes stay in draft until you publish." actions={<><QuietTextAction onClick={onCancel}>Cancel</QuietTextAction><QuietPrimaryAction disabled={readOnly} onClick={preview}>Preview & publish</QuietPrimaryAction></>}/>
    {error&&<p className="work-warning" role="alert">{error}</p>}
    <div className="editor-layout"><nav className="editor-nav" aria-label="Playbook configuration">{['Basics','Entry & ownership','Steps','Permissions','Stop conditions'].map((name,i)=><button key={name} aria-current={section===name?'step':undefined} onClick={()=>setSection(name)}><span>{i+1}</span>{name}</button>)}<p>One business process.<br/>Shared Flows and Agents.</p></nav><div className="editor-body">
      {section==='Basics'&&<QuietSection title="What should this playbook achieve?" className="flush-section"><Field label="Name"><TextField label="Playbook name" value={draft.name} onChange={name=>update({name})} disabled={readOnly}/></Field><Field label="Purpose"><TextField label="Playbook purpose" value={draft.description} onChange={description=>update({description})} disabled={readOnly}/></Field><Field label="Team"><Picker label="Playbook team" value={draft.category} options={['Sales','Customer success']} onChange={category=>update({category})} disabled={readOnly}/></Field><Field label="Customer outcome" hint="What changes for the customer—not how many tasks we finish."><textarea aria-label="Customer outcome" value={draft.goal} onChange={e=>update({goal:e.target.value})} disabled={readOnly} rows={3}/></Field><div className="editor-next"><QuietTextAction onClick={()=>setSection('Entry & ownership')}>Continue to entry & ownership →</QuietTextAction></div></QuietSection>}
      {section==='Entry & ownership'&&<QuietSection title="Who enters, and who owns the work?" className="flush-section"><Field label="Starts when"><Picker label="Entry trigger" value={draft.trigger} options={[draft.trigger,'A qualifying buying-intent signal appears','A deal is marked closed won','Renewal is approaching or a credible risk appears'].filter((v,i,a)=>a.indexOf(v)===i)} onChange={trigger=>update({trigger})} disabled={readOnly}/></Field><Field label="Customers"><TextField label="Eligible customers" value={draft.audience} onChange={audience=>update({audience})} disabled={readOnly}/></Field><Field label="Playbook owner"><Picker label="Configure playbook owner" value={draft.owner} options={people} onChange={owner=>update({owner})} disabled={readOnly}/></Field><Field label="Situation ownership"><span>Use the existing account or deal owner. Flag missing ownership.</span></Field><Field label="Already participating"><span>Continue the existing process. Do not enroll twice.</span></Field><div className="editor-next"><QuietTextAction onClick={()=>setSection('Steps')}>Continue to steps →</QuietTextAction></div></QuietSection>}
      {section==='Steps'&&<QuietSection title="Steps and milestones" className="flush-section" action={<QuietTextAction disabled={readOnly} onClick={()=>update({steps:[...draft.steps,{name:'Review the customer’s next milestone',actor:'Person',detail:'Confirm what the customer needs next.'}]})}>Add step</QuietTextAction>}><div className="editable-steps">{draft.steps.map((step,i)=><div key={i} className="editable-step"><span className="editable-step-number">{i+1}</span><div><TextField label={`Step ${i+1} name`} value={step.name} onChange={name=>patchStep(i,{name})} disabled={readOnly}/><textarea aria-label={`Step ${i+1} instructions`} value={step.detail} onChange={e=>patchStep(i,{detail:e.target.value})} rows={2} disabled={readOnly}/><Picker label={`Step ${i+1} responsibility`} value={step.actor} options={['Agent','Person','Approval','Wait']} onChange={actor=>patchStep(i,{actor:actor as Step['actor']})} disabled={readOnly}/></div><QuietTextAction aria-label={`Remove step ${i+1}`} disabled={readOnly||draft.steps.length<=1} onClick={()=>update({steps:draft.steps.filter((_,n)=>n!==i)})}>Remove</QuietTextAction></div>)}</div><div className="editor-next"><QuietTextAction onClick={()=>setSection('Permissions')}>Continue to permissions →</QuietTextAction></div></QuietSection>}
      {section==='Permissions'&&<QuietSection title="Keep people in control" className="flush-section"><Field label="Customer messages"><span>Prepare automatically · Human approval before sending</span></Field><Field label="Approver"><Picker label="Approval owner" value={draft.approval} options={['Situation owner','Customer success owner','Playbook owner']} onChange={approval=>update({approval})} disabled={readOnly}/></Field><Field label="Research and drafts"><span className="text-quiet-positive">Allowed automatically</span></Field><Field label="Create or update a deal"><span>Require approval of the exact change</span></Field><Field label="PM tasks"><span>Only for a real commitment · Require owner approval</span></Field><Field label="Commercial terms"><span>Never offer unapproved pricing or commitments</span></Field><Field label="Customer contact"><span>Respect opt-outs, recent replies, and other active playbooks</span></Field><p className="work-footnote">These policies are enforced outside the agent’s prompt. Advanced tool access is managed in Automation.</p><div className="editor-next"><QuietTextAction onClick={()=>setSection('Stop conditions')}>Continue to stop conditions →</QuietTextAction></div></QuietSection>}
      {section==='Stop conditions'&&<QuietSection title="Know when to wait, stop, or ask" className="flush-section"><Field label="Next checkpoint"><Picker label="Follow-up delay" value={draft.delay} options={['1 business day','2 business days','3 business days','5 business days']} onChange={delay=>update({delay})} disabled={readOnly}/></Field><Field label="Stop when"><textarea aria-label="Stop conditions" value={draft.stop} onChange={e=>update({stop:e.target.value})} rows={3} disabled={readOnly}/></Field><Field label="Approval expires"><span>After 3 business days · Halt and notify the owner</span></Field><Field label="Uncertain delivery"><span>Check the result before any retry</span></Field><Field label="Missing owner or data"><span>Pause the affected action and request attention</span></Field><Field label="Existing customers"><span>Keep their published configuration unless explicitly migrated</span></Field><div className="editor-next"><QuietTextAction disabled={readOnly} onClick={preview}>Preview the complete playbook →</QuietTextAction></div></QuietSection>}
    </div></div>
  </>;
}
