import { useEffect, useState } from 'react';
import { EditorContent, useEditor } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import { QuietComposerEditorSurface, QuietComposerToolbar, QuietConversationComposer, QuietIconAction, QuietPrimaryAction, QuietSection, QuietTextAction } from '@/components/design-system/quiet';
import { SheetDescription, SheetTitle } from '@/components/ui/sheet';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { ArrowRight01Icon, Cancel01Icon, MoreHorizontalIcon } from '@/lib/icons';
import { ME, people, type Playbook, type Situation } from './workspace-data';
import { Field, Picker, ResourceLink, StateText, TextField } from './workspace-ui';

export type SituationAction = 'send' | 'handoff' | 'assign' | 'pause' | 'resume' | 'resolve' | 'reject' | 'task' | 'reopen' | 'apply-change';
export function SituationDrawer({ situation:s, book:publishedBook, readOnly, onClose, onPatch, onAction, onCustomer, onBook, onResource }: {
  situation:Situation; book?:Playbook; readOnly:boolean; onClose:()=>void; onPatch:(patch:Partial<Situation>,event:string)=>void;
  onAction:(action:SituationAction,patch?:Partial<Situation>)=>void; onCustomer:()=>void; onBook:()=>void; onResource:(title:string,body:string)=>void;
}) {
  const [receiver,setReceiver]=useState(ME);
  const book=s.configuration||publishedBook;
  const [goal,setGoal]=useState(s.goal);
  const [fields,setFields]=useState(s.change?.fields||[]);
  const editor=useEditor({extensions:[StarterKit],content:s.draft.split('\n\n').map(p=>`<p>${p.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('\n','<br>')}</p>`).join(''),editable:!readOnly,editorProps:{attributes:{'aria-label':'Prepared customer response',class:'prepared-editor'}}},[s.id]);
  useEffect(()=>{editor?.setEditable(!readOnly);},[editor,readOnly]);
  const preparing=(s.status==='Needs approval'||s.status==='Delivery failed'||s.status==='Needs attention')&&!!s.draft;
  const terminal=s.status==='Resolved';
  const paused=s.status==='Paused';
  const source=()=>onResource(`${s.source} · ${s.company}`,`${s.author} · ${s.time}\n\n“${s.quote}”`);
  const send=()=>onAction('send',{draft:editor?.getText({blockSeparator:'\n\n'})||s.draft});
  return <>
    <div className="work-drawer-header"><div className="compact-detail-topline"><QuietTextAction className="detail-company-link" onClick={onCustomer}>{s.company}<ArrowRight01Icon className="size-3"/></QuietTextAction><div className="compact-detail-tools"><DropdownMenu><DropdownMenuTrigger asChild><QuietIconAction aria-label="More situation actions"><MoreHorizontalIcon className="size-4"/></QuietIconAction></DropdownMenuTrigger><DropdownMenuContent align="end">
      {!s.reviewed&&<DropdownMenuItem disabled={readOnly} onSelect={()=>onPatch({reviewed:true},'Evidence reviewed by you · Just now')}>Mark evidence reviewed</DropdownMenuItem>}
      {!terminal&&<DropdownMenuItem disabled={readOnly} onSelect={()=>onAction(paused?'resume':'pause')}>{paused?'Resume customer work':'Pause customer work'}</DropdownMenuItem>}
      {!terminal&&<DropdownMenuItem disabled={readOnly} onSelect={()=>onAction('resolve')}>Record an outcome</DropdownMenuItem>}
      {!terminal&&<DropdownMenuItem disabled={readOnly||!!s.task} onSelect={()=>onAction('task')}>{s.task?'Follow-up task already linked':'Create a follow-up task'}</DropdownMenuItem>}
      {terminal&&<DropdownMenuItem disabled={readOnly} onSelect={()=>onAction('reopen')}>Reopen for follow-up</DropdownMenuItem>}
      <DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>onResource('Situation history',s.history.join('\n\n'))}>View activity</DropdownMenuItem>
    </DropdownMenuContent></DropdownMenu><QuietIconAction aria-label="Close situation" onClick={onClose}><Cancel01Icon className="size-4"/></QuietIconAction></div></div><SheetTitle className="detail-title">{s.title}</SheetTitle><SheetDescription className="sr-only">Evidence, next action, and customer progress.</SheetDescription><div className="work-drawer-meta"><span>{s.category}</span><StateText value={s.status}/><div className="compact-assignee"><span>Owner</span><Picker label="Situation owner" value={s.owner||'Unassigned'} options={[...people,'Unassigned']} disabled={readOnly} onChange={owner=>onPatch({owner:owner==='Unassigned'?'':owner},`Situation assigned to ${owner} · Just now`)}/></div></div></div>
    <div className="detail-scroll">
      {terminal?<QuietSection title="Customer outcome" className="drawer-section"><p className="work-prose">{s.outcome}</p><p className="work-small">{s.history[0]?.includes('Just now')?'Recorded from your decision · Just now':`Recorded from ${s.source.toLowerCase()} · ${s.time}`}</p></QuietSection>:paused?<QuietSection title="Work is paused" className="drawer-section"><p className="work-prose">No new automated actions will run for this situation. Previous activity and linked work are unchanged.</p></QuietSection>:s.status==='Delivery failed'?<QuietSection title="Nothing was sent" className="drawer-section"><p className="work-prose">The email connection expired before delivery. Review the response below, then reconnect to send it.</p></QuietSection>:null}
      <QuietSection title={s.kind==='handoff'?'Customer’s goal':'What changed'} className="drawer-section" action={<QuietTextAction onClick={source}>View source <ArrowRight01Icon className="size-3"/></QuietTextAction>}><blockquote className="work-quote">{s.quote}</blockquote><div className="source-byline">{s.author} · {s.source} · {s.time}</div></QuietSection>
      {!terminal&&!paused&&s.kind==='handoff'&&s.status!=='Waiting'&&<QuietSection title="Accept the handoff" className="drawer-section"><div className="commitment-list"><p><strong>Sold scope</strong><span>12 support agents · Annual agreement</span></p><p><strong>Commitment to preserve</strong><span>Help import the existing knowledge base.</span></p><p><strong>Open dependency</strong><span>Customer to send the export before September 10.</span></p></div><Field label="Receiving owner"><Picker label="Receiving success owner" value={receiver} options={people} onChange={setReceiver} disabled={readOnly}/></Field><Field label="First-value goal"><TextField label="First-value goal" value={goal} onChange={setGoal} disabled={readOnly}/></Field><p className="work-small">Daniel owns the handoff until you accept. No project or task is created automatically.</p></QuietSection>}
      {preparing&&!paused&&<QuietSection title="Prepared response" className="drawer-section" action={<span className="work-small">To {s.author}</span>}><QuietConversationComposer><QuietComposerEditorSurface><EditorContent editor={editor}/></QuietComposerEditorSurface>{editor&&!readOnly&&<QuietComposerToolbar editor={editor} showShortcut={false}/>}</QuietConversationComposer><div className="source-byline">Based on the customer’s message{s.task?' and the linked investigation':''}. Edit before approving.</div></QuietSection>}
      {!terminal&&!paused&&s.status==='Waiting'&&<QuietSection title="Next checkpoint" className="drawer-section"><p className="work-prose">{s.next}.</p><p className="work-small">{s.id==='northstar-expansion'?'A separate renewal situation is handling the sync issue. No expansion message will be sent while that hold applies.':'A new customer reply will cancel the scheduled nudge and update the next step.'}</p></QuietSection>}
      {!terminal&&!paused&&s.change&&!s.change.applied&&<QuietSection title={s.change.kind} className="drawer-section" action={<QuietTextAction onClick={()=>onResource(s.change!.target,`Target record: ${s.change!.target}\n\n${s.change!.fields.map(f=>`${f.label}: ${f.before}`).join('\n')}\n\nSource: ${s.author} · ${s.source}`)}>View record <ArrowRight01Icon className="size-3"/></QuietTextAction>}><p className="work-small change-target">{s.change.target}</p><table className="work-table change-table" aria-label="Proposed CRM changes"><thead><tr><th>Field</th><th>Current</th><th>Proposed</th></tr></thead><tbody>{fields.map((f,i)=><tr key={f.label}><td>{f.label}</td><td>{f.before}</td><td><TextField label={`Proposed ${f.label}`} value={f.after} onChange={after=>setFields(old=>old.map((item,n)=>n===i?{...item,after}:item))} disabled={readOnly}/></td></tr>)}</tbody></table><p className="work-small">Only these fields will change. No customer message will be sent.</p></QuietSection>}
      {s.change?.applied&&<QuietSection title="CRM change applied" className="drawer-section"><p className="work-prose">{s.change.target}</p>{s.change.fields.map(f=><Field key={f.label} label={f.label}><span>{f.after}</span></Field>)}<p className="work-small">The record was updated. That does not by itself confirm the customer’s goal was achieved.</p></QuietSection>}
      {!terminal&&!paused&&s.kind==='manual'&&!s.change&&<QuietSection title={s.owner?'Responsible for the next step':'Choose who takes this forward'} className="drawer-section"><p className="work-prose">{s.owner?`${s.owner===ME?'You':s.owner} owns this request. Follow up with the customer and record what happens.`:'This request has no owner yet. Assign it to yourself or a teammate; a playbook or task isn’t required.'}</p></QuietSection>}
      {s.task&&<QuietSection title="Existing work" className="drawer-section"><ResourceLink title={s.task} meta={`${s.taskOwner||'Omar Farooq'} · In progress · Due ${s.taskDue||'September 8'}`} onClick={()=>onResource(s.task!,`Owner: ${s.taskOwner||'Omar Farooq'}\nStatus: In progress\nDue: ${s.taskDue||'September 8'}\n\n${s.task?.split(' · ')[1]}\n\nCompleting this task does not confirm the customer’s issue is resolved.`)}/></QuietSection>}
      <QuietSection className="drawer-section"><div className="drawer-progress-link">{book?<><span className="work-small">{book.name} · {Math.min(s.progress,book.steps.length)} of {book.steps.length} milestones</span><QuietTextAction onClick={onBook}>Playbook <ArrowRight01Icon className="size-3"/></QuietTextAction></>:<span className="work-small">Manually managed customer work</span>}</div><QuietTextAction onClick={onCustomer}>View customer progress <ArrowRight01Icon className="size-3.5"/></QuietTextAction></QuietSection>
    </div>
    <div className="decision-footer work-drawer-footer">
      {readOnly?<span className="work-small">Read-only access</span>
      :terminal?<><span className="work-small">Outcome recorded</span><QuietTextAction onClick={()=>onAction('reopen')}>Reopen for follow-up</QuietTextAction></>
      :paused?<><span className="work-small">Linked work is unchanged</span><QuietPrimaryAction onClick={()=>onAction('resume')}>Resume work</QuietPrimaryAction></>
      :s.change&&!s.change.applied?<><QuietTextAction onClick={()=>onAction('reject')}>Request changes</QuietTextAction><QuietPrimaryAction disabled={fields.some(f=>!f.after.trim())} onClick={()=>onAction('apply-change',{change:{...s.change!,fields,applied:true}})}>Approve & apply</QuietPrimaryAction></>
      :preparing?<><QuietTextAction onClick={()=>onAction('reject')}>Don’t send</QuietTextAction><QuietPrimaryAction onClick={send} disabled={!editor?.getText().trim()}>{s.status==='Delivery failed'?'Reconnect & send':s.status==='Needs attention'?'Approve revised response':'Approve & send'}</QuietPrimaryAction></>
      :s.kind==='handoff'&&s.status!=='Waiting'?<><QuietTextAction onClick={()=>onAction('reject')}>Request changes</QuietTextAction><QuietPrimaryAction disabled={!goal.trim()} onClick={()=>onAction('handoff',{owner:receiver,goal})}>Accept handoff</QuietPrimaryAction></>
      :s.kind==='manual'&&!s.owner?<><QuietTextAction onClick={()=>onAction('resolve')}>No action needed</QuietTextAction><QuietPrimaryAction onClick={()=>onAction('assign')}>Assign to me</QuietPrimaryAction></>
      :<><span className="work-small">{s.kind==='manual'?'Customer follow-through is still open':'Waiting on the next customer event'}</span><QuietTextAction onClick={()=>onAction('resolve')}>Record outcome</QuietTextAction></>}
    </div>
  </>;
}
