import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const artifacts = fileURLToPath(new URL('./artifacts/', import.meta.url));
await mkdir(artifacts, { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const url = process.env.SIGNALS_PREVIEW_URL || 'http://127.0.0.1:5187/design-preview/signals/';
const picker = async (name, value) => {
  await page.getByRole('combobox', { name, exact: true }).click();
  await page.getByRole('option', { name: value, exact: true }).click();
};
const categories = page.getByRole('navigation', { name: 'Signal categories' });
const chooseCategory = name => categories.getByRole('button', { name: new RegExp(`^${name}`) }).click();
const moreAction = async name => {
  await page.getByRole('button', { name: 'More signal actions' }).click();
  await page.getByRole('menuitem', { name, exact: true }).click();
};
const screenshot = async name => {
  // The toast lasts 5 seconds; leave room beyond its lifetime for browser scheduling.
  await expect(page.locator('.preview-toast')).not.toHaveClass(/visible/, { timeout: 8000 });
  await page.screenshot({ path: `${artifacts}${name}.png`, fullPage: true, animations: 'disabled' });
};
const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);

try {
  await page.goto(url);
  await expect(page.getByTestId('signal-row')).toHaveCount(6);
  await expect(page.getByRole('tablist', { name: 'Responsibility' })).toHaveCount(0);
  await expect(page.getByRole('combobox', { name: 'Assignment', exact: true })).toContainText('Mine');
  await expect(page.getByRole('combobox', { name: 'Review state', exact: true })).toBeVisible();
  await expect(page.getByRole('combobox', { name: 'Priority', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'More filters', exact: true })).toHaveCount(0);
  await expect(page.getByTestId('signal-row').first()).toContainText('Northstar');
  await expect(page.getByTestId('signal-row').first().locator('strong')).toHaveText('Sync failures are putting the account at risk');
  await expect(page.locator('.signal-row .owner-cell')).toHaveCount(0);
  await expect(page.locator('.signal-row .event-category')).toHaveCount(6);
  await expect(page.getByTestId('signal-row').nth(1).locator('.event-context')).toHaveCount(0);
  await expect(categories.getByRole('button')).toHaveCount(9);
  await screenshot('desktop-queue');
  await noOverflow();
  console.log('PASS: default Mine, individual priority ranking, all categories visible');

  await picker('Review state', 'Reviewed');
  await picker('Priority', 'High priority');
  await screenshot('active-filters');
  await expect(page.getByTestId('signal-row')).toHaveCount(0);
  await expect(page.getByRole('combobox', { name: 'Review state', exact: true })).toContainText('Reviewed');
  await expect(page.getByRole('combobox', { name: 'Priority', exact: true })).toContainText('High priority');
  await picker('Priority', 'Any priority');
  await expect(page.getByTestId('signal-row')).toHaveCount(1);
  await picker('Review state', 'Any review state');
  await expect(page.getByTestId('signal-row')).toHaveCount(6);
  console.log('PASS: all four toolbar filters stay visible and apply independently');

  await chooseCategory('Retention');
  await expect(page.getByTestId('signal-row')).toHaveCount(1);
  await expect(page.locator('.signal-row .event-category')).toHaveCount(0);
  await expect(page.getByTestId('signal-row').first()).toContainText('Recovery plan requested by Sep 7');
  await expect(categories.getByRole('button', { name: /^Expansion/ })).toContainText('2');
  await page.getByTestId('signal-row').first().click();
  await expect(page.getByText('Also asked about 20 more seats; the sync issue is still unresolved.')).toBeVisible();
  await expect(page.getByText('Why it matters', { exact: true })).toHaveCount(0);
  await expect(page.getByText('Ownership & activity', { exact: true })).toHaveCount(0);
  await expect(page.getByText('No decisions recorded yet.', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: /ENG-248/ })).toBeVisible();
  await screenshot('retention-detail');
  await page.getByRole('button', { name: 'Open conversation', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Sample source/ })).toBeVisible();
  await page.keyboard.press('Escape');
  await moreAction('Mark reviewed');
  await expect(page.getByRole('button', { name: 'Mark handled', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Close signal' }).click();
  await expect(page.getByTestId('signal-row')).toHaveCount(1);
  await expect(page.getByTestId('signal-row').first()).toBeFocused();
  console.log('PASS: direct retention access, contextual evidence, source preview, review does not handle, focus restored');

  await chooseCategory('Expansion');
  await expect(page.getByTestId('signal-row')).toHaveCount(2);
  await page.getByTestId('signal-row').first().click();
  await expect(page.getByRole('heading', { name: 'Inbox purchase blocked', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: /Pricing & eligibility/ })).toBeVisible();
  await screenshot('expansion-detail');
  await page.getByRole('button', { name: 'Mark handled', exact: true }).click();
  await page.getByLabel('Outcome note').fill('Sent add-on price and restored checkout access.');
  await page.getByRole('button', { name: 'Confirm handled', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Reopen signal' })).toBeVisible();
  await page.getByRole('button', { name: 'Close signal' }).click();
  await expect(page.getByTestId('signal-row')).toHaveCount(1);
  await expect(page.getByTestId('signal-row')).toContainText('Five additional seats requested');
  await picker('Work state', 'Handled');
  await expect(page.getByTestId('signal-row')).toHaveCount(2);
  await page.getByTestId('signal-row').first().click();
  await moreAction('View activity');
  await expect(page.getByText(/Handled by Muhammad Azhar · Just now/)).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Reopen signal' }).click();
  await page.getByRole('button', { name: 'Close signal' }).click();
  console.log('PASS: optional note, independently handled requests, history, handled view, reopen');

  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await picker('Assignment', 'Unassigned');
  await expect(page.getByTestId('signal-row')).toHaveCount(2);
  await page.getByTestId('signal-row').first().click();
  await picker('Assign signal', 'Muhammad Azhar');
  await page.getByRole('button', { name: 'Close signal' }).click();
  await expect(page.getByTestId('signal-row')).toHaveCount(1);
  await picker('Assignment', 'Mine');
  await expect(page.getByTestId('signal-row')).toHaveCount(7);
  await page.getByLabel('Search signals').fill('Atlas');
  await expect(page.getByTestId('signal-row')).toHaveCount(1);
  await page.getByTestId('signal-row').first().click();
  await moreAction('Dismiss');
  await picker('Dismissal reason', 'Incorrect evidence');
  await page.getByRole('button', { name: 'Confirm dismissal' }).click();
  await page.getByRole('button', { name: 'Close signal' }).click();
  await expect(page.getByTestId('signal-row')).toHaveCount(0);
  await picker('Work state', 'Dismissed');
  await expect(page.getByTestId('signal-row')).toHaveCount(1);
  console.log('PASS: unassigned, reassignment, scoped search, dismissal reason, historical work view');

  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await picker('Preview state', 'Loading');
  await expect(page.locator('.queue-caption')).toHaveCount(0);
  await expect(page.locator('.queue-table')).toHaveAttribute('aria-busy', 'true');
  await expect(categories.getByRole('button').first()).toContainText('—');
  await screenshot('loading');
  await picker('Preview state', 'Error');
  await expect(page.getByRole('alert')).toContainText('couldn’t load');
  await screenshot('error');
  await page.getByRole('button', { name: 'Retry', exact: true }).click();
  await expect(page.getByTestId('signal-row')).toHaveCount(6);
  await picker('Preview state', 'Empty');
  await expect(page.getByRole('heading', { name: 'No open signals assigned to you' })).toBeVisible();
  await screenshot('empty');
  await page.getByRole('button', { name: 'View my teams' }).click();
  await expect(page.getByTestId('signal-row')).toHaveCount(8);
  await expect(page.locator('.signal-row .owner-cell')).toHaveCount(8);
  await screenshot('team-queue');
  await picker('Preview state', 'Read-only');
  await page.getByTestId('signal-row').first().click();
  await expect(page.getByRole('combobox', { name: 'Assign signal' })).toBeDisabled();
  await page.getByRole('button', { name: 'More signal actions' }).click();
  await expect(page.getByRole('menuitem', { name: 'Mark reviewed', exact: true })).toHaveAttribute('data-disabled', '');
  await page.keyboard.press('Escape');
  await expect(page.locator('[data-slot="dropdown-menu-content"]')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Mark handled', exact: true })).toHaveCount(0);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  console.log('PASS: loading, error with retry, explicit empty navigation, read-only controls');

  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await page.getByRole('button', { name: 'Dark', exact: true }).click();
  await expect(page.locator('html')).toHaveClass('dark');
  await screenshot('dark-queue');
  await page.getByRole('button', { name: 'Light', exact: true }).click();
  await page.getByRole('combobox', { name: 'Assignment', exact: true }).focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('option', { name: 'Mine', exact: true })).toBeFocused();
  await page.keyboard.press('ArrowDown');
  await expect(page.getByRole('option', { name: 'My teams', exact: true })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('combobox', { name: 'Assignment', exact: true })).toContainText('My teams');
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await expect(categories.getByRole('button', { name: /^Retention/ })).toBeInViewport();
  await expect(categories.getByRole('button', { name: /^Needs context/ })).toBeInViewport();
  await screenshot('mobile-queue');
  await chooseCategory('Retention');
  await page.getByTestId('signal-row').first().click();
  await expect(page.getByRole('button', { name: 'Mark handled', exact: true })).toBeInViewport();
  await expect(page.getByRole('button', { name: 'Open conversation', exact: true })).toBeInViewport();
  await expect(page.getByText('Confirm a recovery plan with engineering before replying.')).toBeInViewport();
  await noOverflow();
  await screenshot('mobile-detail');
  await page.keyboard.press('Escape');
  await page.reload();
  await expect(categories.getByRole('button', { name: /^Retention/ })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByTestId('signal-row')).toHaveCount(1);
  expect(errors).toEqual([]);
  console.log('PASS: dark mode, keyboard assignment, mobile categories and action footer, no overflow, URL restoration, zero browser errors');
  console.log(`Screenshots: ${artifacts}`);
} finally {
  await browser.close();
}
