import { ArrowDown, Building2, Check, Link2, MessageSquare } from 'lucide-react';
import { TaskPriorityIcon, TaskSprintIcon } from './task-demo-icons';

export function ProjectIntake({ phase }: { phase: number }) {
  const created = phase === 3;
  return <div className="project-intake" data-phase={phase}>
    <div className="pi-source"><div className="pi-person"><img src="/new/avatars/maya.webp" width={30} height={30} alt="" /><span><strong>Maya Chen</strong><small>Northstar Labs · Customer conversation</small></span><MessageSquare size={15} /></div><p>“Can you alert our team in Slack when a sync fails? We only notice when a customer reports it.”</p><div className="pi-source-link" data-linked={created}><Link2 size={12} /><span>{created ? 'Linked task · ORB-491' : 'Customer request · Slack alerts'}</span>{created && <Check size={12} />}</div></div>
    <div className="pi-handoff"><span /><ArrowDown size={14} /><span className="pi-handoff-label">{['Capture the customer’s need', 'Ask Agent prepares the task', 'Sam approves the plan', 'Task created with its context'][phase]}</span><span /></div>
    <div className="pi-task" data-prepared={phase > 0} data-created={created}><div className="pi-task-top"><span>{created ? 'ORB-491' : 'PROPOSED TASK'}</span><span className="pi-status">{created ? <><Check size={11} />Created</> : phase === 2 ? <><Check size={11} />Approved</> : 'For review'}</span></div><h3>Add Slack alerts for failed syncs</h3><p>Notify the team before a customer has to report a failed sync.</p><div className="pi-properties"><span><small>Team</small><strong>Engineering</strong></span><span><small>Priority</small><strong><TaskPriorityIcon />High</strong></span><span><small>Owner</small><strong><img src="/new/avatars/sam.webp" width={19} height={19} alt="" />Sam Rivera</strong></span><span><small>Sprint</small><strong><TaskSprintIcon />Sprint 24</strong></span></div><div className="pi-requirements"><strong>Requirements from the request</strong><ul><li>Include the affected account and failure reason.</li><li>Link to the sync so the team can investigate.</li><li>Send one alert per failed sync.</li></ul></div><div className="pi-context-links" data-linked={created}><span><MessageSquare size={12} />Maya’s conversation</span><span><Building2 size={12} />Northstar Labs</span><small>{created ? 'Linked to this task' : 'Context to attach'}</small></div></div>
    <div className="pi-confirmation" data-approved={phase >= 2}><img src={phase >= 2 ? '/new/avatars/sam.webp' : '/brand/helpin-icon-white.svg'} width={22} height={22} alt="" /><span>{created ? 'Created after Sam’s approval. Ready for planning.' : phase === 2 ? 'Approved by Sam · Creating the linked task' : 'Ask Agent prepares the details for Sam to review.'}</span><Check size={13} /></div>
  </div>;
}
