[package]
name = "helpin-support-mobile"
version = "0.1.0"
description = "Helpin Support Mobile"
authors = ["Helpin"]
edition = "2021"

[lib]
name = "helpin_support_mobile_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.9.1", features = [] }
tauri-plugin-notification = "2"
tauri-plugin-store = "2.4.0"
