'use client';

import { useState, type CSSProperties, type ReactNode } from 'react';
import { ArrowDown, ArrowUpRight, Building2, CalendarDays, Check, CircleCheck, FileText, Link2, ListChecks, Mail, Pause, Play, Quote, Video } from 'lucide-react';
import { useBentoPlayback } from '../../_components/useBentoPlayback';

type Variant = 'capture' | 'task' | 'followup' | 'context';
function Step({children,at=0,className=''}:{children:ReactNode;at?:number;className?:string}){return <div className={`mt-step ${className}`} style={{'--mt-delay':`${at}s`} as CSSProperties}>{children}</div>;}
function Avatar({person}:{person:'maya'|'sam'}){return <img className="mt-avatar" src={`/new/avatars/${person}.webp`} width={28} height={28} alt=""/>;}
function Capture(){return <><div className="mt-day"><CalendarDays size={15}/><span>Friday, September 18</span><span className="mt-pill">Connected calendar</span></div><div className="mt-calendar"><div className="mt-time">10:00</div><div className="mt-event"><span className="mt-mini">CUSTOMER CALL</span><strong>Northstar Labs · SSO rollout review</strong><span>10:00–10:45 · Google Meet</span><div className="mt-attendees"><Avatar person="maya"/><Avatar person="sam"/><span>Maya, Sam + 1</span></div></div></div><div className="mt-capture-stages"><Step at={.4}><span className="mt-status-icon"><CalendarDays size={16}/></span><div><strong>Meeting selected</strong><small>Capture this occurrence</small></div><Check size={14}/></Step><Step at={1.8}><span className="mt-status-icon"><Video size={16}/></span><div><strong>Helpin notetaker joined</strong><small>Conversation captured after admission</small></div><div className="mt-wave">{[8,16,11,23,14,20,9].map((h,i)=><i key={i} style={{height:h,animationDelay:`${i*.12}s`}}/>)}</div></Step><Step at={3.6}><span className="mt-status-icon"><FileText size={16}/></span><div><strong>Ready to review</strong><small>Transcript, decisions & action items</small></div><CircleCheck size={16}/></Step></div></>;}
function Task(){return <><span className="mt-mini">ACTION ITEM · FROM THE TRANSCRIPT</span><div className="mt-source"><Quote size={16}/><p>“I’ll send the reviewed setup guide and pilot checklist.”</p><div><Avatar person="sam"/><span>Sam Rivera</span><span>28:14</span></div></div><div className="mt-connector"><ArrowDown size={18}/></div><Step at={1} className="mt-task"><div className="mt-task-id"><ListChecks size={16}/><span>SSO Enterprise Readiness</span></div><strong>Share the Okta setup guide and pilot checklist</strong><div className="mt-task-meta"><span><Avatar person="sam"/>Sam Rivera</span><span><i/>To do</span><span>Customer Success</span></div><Step at={2.3} className="mt-linked"><Link2 size={13}/>Northstar Labs · SSO rollout review</Step></Step><Step at={3.4} className="mt-complete"><CircleCheck size={15}/>Task created from the reviewed action item</Step></>;}
function Followup(){return <><div className="mt-mail-heading"><Mail size={18}/><strong>Customer follow-up</strong><span className="mt-pill">Draft</span></div><div className="mt-mail-meta"><span>To</span><span>Maya Chen <span className="mt-muted">· Northstar Labs</span></span><span>Subject</span><strong>Next steps for your SSO pilot</strong></div><div className="mt-email"><p>Hi Maya,</p><p>Thanks for walking us through Northstar’s rollout requirements today.</p><Step at={.8}><div className="mt-email-item"><span>01</span><p>We’ll start with an admin-only pilot.</p></div></Step><Step at={1.7}><div className="mt-email-item"><span>02</span><p>I’ll send the reviewed Okta setup guide and pilot checklist.</p></div></Step><Step at={2.6}><div className="mt-email-item"><span>03</span><p>Please share your security checklist so we can confirm the remaining requirements.</p></div></Step><p>Thanks,<br/>Sam</p></div><Step at={3.5} className="mt-draft-review"><Avatar person="sam"/><div><strong>Ready for Sam’s review</strong><small>Draft prepared · Not sent</small></div><Check size={15}/></Step></>;}
function Context(){return <><div className="mt-customer"><span className="mt-company-mark"><Building2 size={24}/></span><div><span className="mt-mini">CUSTOMER RECORD</span><strong>Northstar Labs</strong><small>Enterprise rollout</small></div></div><div className="mt-context-list">{[
  {Icon:Video,label:'Meeting',title:'SSO rollout review',detail:'Summary, transcript & decisions'},
  {Icon:Mail,label:'Contact',title:'Maya Chen',detail:'Security & rollout requirements'},
  {Icon:Building2,label:'Deal',title:'Enterprise rollout',detail:'Security approval pending'},
  {Icon:ListChecks,label:'Task',title:'Share the setup guide',detail:'Sam Rivera · To do'},
].map(({Icon,label,title,detail},i)=><Step key={label} at={i*.8}><span className="mt-context-icon"><Icon size={16}/></span><div><span className="mt-mini">{label}</span><strong>{title}</strong><small>{detail}</small></div><Link2 size={13}/></Step>)}</div><Step at={3.4} className="mt-context-end"><Link2 size={14}/>One meeting. Connected to the customer and the work.</Step></>;}
const TITLES:Record<Variant,string>={capture:'Meeting capture',task:'Action items',followup:'Follow-up draft',context:'Customer context'};
const DESCRIPTIONS:Record<Variant,string>={capture:'A selected Northstar Labs calendar meeting is captured after the notetaker is admitted. After processing, the transcript, decisions, and action items are ready for review.',task:'Sam’s commitment to share an Okta setup guide is reviewed and created as a Customer Success task, assigned to Sam and linked to the source meeting.',followup:'A draft to Maya summarizes the admin-only pilot, setup guide, and security checklist. The email is ready for Sam’s review and has not been sent.',context:'The Northstar Labs customer record connects the SSO rollout meeting, Maya’s contact, the enterprise rollout deal, and Sam’s follow-up task.'};
export function MeetingScene({variant}:{variant:Variant}){
 const {container,playing,cycle}=useBentoPlayback(10500);
 const [paused,setPaused]=useState(false);
 return <div ref={container} className={`meeting-scene mt-${variant}`} data-playing={playing&&!paused}><div className="mt-toolbar"><span><b className="mt-mark">O</b>OrbitDesk<span className="mt-slash">/</span>{TITLES[variant]}</span><button type="button" aria-label={`${paused?'Play':'Pause'} ${TITLES[variant].toLowerCase()} animation`} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={12}/>:<Pause size={12}/>}</button></div><div className="mt-content" key={cycle} role="img" aria-label={DESCRIPTIONS[variant]}><div aria-hidden="true">{variant==='capture'?<Capture/>:variant==='task'?<Task/>:variant==='followup'?<Followup/>:<Context/>}</div></div></div>;
}
const EVIDENCE=[
 {kind:'Decision',title:'Start with an admin-only pilot.',time:'12:08',person:'maya' as const,name:'Maya Chen',quote:'Let’s start with our admins before we open this up to the rest of the team.',note:'Begin the rollout with a smaller group before wider adoption.'},
 {kind:'Open question',title:'Confirm how groups map to roles.',time:'19:32',person:'maya' as const,name:'Maya Chen',quote:'Can we map our existing Okta groups to the right roles before the pilot?',note:'Group-to-role mapping needs validation before the rollout.'},
 {kind:'Action item',title:'Share the setup guide and checklist.',time:'28:14',person:'sam' as const,name:'Sam Rivera',quote:'I’ll send the reviewed setup guide and pilot checklist.',note:'Sam will share the reviewed materials as the next step.'},
];
export function MeetingEvidence(){
 const [selected,setSelected]=useState(0);
 const item=EVIDENCE[selected];
 return <div className="mt-evidence"><div className="mt-evidence-heading"><span><b className="mt-mark">O</b>Northstar Labs · SSO rollout review</span><span><FileText size={14}/>Meeting intelligence</span></div><div className="mt-evidence-body"><div className="mt-findings"><span className="mt-mini">EXPLORE THE MEETING</span>{EVIDENCE.map((entry,i)=><button key={entry.kind} type="button" aria-pressed={i===selected} aria-controls="meeting-evidence-detail" onClick={()=>setSelected(i)}><span className="mt-finding-type">{entry.kind}</span><strong>{entry.title}</strong><span className="mt-finding-link">See the conversation <ArrowUpRight size={13}/></span></button>)}</div><div id="meeting-evidence-detail" className="mt-transcript"><div className="mt-transcript-top"><span>TRANSCRIPT EVIDENCE</span><span>{item.time}</span></div><div className="mt-transcript-quote" key={item.kind}><div className="mt-speaker"><Avatar person={item.person}/><strong>{item.name}</strong><span>{item.time}</span></div><blockquote>“{item.quote}”</blockquote><div className="mt-extracted"><Check size={15}/><div><span>{item.kind}</span><p>{item.note}</p></div></div></div><div className="mt-transcript-bottom"><Link2 size={14}/>The source stays with the action item.</div></div></div></div>;
}
