'use client';

import '../../_components/product-previews/preview-navigation.css';

import { useId, useRef, useState } from 'react';
import { ArrowLeft, BookOpen, Building2, CalendarDays, Check, ChevronDown, Copy, Flag, LayoutGrid, Link2, Mail, MessageSquare, Mic, Pause, Play, Settings, Users, Video, Zap } from 'lucide-react';
import { MEETING_EVIDENCE, MEETING_SUMMARY, MEETING_TITLE } from './meeting-demo-data';
import { useMeetingPlayback } from './use-meeting-playback';
import './meeting-workspace.css';

// Mirrors MeetingDetail, QuietDetailLayout, ActionItemRow, and the associations
// rail. This is a local demo: no media capture, live task writes, or email sends.
export function MeetingWorkspace({ autoplay = true }: { autoplay?: boolean }) {
  const { container, active, phase, paused, setPaused } = useMeetingPlayback(autoplay);
  const [tab, setTab] = useState<'overview' | 'transcript'>('overview');
  const [selected, setSelected] = useState(0);
  const [manualTask, setManualTask] = useState(false);
  const [copied, setCopied] = useState(false);
  const [announcement, setAnnouncement] = useState('');
  const transcriptRef = useRef<HTMLButtonElement>(null);
  const id = useId();
  const created = manualTask || phase === 3;
  const moment = tab === 'transcript' ? selected : phase >= 1 ? 2 : 0;
  const showEvidence = (index: number) => { setPaused(true); setSelected(index); setTab('transcript'); transcriptRef.current?.focus(); };
  const changeTab = (next: 'overview' | 'transcript') => { setPaused(true); setTab(next); };
  const copy = async () => {
    setPaused(true);
    try { await navigator.clipboard.writeText(MEETING_SUMMARY); setCopied(true); setAnnouncement('Meeting overview copied.'); }
    catch { setAnnouncement('Copy is unavailable. You can select the overview text.'); }
  };
  return <div className="mw-preview" ref={container} data-playing={active} data-phase={phase} role="region" aria-label="OrbitDesk meeting workspace preview">
    <aside className="mw-navigation preview-sidebar" aria-label="Example workspace navigation"><div className="mw-brand"><b>O</b><strong>OrbitDesk</strong><ChevronDown size={12}/></div><div className="mw-nav-body"><div className="mw-rail" aria-hidden="true">{[[LayoutGrid,'Projects'],[MessageSquare,'Support'],[BookOpen,'Docs'],[Building2,'CRM'],[Zap,'Automate'],[Settings,'Settings']].map(([Icon,label])=>{const I=Icon as typeof Video;return <span key={String(label)} data-selected={label==='CRM'}><I size={16}/><small>{String(label)}</small></span>;})}</div><div className="mw-crm-nav">{[[LayoutGrid,'Overview'],[Users,'Contacts'],[Building2,'Companies'],[Flag,'Deals'],[Mail,'Emails'],[CalendarDays,'Meetings'],[BookOpen,'Playbooks'],[Zap,'Signals']].map(([Icon,label])=>{const I=Icon as typeof Video;return <span key={String(label)} data-selected={label==='Meetings'}><I size={13}/>{String(label)}</span>;})}</div></div><div className="mw-user"><img src="/new/avatars/sam.webp" width={25} height={25} alt=""/><span>Sam Rivera<small>sam@orbitdesk.example</small></span></div></aside>
    <div className="mw-work"><header className="mw-heading"><div className="mw-heading-top"><span><ArrowLeft size={12}/>Meetings</span><button type="button" className="mw-pause" aria-label={`${paused?'Play':'Pause'} meeting workspace animation`} aria-pressed={paused} onClick={()=>{setManualTask(false);setPaused(!paused);}}>{paused?<Play size={12}/>:<Pause size={12}/>}</button></div><div className="mw-heading-title"><img src="/new/meetings/google_meet.svg" width={22} height={22} alt="Google Meet"/><h3>{MEETING_TITLE}</h3></div><div className="mw-meta"><span>Google Meet</span><span>Today · 10:00 AM</span><span>42 minutes</span><span>3 participants</span><b>Ready</b></div></header>
      <div className="mw-tabs" role="tablist" aria-label="Meeting detail views">{(['overview','transcript'] as const).map((value,index)=><button type="button" role="tab" key={value} id={`${id}-${value}`} ref={value==='transcript'?transcriptRef:undefined} aria-controls={`${id}-panel`} aria-selected={tab===value} tabIndex={tab===value?0:-1} onClick={()=>changeTab(value)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'overview':e.key==='End'?'transcript':index===0?'transcript':'overview';changeTab(next);document.getElementById(`${id}-${next}`)?.focus();}}}>{value==='overview'?'Overview':<>Transcript <span>132</span></>}</button>)}</div>
      <div className="mw-panel" id={`${id}-panel`} role="tabpanel" aria-labelledby={`${id}-${tab}`}>
        {tab==='overview'?<><div className="mw-summary-bar"><span><i/>Summary from the transcript</span><button type="button" onClick={()=>showEvidence(0)}>View transcript</button><button type="button" onClick={copy}>{copied?<Check size={12}/>:<Copy size={12}/>} {copied?'Copied':'Copy overview'}</button></div><p className="mw-summary">{MEETING_SUMMARY}</p>
          <div className="mw-recording-heading"><span><Video size={13}/>Meeting recording</span><span>42:18</span></div><div className="mw-call" role="img" aria-label="Illustrative three-person meeting preview: Maya Chen, Sam Rivera, and Aisha Patel.">{[['maya','Maya Chen'],['sam','Sam Rivera'],['aisha','Aisha Patel']].map(([person,name],index)=><div key={person} className="mw-call-person" data-speaking={(moment===2?1:0)===index}><img src={`/new/avatars/${person}.webp`} alt=""/><span>{name}<Mic size={10}/></span></div>)}<span className="mw-call-time">{MEETING_EVIDENCE[moment].time}</span></div>
          <button type="button" className="mw-recording-caption" onClick={()=>showEvidence(moment)}><QuoteMark/><span>“{MEETING_EVIDENCE[moment].quote}”</span><Link2 size={12}/></button>
          <div className="mw-section-title"><h4>What happens next</h4><span>2</span><small>Check the commitment. Confirm who owns it.</small></div><div className="mw-actions"><article className="mw-action" data-highlight={phase>=1}><strong>Send the SSO setup guide and pilot checklist</strong><p>Sam Rivera · Due date not set</p><button className="mw-evidence-link" type="button" onClick={()=>showEvidence(2)}>View transcript evidence<ArrowLeft size={10}/></button><div className="mw-destination"><span>Customer Success</span><span>To do</span></div><div className="mw-action-footer"><span className="mw-review-state" data-visible={phase>=2}><Check size={10}/>Team and status set</span><button type="button" aria-disabled={created} onClick={()=>{if(!created){setManualTask(true);setPaused(true);setAnnouncement('Demo task CS-128 created and linked to this meeting.');}}}>{created?<><Check size={12}/>CS-128 linked</>:<>Create task<Link2 size={11}/></>}</button></div></article><article className="mw-action"><strong>Share the remaining security requirements</strong><p>Maya Chen · Customer next step</p><div className="mw-open-question"><span>Still to confirm</span><p>Can Northstar’s existing Okta groups map to the required product roles?</p></div><button className="mw-evidence-link" type="button" onClick={()=>showEvidence(1)}>See the conversation<Link2 size={11}/></button></article></div><div className="mw-decision"><Check size={13}/><span>Agreed on the call: start with an admin-only pilot before a wider rollout.</span><button type="button" onClick={()=>showEvidence(0)}>12:08</button></div></>:
          <div className="mw-transcript-view"><div className="mw-transcript-heading"><span><Mic size={13}/>Speaker-attributed transcript</span><small>Selected excerpts</small></div>{MEETING_EVIDENCE.map((entry,index)=><button type="button" key={entry.kind} className="mw-transcript-row" aria-pressed={selected===index} onClick={()=>setSelected(index)}><img src={`/new/avatars/${entry.person}.webp`} width={28} height={28} alt=""/><span><strong>{entry.name}<small>{entry.time}</small></strong><span>{entry.quote}</span><em>{entry.kind}</em></span></button>)}<div className="mw-transcript-result"><Link2 size={17}/><div><strong>{MEETING_EVIDENCE[selected].title}</strong><p>{MEETING_EVIDENCE[selected].note}</p></div></div><button type="button" className="mw-back-overview" onClick={()=>{changeTab('overview');document.getElementById(`${id}-overview`)?.focus();}}><ArrowLeft size={13}/>Back to overview</button></div>}
      </div>
    </div>
    <aside className="mw-details" aria-label="Meeting details and linked customer records"><div className="mw-detail-title"><Video size={13}/>Capture details</div><dl>{[['Visibility','Workspace'],['Recording','Video'],['Participants','3'],['Platform','Google Meet']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="mw-detail-title">Associations</div><p>Connected to the customer and the work</p>{[['Contact','Maya Chen'],['Company','Northstar Labs'],['Deal','Enterprise rollout'],['Epic','SSO Enterprise Readiness'],['Task',created?'CS-128 · Send the setup guide':'Review suggested action items']].map(([label,value])=><div className="mw-association" key={label} data-linked={label==='Task'&&created}><span>{label}</span><strong>{value}</strong>{label==='Task'&&created&&<small><Link2 size={10}/>Linked to this meeting</small>}</div>)}</aside><span className="mw-sr-only" role="status">{announcement}</span>
  </div>;
}
function QuoteMark(){return <span aria-hidden="true" className="mw-quote-mark">“</span>;}
