import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, CalendarDays, CheckCheck, ChevronRight, FileText, Mic, Settings2 } from 'lucide-react';
import { PreviewNav } from '../../_components/PreviewNav';
import { PreviewFooter } from '../../_components/PreviewFooter';
import { ConnectedWorkspace } from '../../_components/ConnectedWorkspace';
import { CtaRow, SectionHead } from '../../_components/ui';
import { MeetingScene, MeetingEvidence } from './meeting-scenes';
import './meetings.css';

export const metadata: Metadata = {
  title: 'Meetings — Helpin',
  description: 'Capture customer meetings, find the decisions behind the discussion, and turn action items into linked tasks. Keep transcripts, recordings, and follow-up drafts connected to the customer.',
  alternates: { canonical: '/new/products/meetings' },
  robots: { index: false, follow: false },
};
const PLATFORMS = [['google_meet', 'Google Meet'], ['zoom', 'Zoom'], ['teams', 'Microsoft Teams'], ['webex', 'Webex']];
const FAQS = [
  ['Which meeting platforms can Helpin join?', 'Helpin recognizes Google Meet, Zoom, Microsoft Teams, and Webex meeting links. Capture availability depends on your configured meeting provider and the meeting’s access requirements. The notetaker may need to be admitted by the host.'],
  ['Can I choose which calls are captured?', 'Yes. Add a meeting link and start now or schedule it. For connected calendar meetings, choose manual capture, meetings with external attendees, or all eligible meetings. Individual meeting and recurring-series choices can override the workspace default.'],
  ['What do I get after a meeting?', 'A speaker-attributed transcript, summary, decisions, key discussion points, open questions, and suggested action items. Helpin can also prepare a follow-up draft. When recording is enabled and available, you can play it back and use transcript timestamps to revisit the conversation.'],
  ['Can action items become project tasks?', 'Yes. Review an action item and create a task with a destination team, workflow state, and owner. The task stays linked to the meeting. You can dismiss an action item when it does not need a task. Task creation requires the relevant CRM and project permissions.'],
  ['Are follow-up emails sent automatically?', 'Meeting processing prepares a follow-up draft for review; it does not automatically send that draft to the customer. Your team can check the recipient, wording, and next steps before using it.'],
  ['Does the meeting stay connected to the customer?', 'Yes. Meetings can be associated with contacts, companies, deals, and project tasks. Connected calendar capture can also establish customer associations from the event, keeping the discussion alongside the account and related work.'],
  ['Can we control recordings and the notetaker?', 'Yes. Enable or disable meeting notes for the workspace, set the notetaker name, choose the default join behavior, and choose whether recordings are saved. Recording preferences can also be set for an individual meeting.'],
  ['Is Meetings included in the Community beta?', 'The current Community beta focuses on support, docs, and agents. The connected Meetings, CRM, and project workflows shown here depend on the edition and capture services configured for your workspace.'],
];
export default function MeetingsPage() {
  return <><PreviewNav /><div className="meetings-page">
    <section className="meetings-hero" aria-labelledby="meetings-title"><div className="wrap">
      <div className="meetings-breadcrumb"><Link href="/new">Helpin</Link><ChevronRight size={12}/><span>Meetings</span></div>
      <div className="meetings-hero-copy"><span className="eyebrow">Customer meetings, connected to the work</span><h1 id="meetings-title">Turn customer calls into <span>work that moves forward.</span></h1><p className="lede">Capture the conversation. Find the decisions. Turn next steps into tasks and follow-up drafts—with the customer context still attached.</p><CtaRow secondaryHref="#meeting-capture" secondaryLabel="Explore Meetings"/><div className="meetings-platforms">{PLATFORMS.map(([id,label])=><span key={id}><img src={`/new/meetings/${id}.svg`} width={19} height={19} alt=""/>{label}</span>)}</div></div>
      <figure className="meetings-screenshot"><img src="/new/product/workspace-meetings-1920-v3.webp" srcSet="/new/product/workspace-meetings-960-v3.webp 960w, /new/product/workspace-meetings-1920-v3.webp 1920w, /new/product/workspace-meetings-4k-v3.webp 3840w" sizes="(max-width: 1280px) calc(100vw - 48px), 1232px" width={3840} height={2160} fetchPriority="high" alt="OrbitDesk meeting review for Northstar Labs: SSO rollout summary, recording, decisions, assigned action items, and linked customer records."/></figure>
    </div></section>
    <nav className="meetings-page-nav" aria-label="On this page"><div className="wrap"><strong>Meetings</strong><a href="#meeting-capture">Capture the call</a><a href="#meeting-decisions">Find the decisions</a><a href="#meeting-work">Move work forward</a><a href="#meeting-context">Keep the context</a></div></nav>
    <section id="meeting-capture"><div className="wrap"><div className="meetings-split"><div><SectionHead eyebrow="Be in the conversation" title="Give the customer your attention. Keep the details." lede="Let Helpin join the call and capture what was said. Start with a meeting link, or choose which connected calendar meetings your notetaker should attend." secondaryLede="A customer objection, a rollout decision, a promise to follow up—keep the details your team will need after everyone leaves."/></div><MeetingScene variant="capture"/></div><div className="meetings-features">{[
      {Icon:CalendarDays,title:'Choose the calls that matter.',body:'Capture one meeting, set a recurring-series preference, or use workspace defaults for eligible calendar events.'},
      {Icon:Settings2,title:'Make the notetaker yours.',body:'Set its name and join behavior. Choose manual capture, external meetings, or all eligible meetings.'},
      {Icon:Mic,title:'Keep recordings when you need them.',body:'Choose whether to save recordings for playback. Set a default or a preference for an individual meeting.'},
    ].map(({Icon,title,body})=><article key={title}><Icon size={21}/><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section id="meeting-decisions" className="meetings-soft"><div className="wrap"><div className="meetings-centered"><SectionHead eyebrow="More than a transcript" title="Find the decision, then see what was said." lede="Read the summary, review open questions, and check action items against the conversation. Speaker names and timestamps help you return to the moment that matters."/></div><MeetingEvidence/><div className="meetings-detail-row"><span><Mic size={16}/>Speaker-attributed transcripts</span><span><FileText size={16}/>Decisions, risks & open questions</span><span><CheckCheck size={16}/>Action items with evidence</span></div></div></section>
    <section id="meeting-work" className="meetings-dark"><div className="wrap"><div className="meetings-centered"><SectionHead eyebrow="The call ends. The work continues." title="Give every next step somewhere to go." lede="Review the action items, create the tasks, and prepare the follow-up. Move from what was agreed to work your team can own."/></div><div className="meetings-work-grid"><article><div className="meetings-work-copy"><span className="meetings-number">01 / ASSIGN THE WORK</span><h3>Turn a commitment into a task.</h3><p>Choose the team, owner, and workflow state. The task stays linked to the meeting that started it.</p></div><MeetingScene variant="task"/></article><article><div className="meetings-work-copy"><span className="meetings-number">02 / PREPARE THE FOLLOW-UP</span><h3>Leave the customer with a clear next step.</h3><p>Start from a draft grounded in the discussion. Review the wording and commitments before following up.</p></div><MeetingScene variant="followup"/></article></div><Link className="meetings-inline-link" href="/new/products/projects">See how Projects keeps work moving<ArrowRight size={16}/></Link></div></section>
    <section id="meeting-context"><div className="wrap meetings-split"><div><SectionHead eyebrow="Part of the customer’s history" title="Keep the call connected to everything that follows." lede="Attach the meeting to the contact, company, deal, and tasks it belongs to. See the conversation behind a renewal, a product request, or a rollout blocker." secondaryLede="Your team and agents can carry that context into the next piece of work, without starting the story again."/><Link className="meetings-inline-link" href="/new/products/ai-agents">Explore your agents<ArrowRight size={16}/></Link></div><MeetingScene variant="context"/></div></section>
    <section id="meeting-faq" className="meetings-soft"><div className="wrap meetings-faq-grid"><SectionHead eyebrow="A few useful answers" title="Make room for better conversations."/><div className="meetings-faqs">{FAQS.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
    <section className="final-cta final-cta-connected" aria-labelledby="meetings-final-title"><div className="wrap"><ConnectedWorkspace/><div className="final"><span className="eyebrow">Keep the conversation moving</span><h2 id="meetings-final-title">Make the next customer call count.</h2><p className="lede">Bring the conversation, the decisions, and the work that follows into one workspace.</p><CtaRow/></div></div></section>
  </div><PreviewFooter/></>;
}
