// Code generated by scripts/generate-commercial-event-catalog.go; DO NOT EDIT.
pub const SERVER_ONLY_EVENT_NAMES: &[&str] = &[
    "commercial_state_updated",
    "downgrade_requested",
    "payment_failed",
    "subscription_canceled",
    "subscription_changed",
    "subscription_renewed",
    "workflow_failed",
];
pub const SERVER_ONLY_COMPANY_FIELDS: &[&str] = &["commercial_state"];
pub fn is_server_only_event(name: &str) -> bool {
    SERVER_ONLY_EVENT_NAMES.binary_search(&name).is_ok()
}
pub fn has_server_only_company_field(
    company: &std::collections::HashMap<String, serde_json::Value>,
) -> bool {
    SERVER_ONLY_COMPANY_FIELDS.iter().any(|field| {
        company.contains_key(*field)
            || company
                .get("custom")
                .and_then(serde_json::Value::as_object)
                .is_some_and(|custom| custom.contains_key(*field))
    })
}

#[cfg(test)]
mod tests {
    use serde::Deserialize;

    #[derive(Deserialize)]
    struct SourceCatalog {
        server_only_event_names: Vec<String>,
        server_only_company_fields: Vec<String>,
    }

    #[test]
    fn generated_catalog_matches_shared_source() {
        let source: SourceCatalog = serde_json::from_str(include_str!(
            "../../../server/internal/eventcatalog/commercial_events.json"
        ))
        .expect("shared commercial event catalog must parse");
        assert_eq!(
            source.server_only_event_names,
            super::SERVER_ONLY_EVENT_NAMES
        );
        assert_eq!(
            source.server_only_company_fields,
            super::SERVER_ONLY_COMPANY_FIELDS
        );
    }
}
