package automationcatalog

import "github.com/helpin-ai/helpin/server/internal/model"

var entries = []model.AutomationCatalogEntry{
	builtIn(
		"crm.buyer_signal_ingestion",
		"crm",
		"CRM system intelligence",
		"Buyer signal ingestion",
		"Extracts buyer signals from stored CRM email and keeps CRM intelligence current in the background.",
		[]string{"crm_email_message"},
		[]string{"internal_domain_hook"},
		"system",
		"background_workflow",
		false,
		"automation-default",
		"CRM Settings > Email Accounts",
		"/w/$slug/settings/crm-email",
		"Background only",
		nil,
		"CRM contacts, deals, signals, and insights",
		"Settings > AI & Automations",
	),
	builtIn(
		"crm.contact_summary_refresh",
		"crm",
		"CRM system intelligence",
		"Contact summary refresh",
		"Generates durable contact summaries from recent CRM email activity and buyer signals.",
		[]string{"crm_contact"},
		[]string{"internal_domain_hook", "cron"},
		"system",
		"background_workflow",
		false,
		"automation-default",
		"CRM Settings > Email Accounts",
		"/w/$slug/settings/crm-email",
		"Background only",
		nil,
		"CRM contact detail pages",
		"Settings > AI & Automations",
	),
	builtIn(
		"crm.deal_summary_refresh",
		"crm",
		"CRM system intelligence",
		"Deal summary refresh",
		"Generates durable deal summaries from recent CRM email activity and buyer signals.",
		[]string{"crm_deal"},
		[]string{"internal_domain_hook", "cron"},
		"system",
		"background_workflow",
		false,
		"automation-default",
		"CRM Settings > Email Accounts",
		"/w/$slug/settings/crm-email",
		"Background only",
		nil,
		"CRM deal detail pages",
		"Settings > AI & Automations",
	),
	builtIn(
		"pm.epic_auto_start",
		"pm",
		"PM built-in rules",
		"Epic auto-start",
		"Starts an epic automatically when one of its stories enters a started workflow state.",
		[]string{"pm_epic"},
		[]string{"internal_domain_hook"},
		"workspace",
		"deterministic_rule",
		true,
		"inline",
		"Project Settings > Automations",
		"/w/$slug/settings/automations",
		"Story state change",
		nil,
		"PM epics and activity feed",
		"Settings > AI & Automations",
	),
	builtIn(
		"pm.epic_auto_complete",
		"pm",
		"PM built-in rules",
		"Epic auto-complete",
		"Completes an epic automatically when all of its stories are done.",
		[]string{"pm_epic"},
		[]string{"internal_domain_hook"},
		"workspace",
		"deterministic_rule",
		true,
		"inline",
		"Project Settings > Automations",
		"/w/$slug/settings/automations",
		"Story state change",
		nil,
		"PM epics and activity feed",
		"Settings > AI & Automations",
	),
	builtIn(
		"pm.sprint_auto_create",
		"pm",
		"PM built-in rules",
		"Sprint auto-create",
		"Keeps a buffer of future sprints available for each configured team.",
		[]string{"pm_sprint"},
		[]string{"cron"},
		"team",
		"scheduled_rule",
		true,
		"inline",
		"Project Settings > Automations",
		"/w/$slug/settings/automations",
		"Hourly PM automation sweep",
		nil,
		"PM sprint lists and planning views",
		"Settings > AI & Automations",
	),
	builtIn(
		"pm.sprint_move_unfinished",
		"pm",
		"PM built-in rules",
		"Move unfinished stories",
		"Moves unfinished sprint work into the next sprint for configured teams.",
		[]string{"pm_sprint", "pm_story"},
		[]string{"cron"},
		"team",
		"scheduled_rule",
		true,
		"inline",
		"Project Settings > Automations",
		"/w/$slug/settings/automations",
		"Hourly PM automation sweep",
		nil,
		"PM sprints and stories",
		"Settings > AI & Automations",
	),
	contextual(
		"pm.product_planner",
		"pm",
		"PM & Support agents",
		"Product planner",
		"Explicit planning agent used from PM context to create or refine PRDs, stories, and plans.",
		[]string{"pm_story", "pm_epic"},
		[]string{"manual", "assignment_event"},
		"agent-planner",
		"/w/$slug/pm/agents",
		"PM story and epic views",
	),
	contextual(
		"pm.engineer",
		"pm",
		"PM & Support agents",
		"Engineer",
		"Explicit implementation agent used from PM context to work on stories and delivery tasks.",
		[]string{"pm_story"},
		[]string{"manual", "assignment_event"},
		"agent-engineer",
		"/w/$slug/pm/agents",
		"PM story views",
	),
	contextual(
		"pm.reviewer",
		"pm",
		"PM & Support agents",
		"Reviewer",
		"Explicit QA and review agent used from PM context to validate implementation output.",
		[]string{"pm_story"},
		[]string{"manual", "assignment_event"},
		"agent-reviewer",
		"/w/$slug/pm/agents",
		"PM story views",
	),
	contextual(
		"support.support_agent",
		"support",
		"PM & Support agents",
		"Support agent",
		"Explicit support agent used in support conversations for drafting and resolution support.",
		[]string{"support_conversation"},
		[]string{"manual", "assignment_event"},
		"agent-support",
		"/w/$slug/pm/agents",
		"Support conversation views",
	),
	{
		ID:                  "custom.automation_placeholder",
		Kind:                model.AutomationKindCustom,
		Module:              "shared",
		Group:               "Custom automations",
		Title:               "Custom automations",
		Description:         "Reserved for future user-created manual, assignment-event, and scheduled automations.",
		TargetTypes:         []string{},
		TriggerModes:        []string{"manual", "assignment_event", "cron"},
		ConfigScope:         "future",
		ExecutionStyle:      "future",
		UserGoverned:        true,
		UserCreatable:       true,
		Queue:               "",
		CurrentWriteSurface: "Coming later",
		CurrentRunSurface:   "Coming later",
		OutputSurface:       "Defined per automation",
		DiagnosticsSurface:  "Settings > AI & Automations",
	},
}

func builtIn(
	id, module, group, title, description string,
	targetTypes, triggerModes []string,
	configScope, executionStyle string,
	userGoverned bool,
	queue, writeSurface, writePath, runSurface string,
	runPath *string,
	outputSurface, diagnosticsSurface string,
) model.AutomationCatalogEntry {
	entry := model.AutomationCatalogEntry{
		ID:                  id,
		Kind:                model.AutomationKindBuiltIn,
		Module:              module,
		Group:               group,
		Title:               title,
		Description:         description,
		TargetTypes:         targetTypes,
		TriggerModes:        triggerModes,
		ConfigScope:         configScope,
		ExecutionStyle:      executionStyle,
		UserGoverned:        userGoverned,
		UserCreatable:       false,
		Queue:               queue,
		CurrentWriteSurface: writeSurface,
		CurrentRunSurface:   runSurface,
		CurrentRunPath:      runPath,
		OutputSurface:       outputSurface,
		DiagnosticsSurface:  diagnosticsSurface,
	}
	if writePath != "" {
		entry.CurrentWritePath = &writePath
	}
	return entry
}

func contextual(
	id, module, group, title, description string,
	targetTypes, triggerModes []string,
	queue, writePath, outputSurface string,
) model.AutomationCatalogEntry {
	writeSurface := "PM Agents"
	runSurface := "Contextual assignment and manual runs"
	runPath := writePath
	return model.AutomationCatalogEntry{
		ID:                  id,
		Kind:                model.AutomationKindContextual,
		Module:              module,
		Group:               group,
		Title:               title,
		Description:         description,
		TargetTypes:         targetTypes,
		TriggerModes:        triggerModes,
		ConfigScope:         "workspace",
		ExecutionStyle:      "interactive_agent",
		UserGoverned:        true,
		UserCreatable:       false,
		Queue:               queue,
		CurrentWriteSurface: writeSurface,
		CurrentWritePath:    &writePath,
		CurrentRunSurface:   runSurface,
		CurrentRunPath:      &runPath,
		OutputSurface:       outputSurface,
		DiagnosticsSurface:  "Settings > AI & Automations",
	}
}

// All returns the canonical code-defined automation catalog.
func All() []model.AutomationCatalogEntry {
	cloned := make([]model.AutomationCatalogEntry, len(entries))
	copy(cloned, entries)
	return cloned
}

// ByID returns one catalog entry by canonical ID.
func ByID(id string) (model.AutomationCatalogEntry, bool) {
	for _, entry := range entries {
		if entry.ID == id {
			return entry, true
		}
	}
	return model.AutomationCatalogEntry{}, false
}
