package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/helpin-ai/helpin/server/internal/aiusage"
)

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string, output io.Writer) error {
	catalog, err := aiusage.LoadCatalog()
	if err != nil {
		return err
	}
	switch {
	case len(args) == 1 && args[0] == "validate":
		if _, err := fmt.Fprintf(output, "pricing %s valid\n", catalog.PricingVersion); err != nil {
			return fmt.Errorf("write validation result: %w", err)
		}
		return nil
	case len(args) == 3 && args[0] == "export" && args[1] == "--format" && args[2] == "typescript":
		return exportTypeScript(output, catalog)
	case len(args) == 5 && args[0] == "export" && args[1] == "--format" && args[2] == "typescript" && args[3] == "--output":
		file, err := os.Create(args[4])
		if err != nil {
			return fmt.Errorf("create pricing export: %w", err)
		}
		defer file.Close()
		return exportTypeScript(file, catalog)
	default:
		return fmt.Errorf("usage: ai-pricing validate | export --format typescript [--output path]")
	}
}

func exportTypeScript(output io.Writer, catalog *aiusage.Catalog) error {
	snapshot := catalog.PublicSnapshot()
	encoded, err := json.MarshalIndent(snapshot, "", "  ")
	if err != nil {
		return fmt.Errorf("encode public AI pricing: %w", err)
	}
	digest := sha256.Sum256(encoded)
	_, err = fmt.Fprintf(output, "// Code generated by cmd/ai-pricing; DO NOT EDIT.\nexport const catalogSha256 = %q;\nexport const AI_PRICING = %s as const;\n", hex.EncodeToString(digest[:]), encoded)
	if err != nil {
		return fmt.Errorf("write TypeScript pricing: %w", err)
	}
	return nil
}
