import { createHash } from 'node:crypto'
import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import * as hugeicons from '@hugeicons/core-free-icons'

const ASSET_FORMAT_VERSION = 1
const ALLOWED_SVG_TAGS = new Set(['circle', 'ellipse', 'path', 'rect'])
const ALLOWED_SVG_ATTRIBUTES = new Set([
  'cx', 'cy', 'd', 'fill', 'fillRule', 'height', 'key', 'opacity', 'r', 'rx', 'ry',
  'stroke', 'strokeLinecap', 'strokeLinejoin', 'strokeWidth', 'transform', 'width', 'x', 'y',
])
const scriptDir = dirname(fileURLToPath(import.meta.url))
const helpCenterDir = resolve(scriptDir, '..')
const aliasPath = resolve(helpCenterDir, 'icon-aliases.json')
const packagePath = resolve(
  helpCenterDir,
  'node_modules/@hugeicons/core-free-icons/package.json',
)
const licensePath = resolve(
  helpCenterDir,
  'icon-license.txt',
)

function pascalToKebab(value) {
  return value.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
}

function pascalToLabel(value) {
  return value
    .replace(/(\d+)/g, ' $1 ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/Icon$/, '')
    .trim()
}

function escapeXML(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
}

function svgAttributeName(name) {
  return {
    fillRule: 'fill-rule',
    strokeLinecap: 'stroke-linecap',
    strokeLinejoin: 'stroke-linejoin',
    strokeWidth: 'stroke-width',
  }[name] ?? name
}

function renderSVG(icon) {
  const children = icon.map(([tag, rawAttributes]) => {
    if (!ALLOWED_SVG_TAGS.has(tag) || !rawAttributes || typeof rawAttributes !== 'object') {
      throw new Error(`unsafe generated SVG element: ${String(tag)}`)
    }
    for (const [name, value] of Object.entries(rawAttributes)) {
      if (!ALLOWED_SVG_ATTRIBUTES.has(name) || (typeof value !== 'string' && typeof value !== 'number')) {
        throw new Error(`unsafe generated SVG attribute: ${name}`)
      }
    }
    const attributes = { ...rawAttributes }
    delete attributes.key
    if (attributes.stroke !== undefined) {
      attributes.stroke = 'currentColor'
      attributes.strokeWidth = '1.5'
    }
    const encoded = Object.entries(attributes)
      .map(([name, value]) => `${svgAttributeName(name)}="${escapeXML(value)}"`)
      .join(' ')
    return `<${tag}${encoded ? ` ${encoded}` : ''}/>`
  })
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">${children.join('')}</svg>\n`
}

function sortedPairs(values) {
  return Object.entries(values).sort(([left], [right]) => left.localeCompare(right))
}

function goString(value) {
  return JSON.stringify(value)
}

function renderGoCatalog(catalog) {
  const renderAliasEntries = (values) => sortedPairs(values)
    .map(([source, target]) => `\t{Source: ${goString(source)}, Target: ${goString(target)}},`)
    .join('\n')
  const entries = catalog.icons
    .map(({ id, label }) => `\t{ID: ${goString(id)}, Label: ${goString(label)}},`)
    .join('\n')
  return `// Code generated by help-center/scripts/generate-icons.mjs; DO NOT EDIT.\n\npackage iconcatalog\n\nconst (\n\t_catalogVersion = ${goString(catalog.version)}\n\t_catalogHash    = ${goString(catalog.hash)}\n)\n\nvar _entries = [...]entry{\n${entries}\n}\n\nvar _aliases = [...]aliasEntry{\n${renderAliasEntries(catalog.aliases)}\n}\n\nvar _normalizedAliases = [...]aliasEntry{\n${renderAliasEntries(catalog.normalized_aliases)}\n}\n\nvar _tokenAliases = [...]aliasEntry{\n${renderAliasEntries(catalog.token_aliases)}\n}\n`
}

function renderFrontendAliases(catalog) {
  const render = (value) => JSON.stringify(value, null, 2)
  return `// Code generated by help-center/scripts/generate-icons.mjs; DO NOT EDIT.\n\nexport const ICON_ALIASES: Readonly<Record<string, string>> = ${render(catalog.aliases)}\n\nexport const NORMALIZED_ICON_ALIASES: Readonly<Record<string, string>> = ${render(catalog.normalized_aliases)}\n\nexport const TOKEN_ICON_ALIASES: Readonly<Record<string, string>> = ${render(catalog.token_aliases)}\n`
}

async function fileExists(path) {
  try {
    await stat(path)
    return true
  } catch {
    return false
  }
}

async function writeAssets(catalog, iconDataByID, license, root) {
  const versionRoot = resolve(root, 'hugeicons', catalog.version)
  const markerPath = resolve(root, '.catalog-hash')
  if (await fileExists(markerPath)) {
    const marker = (await readFile(markerPath, 'utf8')).trim()
    if (marker === catalog.hash &&
        await fileExists(resolve(versionRoot, 'rocket01.svg')) &&
        await fileExists(resolve(root, 'catalog.json'))) {
      return
    }
  }

  await rm(root, { recursive: true, force: true })
  await mkdir(versionRoot, { recursive: true })
  const batchSize = 100
  for (let index = 0; index < catalog.icons.length; index += batchSize) {
    const batch = catalog.icons.slice(index, index + batchSize)
    await Promise.all(batch.map(({ id }) =>
      writeFile(resolve(versionRoot, `${id}.svg`), renderSVG(iconDataByID.get(id))),
    ))
  }
  await writeFile(resolve(root, 'LICENSE.txt'), license)
  await writeFile(resolve(root, 'catalog.json'), `${JSON.stringify({
    version: catalog.version,
    hash: catalog.hash,
    icons: catalog.icons,
  })}\n`)
  await writeFile(markerPath, `${catalog.hash}\n`)
}

async function main() {
  const args = new Set(process.argv.slice(2))
  const packageJSON = JSON.parse(await readFile(packagePath, 'utf8'))
  const aliases = JSON.parse(await readFile(aliasPath, 'utf8'))
  const iconDataByID = new Map()
  const icons = []

  for (const [exportName, data] of Object.entries(hugeicons)) {
    if (!exportName.endsWith('Icon') || !Array.isArray(data)) continue
    const id = pascalToKebab(exportName.replace(/Icon$/, ''))
    if (iconDataByID.has(id)) {
      throw new Error(`duplicate generated icon id: ${id}`)
    }
    iconDataByID.set(id, data)
    icons.push({ id, label: pascalToLabel(exportName) })
  }
  icons.sort((left, right) => left.id.localeCompare(right.id))
  const validIDs = new Set(icons.map(({ id }) => id))
  for (const group of ['aliases', 'normalized_aliases', 'token_aliases']) {
    for (const [source, target] of sortedPairs(aliases[group])) {
      if (!validIDs.has(target)) {
        throw new Error(`${group} target for ${source} is not a generated icon: ${target}`)
      }
    }
  }
  const hashInput = JSON.stringify({
    asset_format_version: ASSET_FORMAT_VERSION,
    version: packageJSON.version,
    icons,
    ...aliases,
  })
  const catalog = {
    version: packageJSON.version,
    hash: createHash('sha256').update(hashInput).digest('hex'),
    icons,
    ...aliases,
  }

  const assetsOutputArg = process.argv.find((arg) => arg.startsWith('--assets-output='))
  if (args.has('--assets') || assetsOutputArg) {
    const assetsRoot = assetsOutputArg
      ? resolve(helpCenterDir, assetsOutputArg.slice('--assets-output='.length))
      : resolve(helpCenterDir, 'public/assets/helpin-icons')
    await writeAssets(catalog, iconDataByID, await readFile(licensePath, 'utf8'), assetsRoot)
  }

  const serverOutputArg = process.argv.find((arg) => arg.startsWith('--server-output='))
  const checkServerArg = process.argv.find((arg) => arg.startsWith('--check-server='))
  const frontendAliasOutputArg = process.argv.find((arg) => arg.startsWith('--frontend-alias-output='))
  const checkFrontendAliasArg = process.argv.find((arg) => arg.startsWith('--check-frontend-alias='))
  if (serverOutputArg) {
    const outputPath = resolve(helpCenterDir, serverOutputArg.slice('--server-output='.length))
    await mkdir(dirname(outputPath), { recursive: true })
    await writeFile(outputPath, renderGoCatalog(catalog))
  }
  if (checkServerArg) {
    const outputPath = resolve(helpCenterDir, checkServerArg.slice('--check-server='.length))
    const expected = renderGoCatalog(catalog)
    const actual = await readFile(outputPath, 'utf8')
    if (actual !== expected) {
      throw new Error(`generated server icon catalog is stale: ${outputPath}`)
    }
  }
  if (frontendAliasOutputArg) {
    const outputPath = resolve(helpCenterDir, frontendAliasOutputArg.slice('--frontend-alias-output='.length))
    await mkdir(dirname(outputPath), { recursive: true })
    await writeFile(outputPath, renderFrontendAliases(catalog))
  }
  if (checkFrontendAliasArg) {
    const outputPath = resolve(helpCenterDir, checkFrontendAliasArg.slice('--check-frontend-alias='.length))
    const expected = renderFrontendAliases(catalog)
    const actual = await readFile(outputPath, 'utf8')
    if (actual !== expected) {
      throw new Error(`generated frontend icon aliases are stale: ${outputPath}`)
    }
  }
}

await main()
