-- First-class support inbox global search.
-- Search vectors are generated by Postgres, so normal conversation/message writes
-- refresh synchronously without application hooks or async index drift.

ALTER TABLE support_conversations
  ADD COLUMN IF NOT EXISTS search_vector tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('simple', coalesce(subject, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(customer_email, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(customer_name, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(display_id::text, '')), 'A')
  ) STORED;

ALTER TABLE support_messages
  ADD COLUMN IF NOT EXISTS search_vector tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('simple', coalesce(content, '')), 'C')
  ) STORED;

CREATE INDEX IF NOT EXISTS idx_support_conversations_search_vector
  ON support_conversations USING GIN (search_vector);

CREATE INDEX IF NOT EXISTS idx_support_messages_search_vector
  ON support_messages USING GIN (search_vector);

CREATE INDEX IF NOT EXISTS idx_support_messages_search_conversation
  ON support_messages (workspace_id, conversation_id)
  WHERE deleted_at IS NULL
    AND message_type = 'reply'
    AND system_event_type IS NULL;

CREATE INDEX IF NOT EXISTS idx_support_conversations_workspace_display
  ON support_conversations (workspace_id, display_id);

CREATE INDEX IF NOT EXISTS idx_support_conversations_workspace_customer_email
  ON support_conversations (workspace_id, lower(customer_email));
