export const COMPANIES = [
  {
    name: "Northstar Labs",
    logo: "northstar-labs",
    domain: "northstar.example",
    industry: "Software",
    employees: "85",
    revenue: "$8.4m",
    owner: "Sam Rivera",
    initials: "NL",
  },
  {
    name: "Harbor Metrics",
    logo: "harbor-metrics",
    domain: "harbormetrics.example",
    industry: "Analytics",
    employees: "42",
    revenue: "$3.1m",
    owner: "Aisha Patel",
    initials: "HM",
  },
  {
    name: "Forma",
    logo: "forma",
    domain: "forma.example",
    industry: "Software",
    employees: "120",
    revenue: "$12m",
    owner: "Sam Rivera",
    initials: "F",
  },
  {
    name: "Latticepoint",
    logo: "latticepoint",
    domain: "latticepoint.example",
    industry: "Developer tools",
    employees: "64",
    revenue: "$5.2m",
    owner: "Aisha Patel",
    initials: "LP",
  },
  {
    name: "Fieldnote",
    logo: "fieldnote",
    domain: "fieldnote.example",
    industry: "Software",
    employees: "28",
    revenue: "$1.8m",
    owner: "Sam Rivera",
    initials: "FN",
  },
  {
    name: "Cedar Cloud",
    logo: "cedar-cloud",
    domain: "cedarcloud.example",
    industry: "Infrastructure",
    employees: "96",
    revenue: "$9.6m",
    owner: "Aisha Patel",
    initials: "CC",
  },
  {
    name: "Metriclane",
    logo: "metriclane",
    domain: "metriclane.example",
    industry: "Analytics",
    employees: "36",
    revenue: "$2.4m",
    owner: "Sam Rivera",
    initials: "ML",
  },
  {
    name: "Relaynote",
    logo: "relaynote",
    domain: "relaynote.example",
    industry: "Software",
    employees: "57",
    revenue: "$4.6m",
    owner: "Aisha Patel",
    initials: "RN",
  },
  {
    name: "Waypoint Labs",
    logo: "waypoint-labs",
    domain: "waypoint.example",
    industry: "Developer tools",
    employees: "74",
    revenue: "$6.2m",
    owner: "Sam Rivera",
    initials: "WL",
  },
  {
    name: "Tracewell",
    logo: "tracewell",
    domain: "tracewell.example",
    industry: "Infrastructure",
    employees: "112",
    revenue: "$11.3m",
    owner: "Aisha Patel",
    initials: "TW",
  },
  {
    name: "Branchlight",
    logo: "branchlight",
    domain: "branchlight.example",
    industry: "Developer tools",
    employees: "48",
    revenue: "$3.8m",
    owner: "Sam Rivera",
    initials: "BL",
  },
  {
    name: "Everpath",
    logo: "everpath",
    domain: "everpath.example",
    industry: "Customer success",
    employees: "135",
    revenue: "$14.2m",
    owner: "Aisha Patel",
    initials: "EP",
  },
  {
    name: "Layerline",
    logo: "layerline",
    domain: "layerline.example",
    industry: "Infrastructure",
    employees: "72",
    revenue: "$7.1m",
    owner: "Sam Rivera",
    initials: "LL",
  },
  {
    name: "Signalnest",
    logo: "signalnest",
    domain: "signalnest.example",
    industry: "Analytics",
    employees: "31",
    revenue: "$2.7m",
    owner: "Aisha Patel",
    initials: "SN",
  },
  {
    name: "Arcwell",
    logo: "arcwell",
    domain: "arcwell.example",
    industry: "Security",
    employees: "156",
    revenue: "$18.5m",
    owner: "Sam Rivera",
    initials: "AW",
  },
  {
    name: "Mergefield",
    logo: "mergefield",
    domain: "mergefield.example",
    industry: "Developer tools",
    employees: "61",
    revenue: "$5.4m",
    owner: "Aisha Patel",
    initials: "MF",
  },
  {
    name: "Pineworks",
    logo: "pineworks",
    domain: "pineworks.example",
    industry: "Software",
    employees: "44",
    revenue: "$3.6m",
    owner: "Sam Rivera",
    initials: "PW",
  },
  {
    name: "Flowspan",
    logo: "flowspan",
    domain: "flowspan.example",
    industry: "Automation",
    employees: "93",
    revenue: "$9.2m",
    owner: "Aisha Patel",
    initials: "FS",
  },
];
export const CONTACTS = [
  {
    name: "Maya Chen",
    email: "maya@northstar.example",
    role: "Head of Operations",
    company: 0,
    stage: "Customer",
    status: "In Progress",
    owner: "Sam Rivera",
    avatar: "maya",
    initials: "MC",
  },
  {
    name: "Daniel Park",
    email: "daniel@harbormetrics.example",
    role: "Co-founder",
    company: 1,
    stage: "Sales Qualified",
    status: "Open",
    owner: "Aisha Patel",
    initials: "DP",
  },
  {
    name: "Nina Brooks",
    email: "nina@forma.example",
    role: "VP Customer Success",
    company: 2,
    stage: "Customer",
    status: "In Progress",
    owner: "Sam Rivera",
    initials: "NB",
  },
  {
    name: "Leo Martin",
    email: "leo@latticepoint.example",
    role: "Engineering Lead",
    company: 3,
    stage: "Opportunity",
    status: "Open",
    owner: "Aisha Patel",
    initials: "LM",
  },
  {
    name: "Priya Shah",
    email: "priya@fieldnote.example",
    role: "Founder",
    company: 4,
    stage: "Lead",
    status: "New",
    owner: "Sam Rivera",
    initials: "PS",
  },
  {
    name: "Owen Reed",
    email: "owen@cedarcloud.example",
    role: "Customer Experience",
    company: 5,
    stage: "Sales Qualified",
    status: "Open",
    owner: "Aisha Patel",
    initials: "OR",
  },
  {
    name: "Elena Costa",
    email: "elena@metriclane.example",
    role: "Product Lead",
    company: 6,
    stage: "Customer",
    status: "In Progress",
    owner: "Sam Rivera",
    initials: "EC",
  },
  {
    name: "Jonah Ellis",
    email: "jonah@relaynote.example",
    role: "Founder",
    company: 7,
    stage: "Opportunity",
    status: "Open",
    owner: "Aisha Patel",
    initials: "JE",
  },
  {
    name: "Sofia Bennett",
    email: "sofia@waypoint.example",
    role: "Engineering Manager",
    company: 8,
    stage: "Lead",
    status: "New",
    owner: "Sam Rivera",
    initials: "SB",
  },
  {
    name: "Marcus Lee",
    email: "marcus@tracewell.example",
    role: "Head of Support",
    company: 9,
    stage: "Sales Qualified",
    status: "Open",
    owner: "Aisha Patel",
    initials: "ML",
  },
  {
    name: "Ada Morgan",
    email: "ada@branchlight.example",
    role: "VP Engineering",
    company: 10,
    stage: "Customer",
    status: "In Progress",
    owner: "Sam Rivera",
    initials: "AM",
  },
  {
    name: "Kai Nakamura",
    email: "kai@everpath.example",
    role: "Head of Customer Success",
    company: 11,
    stage: "Opportunity",
    status: "Open",
    owner: "Aisha Patel",
    initials: "KN",
  },
  {
    name: "Amara Okafor",
    email: "amara@layerline.example",
    role: "Platform Lead",
    company: 12,
    stage: "Sales Qualified",
    status: "In Progress",
    owner: "Sam Rivera",
    initials: "AO",
  },
  {
    name: "Ben Walker",
    email: "ben@signalnest.example",
    role: "Co-founder",
    company: 13,
    stage: "Lead",
    status: "New",
    owner: "Aisha Patel",
    initials: "BW",
  },
  {
    name: "Leila Haddad",
    email: "leila@arcwell.example",
    role: "Head of Operations",
    company: 14,
    stage: "Customer",
    status: "Open",
    owner: "Sam Rivera",
    initials: "LH",
  },
  {
    name: "Ethan Kim",
    email: "ethan@mergefield.example",
    role: "Product Manager",
    company: 15,
    stage: "Opportunity",
    status: "In Progress",
    owner: "Aisha Patel",
    initials: "EK",
  },
  {
    name: "Isabel Torres",
    email: "isabel@pineworks.example",
    role: "Customer Experience Lead",
    company: 16,
    stage: "Lead",
    status: "Open",
    owner: "Sam Rivera",
    initials: "IT",
  },
  {
    name: "Noah Clarke",
    email: "noah@flowspan.example",
    role: "Solutions Engineer",
    company: 17,
    stage: "Sales Qualified",
    status: "New",
    owner: "Aisha Patel",
    initials: "NC",
  },
];
export const ACCOUNT_SUMMARY =
  "Maya leads operations at Northstar Labs. The $42,000 renewal is in review, and reliable CSV exports are a requirement for the wider rollout. EXP-142 is with engineering for review. Sam owns the customer follow-up.";
export const ACCOUNT_BRIEF =
  "Start with the export issue. Maya needs complete CSV exports before the wider rollout and renewal discussion.\n\nEXP-142 is in review. Confirm the fix with engineering, then prepare an update for Maya. Sam owns the next step; the $42,000 renewal is still open.";
