export const COMPANIES = [
  {
    name: "Northstar Labs",
    domain: "northstar.example",
    industry: "Software",
    employees: "85",
    revenue: "$8.4m",
    owner: "Sam Rivera",
    initials: "NL",
  },
  {
    name: "Harbor Metrics",
    domain: "harbormetrics.example",
    industry: "Analytics",
    employees: "42",
    revenue: "$3.1m",
    owner: "Aisha Patel",
    initials: "HM",
  },
  {
    name: "Forma",
    domain: "forma.example",
    industry: "Software",
    employees: "120",
    revenue: "$12m",
    owner: "Sam Rivera",
    initials: "F",
  },
  {
    name: "Latticepoint",
    domain: "latticepoint.example",
    industry: "Developer tools",
    employees: "64",
    revenue: "$5.2m",
    owner: "Aisha Patel",
    initials: "LP",
  },
  {
    name: "Fieldnote",
    domain: "fieldnote.example",
    industry: "Software",
    employees: "28",
    revenue: "$1.8m",
    owner: "Sam Rivera",
    initials: "FN",
  },
  {
    name: "Cedar Cloud",
    domain: "cedarcloud.example",
    industry: "Infrastructure",
    employees: "96",
    revenue: "$9.6m",
    owner: "Aisha Patel",
    initials: "CC",
  },
  {
    name: "Metriclane",
    domain: "metriclane.example",
    industry: "Analytics",
    employees: "36",
    revenue: "$2.4m",
    owner: "Sam Rivera",
    initials: "ML",
  },
  {
    name: "Relaynote",
    domain: "relaynote.example",
    industry: "Software",
    employees: "57",
    revenue: "$4.6m",
    owner: "Aisha Patel",
    initials: "RN",
  },
  {
    name: "Waypoint Labs",
    domain: "waypoint.example",
    industry: "Developer tools",
    employees: "74",
    revenue: "$6.2m",
    owner: "Sam Rivera",
    initials: "WL",
  },
  {
    name: "Tracewell",
    domain: "tracewell.example",
    industry: "Infrastructure",
    employees: "112",
    revenue: "$11.3m",
    owner: "Aisha Patel",
    initials: "TW",
  },
];
export const CONTACTS = [
  {
    name: "Maya Chen",
    email: "maya@northstar.example",
    role: "Head of Operations",
    company: 0,
    stage: "Customer",
    status: "In Progress",
    owner: "Sam Rivera",
    avatar: "maya",
    initials: "MC",
  },
  {
    name: "Daniel Park",
    email: "daniel@harbormetrics.example",
    role: "Co-founder",
    company: 1,
    stage: "Sales Qualified",
    status: "Open",
    owner: "Aisha Patel",
    initials: "DP",
  },
  {
    name: "Nina Brooks",
    email: "nina@forma.example",
    role: "VP Customer Success",
    company: 2,
    stage: "Customer",
    status: "In Progress",
    owner: "Sam Rivera",
    initials: "NB",
  },
  {
    name: "Leo Martin",
    email: "leo@latticepoint.example",
    role: "Engineering Lead",
    company: 3,
    stage: "Opportunity",
    status: "Open",
    owner: "Aisha Patel",
    initials: "LM",
  },
  {
    name: "Priya Shah",
    email: "priya@fieldnote.example",
    role: "Founder",
    company: 4,
    stage: "Lead",
    status: "New",
    owner: "Sam Rivera",
    initials: "PS",
  },
  {
    name: "Owen Reed",
    email: "owen@cedarcloud.example",
    role: "Customer Experience",
    company: 5,
    stage: "Sales Qualified",
    status: "Open",
    owner: "Aisha Patel",
    initials: "OR",
  },
  {
    name: "Elena Costa",
    email: "elena@metriclane.example",
    role: "Product Lead",
    company: 6,
    stage: "Customer",
    status: "In Progress",
    owner: "Sam Rivera",
    initials: "EC",
  },
  {
    name: "Jonah Ellis",
    email: "jonah@relaynote.example",
    role: "Founder",
    company: 7,
    stage: "Opportunity",
    status: "Open",
    owner: "Aisha Patel",
    initials: "JE",
  },
  {
    name: "Sofia Bennett",
    email: "sofia@waypoint.example",
    role: "Engineering Manager",
    company: 8,
    stage: "Lead",
    status: "New",
    owner: "Sam Rivera",
    initials: "SB",
  },
  {
    name: "Marcus Lee",
    email: "marcus@tracewell.example",
    role: "Head of Support",
    company: 9,
    stage: "Sales Qualified",
    status: "Open",
    owner: "Aisha Patel",
    initials: "ML",
  },
];
export const ACCOUNT_SUMMARY =
  "Maya leads operations at Northstar Labs. The $42,000 renewal is in review, and reliable CSV exports are a requirement for the wider rollout. EXP-142 is with engineering for review. Sam owns the customer follow-up.";
export const ACCOUNT_BRIEF =
  "Start with the export issue. Maya needs complete CSV exports before the wider rollout and renewal discussion.\n\nEXP-142 is in review. Confirm the fix with engineering, then prepare an update for Maya. Sam owns the next step; the $42,000 renewal is still open.";
