package dbschema

import (
	"github.com/helpin-ai/helpin/server/internal/authorization"
	"github.com/helpin-ai/helpin/server/internal/model"
)

// AutoMigrationModels is the shared API startup model list. Community schema
// parity CI uses this exact list; model changes require a ledger migration.
// Models owned exclusively by versioned SQL must not be added here.
func AutoMigrationModels() []any {
	return []any{
		&model.User{},
		&model.UserPasskey{},
		&model.PasswordResetToken{},
		&model.EmailVerificationToken{},
		&model.OAuthMobileHandoff{},
		&model.CLIConnection{}, &model.CLIToken{}, &model.CLIExecution{}, &model.CLIGeneration{},
		&model.Organization{},
		&model.OrganizationMember{},
		&model.Workspace{},
		&model.WorkspaceMember{},
		&model.WorkspaceModuleGrant{},
		&model.WorkspaceSettings{},
		&model.SetupGoal{},
		&model.SetupIntent{},
		&model.SetupAchievement{},
		&model.SetupActionIntent{},
		&model.MemberSetupPreference{},
		&model.WorkspaceTeam{},
		&model.TeamWorkspaceMembership{},
		&model.WorkspaceManager{},
		&model.JobRoleCriteria{},
		&model.PMWorkflow{},
		&model.PMWorkflowState{},
		&model.PMEpicWorkflowState{},
		&model.PMLabel{},
		&model.PMEpic{},
		&model.PMEpicObjective{},
		&model.PMEpicLabel{},
		&model.PMSprint{},
		&model.PMSprintLabel{},
		&model.PMTask{},
		&model.PMTaskOwner{},
		&model.PMTaskFollower{},
		&model.PMTaskLabel{},
		&model.PMComment{},
		&model.PMCommentReaction{},
		&model.PMActivityLog{},
		&model.PMTaskUpdateRead{},
		&model.PMTaskStandingBrief{},
		&model.PMTaskBriefSuggestionDismissal{},
		&model.PMAttachment{},
		&model.PMObjective{},
		&model.PMKeyResult{},
		&model.PMObjectiveTeam{},
		&model.PMObjectiveOwner{},
		&model.PMObjectiveLabel{},
		&model.PMChecklistItem{},
		&model.PMExternalLink{},
		&model.PMView{},
		&model.SupportInboxView{},
		&model.PMAutomation{},
		&model.AutomationRule{},
		&model.WorkspaceInvitation{},
		&model.InvitationTeamPreassignment{},
		&model.PMTeamEstimateSettings{},
		&model.PMTeamFieldVisibility{},
		&model.Agent{},
		&model.AgentTeamAccess{},
		&model.AgentTemplate{},
		&model.WorkspaceAgentPresetVersion{},
		&model.AgentVersion{},
		&model.WorkspaceSkill{},
		&model.AgentRun{},
		&model.AgentTriggerExecution{},
		&model.AgentRunMessage{},
		&model.AgentRunArtifact{},
		&model.AgentRunInteraction{},
		&model.DockActionProposal{},
		// Public MCP tables are intentionally excluded. Their constraints,
		// partial indexes, and retention fields are owned exclusively by
		// versioned migration 202607100003_public_mcp.sql. Letting GORM
		// reconcile those tables can attempt incompatible constraint changes.
		&model.CommandBarPlanRecord{},
		&model.CommandBarPlanDismissal{},
		&model.DockChat{},
		&model.DockChatHandoff{},
		&model.PublicShare{},
		&model.SupportRunEvidence{},
		&model.HelpcenterAnswer{},
		&model.CodingSessionStateSnapshot{},
		&model.PMTaskLink{},
		&model.SupportConversation{},
		&model.SupportConversationTriage{},
		&model.SupportConversationTriageEvent{},
		&model.SupportMailbox{},
		&model.SupportMailboxMembership{},
		&model.SupportTriageRule{},
		&model.SupportEmailRoute{},
		&model.SupportEmailSender{},
		&model.SupportEmailSenderMailbox{},
		&model.SupportEmailSenderDomain{},
		&model.SupportMessage{},
		&model.SupportTranslation{},
		&model.SupportTranslationPreference{},
		&model.SupportTranslationConversation{},
		&model.SupportEmailLog{},
		&model.SupportEmailWebhookEvent{},
		&model.SupportTag{},
		&model.SupportConversationTag{},
		&model.SupportTeammateStatusOverride{},
		&model.SupportCannedResponse{},
		&model.SupportWidgetInstallation{},
		// WorkspaceEventProjectAlias is owned by versioned migration
		// 202608240001, including its overlapping single-column and
		// composite uniqueness constraints. GORM cannot safely reconcile
		// those PostgreSQL constraints as indexes during AutoMigrate.
		&model.CRMIdentityLink{},
		&model.SupportCredentialRotationAudit{},
		&model.SupportWidgetSession{},
		&model.SupportAttachment{},
		&model.CRMEmailAttachment{},
		&model.SupportEvent{},
		&model.SupportCoverageTopic{},
		&model.SupportCoverageGap{},
		&model.SupportGapEvidence{},
		&model.SupportGapSuggestion{},
		&model.SupportCoverageGapArticle{},
		&model.SupportCoverageSnapshot{},
		&model.SupportCoverageDigestDelivery{},
		&model.SupportCoverageAnalysisRun{},
		&model.SupportCoverageConversationAnalysis{},
		&model.AIActionExecution{},
		&model.CoverageBatch{},
		&model.CoverageAnalysisAttempt{},
		&model.CoverageFinding{},
		&model.CoverageTopicV2{},
		&model.CoverageAssignmentAttempt{},
		&model.CoverageTopicMembership{},
		&model.CoverageUnreviewedSignal{},
		&model.CoverageRebuildAudit{},
		&model.SupportAIRetrievalTrace{},
		&model.SupportCoverageRecommendation{},
		&model.SupportCoverageClusterRebuildRun{},
		&model.SupportCoverageGapMergeSuggestion{},
		&model.SupportCoverageGapPairDecision{},
		&model.GitIntegration{},
		&model.GitCredential{},
		&model.GitRepository{},
		&model.PMTeamRepoDefault{},
		&model.TaskDeliveryTarget{},
		&model.EpicDeliveryTarget{},
		&model.TaskGitLink{},
		&model.GitWebhookEvent{},
		&model.AgentHandoff{},
		&model.PMTaskTemplate{},
		&model.PMRecurringTemplate{},
		&model.PMRecurringRun{},
		&model.PMImportJob{},
		&authorization.AuthorizationRelation{},
		// Docs module
		&model.DocsSpace{},
		&model.DocsSpaceTeam{},
		&model.DocsCollection{},
		&model.DocsDocument{},
		&model.DocsDocumentKey{},
		&model.DocsContent{},
		&model.DocsBlock{},
		&model.DocsAISectionCandidate{},
		&model.DocsChangeProposal{},
		&model.DocsVersion{},
		&model.DocsLink{},
		&model.DocsHelpcenterConfig{},
		&model.DocsHelpcenterArticle{},
		&model.DocsHelpcenterArticlePublication{},
		&model.DocsHelpcenterSearchEntry{},
		&model.DocsHelpcenterSpaceTranslation{},
		&model.DocsHelpcenterCollectionTranslation{},
		&model.DocsHelpcenterArticleTranslation{},
		&model.DocsSlugAlias{},
		&model.DocsRedirect{},
		&model.DocsReviewQueue{},
		&model.DocsArticleFeedback{},
		&model.DocsComment{},
		&model.DocsImportJob{},
		&model.DocsAPIReference{},
		&model.DocsAPIReferenceRevision{},
		// Notifications module
		&model.Notification{},
		&model.NotificationEvent{},
		&model.NotificationDelivery{},
		&model.NotificationPreference{},
		&model.UserNotificationSettings{},
		&model.EntityFollower{},
		&model.PushDevice{},
		// CRM module
		&model.CRMContact{},
		&model.CRMCompany{},
		&model.CRMPipeline{},
		&model.CRMPipelineStage{},
		&model.CRMDeal{},
		&model.CRMAssociation{},
		&model.CRMActivity{},
		&model.CRMImportJob{},
		&model.CRMMeeting{},
		&model.CRMMeetingCapture{},
		&model.CRMMeetingTranscript{},
		&model.CRMMeetingIntelligence{},
		&model.CRMMeetingActionItem{},
		&model.CRMMeetingSettings{},
		&model.CRMMeetingProviderEvent{},
		// CRM Phase 3: Email & Calendar
		&model.CRMEmailAccount{},
		&model.CRMMailboxSendingPolicy{}, &model.CRMEmailSendReservation{}, &model.CRMEmailTemplate{}, &model.CRMEmailSequence{}, &model.CRMSequenceEnrollment{}, &model.CRMSequenceDelivery{}, &model.CRMEmailSuppression{},
		&model.CRMEmailThread{},
		&model.CRMEmailMessage{},
		&model.CRMEmailMessageContact{},
		&model.CRMCalendarEvent{},
		&model.CRMCalendarSeriesPreference{},
		// CRM Phase 4: Intelligence
		&model.CRMEnrichmentResult{},
		&model.CRMSignal{},
		&model.CRMSignalObservation{},
		&model.CRMSignalInterpretationConfig{},
		&model.CRMSignalMotionState{},
		&model.CRMSignalRuleConfig{},
		&model.CRMSignalEvaluationRun{},
		&model.CRMSignalEvaluatorWatermark{},
		&model.CRMSignalScoringConfig{},
		&model.CRMSignalFeedback{},
		&model.CRMSignalRoutingPolicy{},
		&model.CRMSignalRoutingSettings{},
		&model.CRMSignalRolloutSettings{},
		&model.CRMCompanyCommercialState{},
		&model.CRMCompanyCommercialStateHistory{},
		&model.CRMCompanyCommercialStateHealth{},
		&model.CRMSignalConditionState{},
		&model.CRMUsageWeekdayBaseline{},
		&model.CRMSignalBatchSuppression{},
		&model.CRMSignalDelivery{},
		&model.CRMSignalExternalEvidence{},
		&model.CRMEntitySummary{},
		&model.CRMDealHealthScore{},
		&model.CRMSuggestion{},
		// Signals, Playbooks, history and scheduled events are versioned-SQL-owned;
		// AutoMigrate must not pre-create these models without their constraints.
		// CRM Phase 5: Writing
		&model.CRMWritingProfile{},
		// CRM Autonomy
		&model.CRMAutonomySettings{},
		// CRM Email Sync Settings
		&model.CRMEmailSyncSettings{},
		&model.AutomationHealthSnapshot{},
		// AI Support Agent
		&model.AgentKnowledgeSource{},
		&model.AgentContentSource{},
		&model.AIMessageProcessing{},
		&model.DocsChunk{},
		&model.SupportContentSource{},
		&model.SupportContentPage{},
		&model.SupportContentChunk{},
		&model.CuratedGuidance{},
	}
}
