'use client';

import { useState, type CSSProperties, type ReactNode } from 'react';
import { ArrowDown, BookOpen, Check, FileText, Globe, LockKeyhole, Pause, Play } from 'lucide-react';
import { useBentoPlayback } from '../../_components/useBentoPlayback';

const ARTICLES = [
  { title: 'Connect your first integration', collection: 'Getting started', body: 'Bring your tools into OrbitDesk and keep the activity in one workspace.', steps: ['Open Settings → Integrations.', 'Choose the service you want to connect.', 'Authorize access and confirm your workspace.'] },
  { title: 'Invite your team', collection: 'Workspace & team', body: 'Give teammates access to the workspace and choose their role.', steps: ['Open your workspace members settings.', 'Add your teammate’s email address.', 'Choose a role and send the invitation.'] },
  { title: 'Export your customer list', collection: 'Working with data', body: 'Create a CSV of the customer records in your current view.', steps: ['Open Customers and apply your filters.', 'Choose Export from the view menu.', 'Download the CSV when your export is ready.'] },
];
export function KnowledgeLibrary() {
  const [selected, setSelected] = useState(0);
  const article = ARTICLES[selected];
  return <div className="kl-library"><div className="kl-top"><span><b className="ks-mark">O</b><strong>OrbitDesk</strong><span>/</span>Help Center</span><span className="kl-public"><Globe size={13} />Public space</span></div><div className="kl-body"><nav aria-label="Example help center articles"><span className="kl-caption">YOUR GUIDES</span>{ARTICLES.map((item,index)=><button key={item.title} type="button" aria-pressed={selected===index} aria-controls="knowledge-example-article" onClick={()=>setSelected(index)}><BookOpen size={15}/><span>{item.title}<small>{item.collection}</small></span></button>)}<div className="kl-internal"><LockKeyhole size={14}/><span>Internal playbooks<small>In a separate team space</small></span></div></nav><article id="knowledge-example-article" aria-live="polite" aria-atomic="true"><div className="kl-article-meta"><span>{article.collection}</span><span><Check size={12}/>Published</span></div><h3>{article.title}</h3><p>{article.body}</p><ol>{article.steps.map(step=><li key={step}>{step}</li>)}</ol><div className="kl-author"><img src="/new/avatars/sam.webp" width={24} height={24} alt=""/><span>Written by Sam Rivera</span></div></article></div></div>;
}
function Step({children,at=0,className=''}:{children:ReactNode;at?:number;className?:string}) {return <div className={`ks-step ${className}`} style={{'--ks-delay':`${at}s`} as CSSProperties}>{children}</div>;}
function Sources(){return <><span className="ks-caption">SELECTED KNOWLEDGE</span><div className="ks-source-list">{[
  {Icon:BookOpen,title:'OrbitDesk Help Center',detail:'Getting started · Selected collection'},
  {Icon:Globe,title:'OrbitDesk product website',detail:'Website source'},
  {Icon:FileText,title:'Integration reference.pdf',detail:'Uploaded file'},
].map(({Icon,title,detail},index)=><Step key={title} at={index*.8}><span className="ks-source-icon"><Icon size={19}/></span><div><strong>{title}</strong><small>{detail}</small></div><span className="ks-ready"><Check size={12}/>Ready</span></Step>)}</div><div className="ks-connector"><ArrowDown size={19}/></div><Step at={2.7} className="ks-available"><img src="/new/agents/echo.svg" width={35} height={35} alt=""/><div><strong>Available to Echo</strong><span>Support answers from selected sources</span></div><Check size={16}/></Step><p className="ks-note"><LockKeyhole size={12}/>Internal playbooks aren’t selected here.</p></>;}
function Quill(){return <><div className="ks-quill-heading"><img src="/new/agents/quill.svg" width={43} height={43} alt=""/><div><strong>Quill</strong><span>Review the integration setup guide</span></div><span className="ks-badge">Docs agent</span></div><div className="ks-evidence"><span className="ks-caption">WORKING FROM</span><span><BookOpen size={13}/>Existing guide</span><span><FileText size={13}/>Updated setup flow</span></div><div className="ks-review-steps"><Step at={.5}><Check size={13}/><span>Read the current setup instructions</span></Step><Step at={1.4}><Check size={13}/><span>Compare the guide with the linked change</span></Step><Step at={2.3}><Check size={13}/><span>Prepare a focused update</span></Step></div><Step at={3.1} className="ks-proposal"><div><FileText size={14}/><strong>Connect your first integration</strong><span>Proposed update</span></div><p>Add the workspace confirmation step after authorization.</p><div className="ks-added"><span>+</span>Confirm the workspace before starting your first sync.</div></Step><Step at={4} className="ks-review"><img src="/new/avatars/sam.webp" width={26} height={26} alt=""/><div><strong>Ready for Sam’s review</strong><span>Changes prepared · Not published</span></div><Check size={15}/></Step></>;}
export function KnowledgeScene({variant}:{variant:'sources'|'quill'}) {
  const {container,playing,cycle}=useBentoPlayback(10000);
  const [paused,setPaused]=useState(false);
  const description=variant==='sources'?'Selected OrbitDesk public docs, a website, and an uploaded file are indexed and available to Echo. Internal playbooks are not selected.':'Quill reads an integration guide and linked product change, then proposes a missing workspace confirmation step. Sam reviews the proposed update before publication.';
  return <div className={`knowledge-scene ks-${variant}`} ref={container} data-playing={playing&&!paused}><div className="ks-toolbar"><span><b className="ks-mark">O</b>OrbitDesk<span>/</span>{variant==='sources'?'Knowledge sources':'Documentation'}</span><button type="button" aria-label={`${paused?'Play':'Pause'} ${variant==='sources'?'knowledge sources':'Quill review'} animation`} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={12} aria-hidden="true"/>:<Pause size={12} aria-hidden="true"/>}</button></div><div className="ks-content" key={cycle} role="img" aria-label={description}><div aria-hidden="true">{variant==='sources'?<Sources/>:<Quill/>}</div></div></div>;
}
