import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, BookOpen, ChevronRight, Code2, FolderOpen, History, Languages, Link2, ShieldCheck, Search, Server, Network, Braces } from 'lucide-react';
import { PreviewNav } from '../../_components/PreviewNav';
import { PreviewFooter } from '../../_components/PreviewFooter';
import { ConnectedWorkspace } from '../../_components/ConnectedWorkspace';
import { CtaRow, SectionHead } from '../../_components/ui';
import { SupportKnowledge } from '../customer-support/support-knowledge';
import { KnowledgeScene } from './knowledge-scenes';
import './knowledge-publishing.css';
import { PublishingDemoV2 } from './publishing-demo-v2';
import './knowledge.css';
import { KnowledgeWorkspace, KnowledgeReader, KnowledgeAPI } from './knowledge-previews';

export const metadata: Metadata = {
  title: 'Knowledge — Helpin',
  description: 'Publish a branded, server-rendered help center on your domain or behind a reverse proxy. Bring together API references, AI answers, internal docs, and agents that help keep knowledge current.',
  alternates: { canonical: '/new/products/knowledge' },
  robots: { index: false, follow: false },
};
const FEATURES = [
  { Icon: FolderOpen, title: 'Make the next step easy to find.', body: 'Organize guides into nested collections, with article navigation and a table of contents for longer answers.' },
  { Icon: Search, title: 'Answer the question behind the search.', body: 'Let readers find a guide or ask in their own words. Enable AI answers with article citations, so customers can follow the answer back to its source.' },
  { Icon: Languages, title: 'Publish for every audience.', body: 'Manage translated articles and collections, with language selection and separate review and publishing states.' },
];
const AUTHORING = [
  { Icon: Code2, title: 'Check the source behind the claim.', body: 'Give Quill the relevant repository and product context. It can inspect the implementation and tests behind a feature before proposing what the docs should say.' },
  { Icon: BookOpen, title: 'Improve the guide you already have.', body: 'Find the article that needs a correction, add a missing step, or draft a guide for something new. Keep the answer in the right place.' },
  { Icon: History, title: 'Review the change with its reasons.', body: 'See the proposed edits and the evidence behind them. Keep draft changes separate from the live article, with document history to follow what changed.' },
];
const FAQS = [
  ['Can we serve docs from our own website?', 'Yes. Publish on a Helpin subdomain, configure a custom domain, or use reverse-proxy mode to serve docs under a path such as yourdomain.com/docs. Helpin includes setup guidance for Cloudflare Workers, AWS CloudFront, and Vercel, and uses the configured public URL for canonical links and sitemaps.'],
  ['Are help-center pages server rendered?', 'Yes. Public help-center pages are rendered on the server, so article HTML is available in the initial response. The delivery layer supports HTML caching, an optional shared Redis cache, and response compression. Actual loading speed depends on hosting, content, network conditions, and cache state.'],
  ['What is included for search engines?', 'The public help center generates canonical URLs, sitemaps, robots.txt, structured page metadata, and social previews. Multilingual pages include language-alternate links. Redirects help preserve paths when content moves.'],
  ['Can developers try our API from the docs?', 'Yes. Import an OpenAPI specification from a URL or file to create an interactive reference with operation details, parameters, schemas, authentication, and cURL, JavaScript, and Python examples. The request panel can send requests to your configured API, subject to its authentication and browser CORS settings.'],
  ['Does the help center include AI answers?', 'Yes. When enabled, readers can explicitly ask a question from help-center search and get an answer with article citations. When the documentation does not confidently answer a question, Helpin points readers to the closest articles instead.'],
  ['Can we keep internal documentation too?', 'Yes. Internal spaces can be visible across the workspace or restricted to selected teams. Public publishing and agent knowledge sources are separate settings; an internal document is not automatically a customer-facing answer.'],
  ['What knowledge can agents use?', 'Select supported public Helpin docs at the space, collection, or article level. You can also add website sources and supported files, including PDF, Markdown, text, and CSV. Review source status and reindex sources when needed.'],
  ['How does Helpin find missing knowledge?', 'Support coverage gaps connect unanswered or weakly answered questions to conversation evidence. Your team can investigate a gap and prepare a new article or an update to an existing one. New suggested articles remain drafts until published.'],
  ['What does Quill do?', 'Quill is the documentation agent. It can investigate support gaps, audit existing docs, and prepare changes using the relevant workspace evidence and tools available to it. Where repository context is connected, it can check implementation details before proposing product documentation.'],
  ['Can we review an AI-written article before it goes live?', 'Yes. Review drafts and proposed changes before publishing. Agent tool access and approval settings determine which actions an agent can take.'],
  ['Can we self-host Knowledge?', 'Yes. Docs is part of the open-source Community beta, alongside support and agents. Connected project, CRM, and repository workflows depend on the edition and tools available in your workspace.'],
];
export default function KnowledgePage() {
  return <><PreviewNav /><main className="knowledge-page">
    <section className="knowledge-hero" aria-labelledby="knowledge-title"><div className="wrap">
      <div className="knowledge-breadcrumb"><Link href="/new">Helpin</Link><ChevronRight size={12} /><span>Knowledge</span></div>
      <div className="knowledge-hero-copy"><span className="eyebrow">Documentation for customers, developers & agents</span><h1 id="knowledge-title">Give customers and agents <span>docs they can rely on.</span></h1><p className="lede">Publish guides and API references on your own domain. Help customers find answers, give agents knowledge to work from, and let Quill prepare updates as your product changes.</p><CtaRow secondaryHref="#knowledge-library" secondaryLabel="Explore Knowledge" /><div className="knowledge-hero-points"><span><Server size={14} />Server rendered</span><span><Network size={14} />Reverse-proxy ready</span><span><Code2 size={14} />OpenAPI reference</span><span><Link2 size={14} />Connected to your workspace</span></div></div>
      <div className="knowledge-screenshot"><KnowledgeWorkspace /></div>
    </div></section>
    <nav className="knowledge-page-nav" aria-label="On this page"><div className="wrap"><strong>Knowledge</strong><a href="#knowledge-library">Reader experience</a><a href="#knowledge-publishing">Publishing & performance</a><a href="#knowledge-api">Developer docs</a><a href="#knowledge-sources">Agent knowledge</a><a href="#knowledge-quill">Keep docs current</a></div></nav>
    <section id="knowledge-library"><div className="wrap"><SectionHead eyebrow="The experience your customers see" title="Make your docs feel like part of your product." lede="Give readers a clear path from their first question to the next step. Put searchable guides, source-backed AI answers, and your brand into one help center." /><div className="knowledge-reader-image"><KnowledgeReader /></div><div className="knowledge-features">{FEATURES.map(({Icon,title,body})=><article key={title}><Icon size={20} aria-hidden="true" /><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section id="knowledge-publishing" className="knowledge-publishing-section"><div className="wrap"><SectionHead eyebrow="Built to be part of your website" title="Your docs belong on your domain." lede="Use a Helpin address, connect your own domain, or serve docs under /docs through a reverse proxy. Keep the address, branding, and reading experience yours." /><PublishingDemoV2 /><div className="knowledge-delivery-details"><article><span className="knowledge-detail-icon"><Server size={21}/></span><div><h3>Deliver the article, ready to read.</h3><p>Server-side rendering puts article content in the first HTML response. Caching and compression keep the delivery efficient as readers move through your docs.</p><div className="knowledge-tech-points"><span>Server-rendered HTML</span><span>HTML caching</span><span>Response compression</span></div></div></article><article><span className="knowledge-detail-icon"><Search size={21}/></span><div><h3>Give search engines a clear path.</h3><p>Canonical URLs, sitemaps, structured metadata, and language-alternate links help search engines understand your docs—even when they live behind your proxy.</p><div className="knowledge-tech-points"><span>Canonical URLs</span><span>Sitemaps & redirects</span><span>Social previews</span></div></div></article></div><p className="knowledge-proxy-platforms">Reverse-proxy setup guidance for <span>Cloudflare Workers</span><span>AWS CloudFront</span><span>Vercel</span></p></div></section>
    <section id="knowledge-api"><div className="wrap"><SectionHead eyebrow="For the people building with your product" title="Give developers a reference they can work with." lede="Turn an OpenAPI specification into an interactive reference beside your guides. Let developers explore endpoints, switch code examples, and try requests against your API without leaving the docs." /><div className="knowledge-reader-image knowledge-api-image"><KnowledgeAPI /></div><div className="knowledge-api-points"><span><Braces size={15}/>cURL, JavaScript & Python</span><span><Code2 size={15}/>Import from a URL or file</span><span><ShieldCheck size={15}/>Authentication-aware request playground</span></div></div></section>
    <section id="knowledge-sources" className="knowledge-sources-section"><div className="wrap knowledge-split"><SectionHead eyebrow="The knowledge behind the answer" title="Put your published knowledge to work." lede="Give agents the same guides your customers read. Connect public Helpin docs, website pages, and files, then choose which sources each agent can use." secondaryLede="Select a whole docs space, a collection, or individual articles. Check source status and refresh the index when the content changes." /><KnowledgeScene variant="sources" /></div></section>
    <section id="knowledge-gaps" className="knowledge-gaps-section"><div className="wrap knowledge-split"><div><SectionHead eyebrow="Let support show you what to write" title="See where your docs leave customers stuck." lede="Repeated questions. Incomplete answers. A guide that no longer matches the product. Helpin connects knowledge gaps to the conversations behind them, so your team knows what needs attention." secondaryLede="Turn that evidence into a new article or a focused update. Review the draft before it becomes the next customer’s answer." /><Link className="knowledge-inline-link" href="/new/products/customer-support">See how support connects<ArrowRight size={15} /></Link></div><SupportKnowledge /></div></section>
    <section id="knowledge-quill" className="knowledge-quill-section"><div className="wrap"><div className="knowledge-split"><div><span className="knowledge-agent-label"><img src="/new/agents/quill.svg" width={32} height={32} alt="" />Meet Quill, your documentation agent</span><SectionHead eyebrow="From shipped changes to useful docs" title="Let Quill turn product changes into doc updates." lede="A setup step changed. An endpoint behaves differently. A new feature needs a guide. Ask Quill to check the source, find the affected docs, and prepare the update." secondaryLede="Give it the relevant docs, customer evidence, and repository access. Review what changed and why before you publish." /><Link className="knowledge-inline-link" href="/new/products/ai-agents">Meet the agents<ArrowRight size={15} /></Link></div><KnowledgeScene variant="quill" /></div><div className="knowledge-features knowledge-authoring">{AUTHORING.map(({Icon,title,body})=><article key={title}><Icon size={20} aria-hidden="true"/><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section id="knowledge-faq"><div className="wrap knowledge-faq-grid"><SectionHead eyebrow="Questions & answers" title="What to know before you publish." /><div className="knowledge-faqs">{FAQS.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
    <section className="final-cta final-cta-connected" aria-labelledby="knowledge-final-title"><div className="wrap"><ConnectedWorkspace /><div className="final"><span className="eyebrow">Make the next answer better</span><h2 id="knowledge-final-title">Make your next release easier to understand.</h2><p className="lede">Publish the guide, answer the question, and keep the knowledge connected to what your team ships.</p><CtaRow /></div></div></section>
  </main><PreviewFooter /></>;
}
