import type { Icon as PhosphorIcon } from '@phosphor-icons/react'
import {
  Rocket, RocketLaunch,
  BookOpen, Book, Books,
  Gear, GearSix,
  PuzzlePiece,
  Code, CodeBlock,
  ChatCircle, ChatDots, ChatText,
  Question,
  ChartBar, ChartLine, ChartPie,
  Shield, ShieldCheck,
  CreditCard,
  Users, UserCircle, User,
  Lightning,
  FileText, File, Files,
  Globe, GlobeSimple,
  Envelope, EnvelopeSimple,
  Key,
  Database,
  Terminal, TerminalWindow,
  Package,
  GitBranch, GitFork,
  Stack,
  Compass,
  Lightbulb, LightbulbFilament,
  BookmarkSimple, Bookmark,
  Folder, FolderOpen,
  Palette, PaintBrush,
  Bell, BellRinging,
  Star,
  Wrench,
  Cloud, CloudArrowUp,
  Lock, LockKey,
  Link, LinkSimple,
  Heart,
  Flag,
  Tag,
  MagnifyingGlass,
  House,
  ArrowRight, ArrowSquareOut,
  CheckCircle,
  Warning, WarningCircle,
  Info,
  PencilSimple,
  Eye,
  Download, UploadSimple,
  ShareNetwork,
  Copy,
  Clock, Timer,
  Calendar,
  MapPin,
  Phone,
  Image,
  VideoCamera,
  Headphones,
  Cpu,
  HardDrive,
  Monitor,
  DeviceMobile,
  Bug,
  Robot,
  Brain,
  Sparkle,
  Trophy,
  Gift,
  Handshake,
  TreeStructure,
  Kanban,
  ListChecks,
  ClipboardText,
  Newspaper,
  Megaphone,
  Target, Crosshair,
  Gauge,
  Plugs,
  Cube,
  Lifebuoy,
  Broadcast,
  Translate,
  CurrencyDollar,
  Storefront,
  Truck,
  Airplane,
  Notebook,
  Scroll,
  Chats,
  SealCheck,
  Play,
  Sliders,
  FunnelSimple,
} from '@phosphor-icons/react'

// Curated map of ~100 commonly used icons for the public help center.
// Keys are kebab-case strings matching the admin icon picker's output.
// The PhIcon component falls back to rendering the string as emoji/text
// if the name is not found here.
export const ICON_MAP: Record<string, PhosphorIcon> = {
  'rocket': Rocket,
  'rocket-launch': RocketLaunch,
  'book-open': BookOpen,
  'book': Book,
  'books': Books,
  'gear': Gear,
  'gear-six': GearSix,
  'puzzle-piece': PuzzlePiece,
  'code': Code,
  'code-block': CodeBlock,
  'chat-circle': ChatCircle,
  'chat-dots': ChatDots,
  'chat-text': ChatText,
  'question': Question,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'credit-card': CreditCard,
  'users': Users,
  'user-circle': UserCircle,
  'user': User,
  'lightning': Lightning,
  'file-text': FileText,
  'file': File,
  'files': Files,
  'globe': Globe,
  'globe-simple': GlobeSimple,
  'envelope': Envelope,
  'envelope-simple': EnvelopeSimple,
  'key': Key,
  'database': Database,
  'terminal': Terminal,
  'terminal-window': TerminalWindow,
  'package': Package,
  'git-branch': GitBranch,
  'git-fork': GitFork,
  'stack': Stack,
  'compass': Compass,
  'lightbulb': Lightbulb,
  'lightbulb-filament': LightbulbFilament,
  'bookmark-simple': BookmarkSimple,
  'bookmark': Bookmark,
  'folder': Folder,
  'folder-open': FolderOpen,
  'palette': Palette,
  'paint-brush': PaintBrush,
  'bell': Bell,
  'bell-ringing': BellRinging,
  'star': Star,
  'wrench': Wrench,
  'cloud': Cloud,
  'cloud-arrow-up': CloudArrowUp,
  'lock': Lock,
  'lock-key': LockKey,
  'link': Link,
  'link-simple': LinkSimple,
  'heart': Heart,
  'flag': Flag,
  'tag': Tag,
  'magnifying-glass': MagnifyingGlass,
  'house': House,
  'arrow-right': ArrowRight,
  'arrow-square-out': ArrowSquareOut,
  'check-circle': CheckCircle,
  'warning': Warning,
  'warning-circle': WarningCircle,
  'info': Info,
  'pencil-simple': PencilSimple,
  'eye': Eye,
  'download': Download,
  'upload-simple': UploadSimple,
  'share-network': ShareNetwork,
  'copy': Copy,
  'clock': Clock,
  'timer': Timer,
  'calendar': Calendar,
  'map-pin': MapPin,
  'phone': Phone,
  'image': Image,
  'video-camera': VideoCamera,
  'headphones': Headphones,
  'cpu': Cpu,
  'hard-drive': HardDrive,
  'monitor': Monitor,
  'device-mobile': DeviceMobile,
  'bug': Bug,
  'robot': Robot,
  'brain': Brain,
  'sparkle': Sparkle,
  'trophy': Trophy,
  'gift': Gift,
  'handshake': Handshake,
  'tree-structure': TreeStructure,
  'kanban': Kanban,
  'list-checks': ListChecks,
  'clipboard-text': ClipboardText,
  'newspaper': Newspaper,
  'megaphone': Megaphone,
  'target': Target,
  'crosshair': Crosshair,
  'gauge': Gauge,
  'plugs': Plugs,
  'cube': Cube,
  'lifebuoy': Lifebuoy,
  'broadcast': Broadcast,
  'translate': Translate,
  'currency-dollar': CurrencyDollar,
  'storefront': Storefront,
  'truck': Truck,
  'airplane': Airplane,
  'notebook': Notebook,
  'scroll': Scroll,
  'chats': Chats,
  'seal-check': SealCheck,
  'play': Play,
  'sliders': Sliders,
  'funnel-simple': FunnelSimple,
}
