import { ArrowDown, Building2, Check, Link2, MessageSquare } from 'lucide-react';
import { TaskPriorityIcon, TaskSprintIcon } from './task-demo-icons';

export function ProjectIntake({ phase }: { phase: number }) {
  const created = phase === 3;
  return <div className="project-intake" data-phase={phase}>
    <div className="pi-source"><div className="pi-person"><img src="/new/avatars/maya.webp" width={30} height={30} alt="" /><span><strong>Maya Chen</strong><small>Northstar Labs · Customer conversation</small></span><MessageSquare size={15} /></div><p>“We’d like to test SSO with our admins first. We’re not ready to switch everyone over.”</p><div className="pi-source-link" data-linked={created}><Link2 size={12} /><span>{created ? 'Linked task · PRJ-214' : 'Customer request · SSO pilot'}</span>{created && <Check size={12} />}</div></div>
    <div className="pi-handoff"><span /><ArrowDown size={14} /><span className="pi-handoff-label">{['Capture the customer’s need', 'Ask Agent prepares the task', 'Sam approves the plan', 'Task created with its context'][phase]}</span><span /></div>
    <div className="pi-task" data-prepared={phase > 0} data-created={created}><div className="pi-task-top"><span>{created ? 'PRJ-214' : 'PROPOSED TASK'}</span><span className="pi-status">{created ? <><Check size={11} />Created</> : phase === 2 ? <><Check size={11} />Approved</> : 'For review'}</span></div><span className="pi-defined-step">A defined next step</span><h3>Add an admin-only SSO pilot</h3><p>Allow selected administrators to test SSO before a company-wide rollout.</p><div className="pi-properties"><span><small>Team</small><strong>Engineering</strong></span><span><small>Priority</small><strong><TaskPriorityIcon />High</strong></span><span><small>Owner</small><strong><img src="/new/avatars/sam.webp" width={19} height={19} alt="" />Sam Rivera</strong></span><span><small>Sprint</small><strong><TaskSprintIcon />Sprint 24</strong></span></div><div className="pi-requirements"><strong>{phase >= 2 ? 'Scope reviewed by the team' : 'Scope for team review'}</strong><ul><li>Limit the pilot to selected administrators.</li><li>Validate group-to-role mappings first.</li><li>Leave everyone else’s access unchanged.</li></ul></div><div className="pi-context-links" data-linked={created}><span><MessageSquare size={12} />Maya’s request</span><span><Building2 size={12} />Northstar Labs</span><small>{created ? 'Linked to this task' : 'Context to attach'}</small></div></div>
    <div className="pi-confirmation" data-approved={phase >= 2}><img src={phase >= 2 ? '/new/avatars/sam.webp' : '/brand/helpin-icon-white.svg'} width={22} height={22} alt="" /><span>{created ? 'Created after Sam’s approval. Ready for planning.' : phase === 2 ? 'Approved by Sam · Creating the linked task' : 'Ask Agent prepares the details for Sam to review.'}</span><Check size={13} /></div>
  </div>;
}
