// Command ai-models exports model metadata without loading commercial prices.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	sdk "github.com/helpin-ai/agent-runtime-go"
	"github.com/helpin-ai/helpin/server/internal/aimodel"
)

func main() {
	if err := export(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func export(output io.Writer) error {
	catalog, err := aimodel.LoadCatalog()
	if err != nil {
		return err
	}
	snapshot := struct {
		ServiceTiers []string                 `json:"service_tiers"`
		Models       []aimodel.PublicModel    `json:"models"`
		Tiers        []aimodel.TierDefinition `json:"tiers"`
	}{Models: catalog.PublicModels(), Tiers: catalog.Tiers, ServiceTiers: sdk.ServiceTiers()}
	encoded, err := json.MarshalIndent(snapshot, "", "  ")
	if err != nil {
		return fmt.Errorf("encode model metadata: %w", err)
	}
	_, err = fmt.Fprintf(output, "// Code generated by cmd/ai-models; DO NOT EDIT.\nexport const AI_MODELS = %s as const;\n", encoded)
	return err
}
