/**
 * Helpin Emoji Data Bundle (Crisp-compatible format)
 * Lazy-loaded on demand when emoji picker is opened.
 * Uses Apple emoji images for cross-platform consistency.
 * 
 * Format: { n: ["name", "alias1", ...], u: "unicode_codepoint", v: ["variant1", ...] }
 * Image URL: https://cdn.jsdelivr.net/npm/emoji-datasource-apple@15.0.1/img/apple/64/{codepoint}.png
 */
(function(global) {
  'use strict';

  var EMOJI_CDN_BASE = 'https://cdn.jsdelivr.net/npm/emoji-datasource-apple@15.0.1/img/apple/64/';

  var EMOJIS = [
    // Smileys & People
    {n:["grinning face","grin"],u:"1f600"},
    {n:["beaming face with smiling eyes","smile","happy"],u:"1f601"},
    {n:["grinning face with smiling eyes","smile","happy"],u:"1f602"},
    {n:["grinning face with big eyes","smile"],u:"1f603"},
    {n:["grinning face with smiling eyes","smile"],u:"1f604"},
    {n:["grinning squinting face","laugh"],u:"1f606"},
    {n:["rofl face","laugh"],u:"1f923"},
    {n:["face with tears of joy","joy","laugh"],u:"1f602",v:["1f602-1f3fb","1f602-1f3fc","1f602-1f3fd","1f602-1f3fe","1f602-1f3ff"]},
    {n:["slightly smiling face","smile"],u:"1f642"},
    {n:["upside-down face","silly"],u:"1f643"},
    {n:["winking face","wink"],u:"1f609"},
    {n:["smiling face with smiling eyes","smile","happy"],u:"1f60a"},
    {n:["smiling face with halo","innocent"],u:"1f607"},
    {n:["smiling face with hearts","love","adore"],u:"1f970"},
    {n:["smiling face with heart-eyes","love","adore"],u:"1f60d"},
    {n:["star-struck","excited","love"],u:"1f929"},
    {n:["face blowing a kiss","kiss"],u:"1f618"},
    {n:["kissing face","kiss"],u:"1f617"},
    {n:["smiling face","smile"],u:"263a"},
    {n:["kissing face with closed eyes","kiss"],u:"1f61a"},
    {n:["kissing face with smiling eyes","kiss"],u:"1f619"},
    {n:["face savoring food","yum","delicious"],u:"1f60b"},
    {n:["face with tongue out","tongue","playful"],u:"1f61b"},
    {n:["winking face with tongue","tongue","playful"],u:"1f61c"},
    {n:["zany face","crazy","wacky"],u:"1f92a"},
    {n:["squinting face with tongue","tongue"],u:"1f61d"},
    {n:["money-mouth face","money"],u:"1f911"},
    {n:["hugging face","hug"],u:"1f917"},
    {n:["face with hand over mouth","quiet","giggle"],u:"1f92d"},
    {n:["shushing face","quiet","hush"],u:"1f92b"},
    {n:["thinking face","think","hmm"],u:"1f914"},
    {n:["zipper-mouth face","quiet","secret"],u:"1f910"},
    {n:["neutral face","neutral"],u:"1f610"},
    {n:["expressionless face","neutral"],u:"1f611"},
    {n:["face without mouth","mute"],u:"1f636"},
    {n:["smirking face","smirk"],u:"1f60f"},
    {n:["unamused face","unamused"],u:"1f612"},
    {n:["face with rolling eyes","eyeroll"],u:"1f644"},
    {n:["grimacing face","grimace"],u:"1f62c"},
    {n:["lying face","liar"],u:"1f925"},
    {n:["relieved face","relieved"],u:"1f60c"},
    {n:["pensive face","pensive"],u:"1f614"},
    {n:["sleepy face","sleepy"],u:"1f61a"},
    {n:["drooling face","drool"],u:"1f924"},
    {n:["sleeping face","sleep"],u:"1f634"},
    {n:["face with medical mask","sick","ill"],u:"1f637"},
    {n:["face with thermometer","sick"],u:"1f912"},
    {n:["face with head-bandage","injured"],u:"1f915"},
    {n:["nauseated face","nauseous"],u:"1f922"},
    {n:["face vomiting","vomit"],u:"1f92e"},
    {n:["sneezing face","sneeze"],u:"1f927"},
    {n:["hot face","hot"],u:"1f975"},
    {n:["cold face","cold"],u:"1f976"},
    {n:["woozy face","dizzy"],u:"1f974"},
    {n:["face with crossed-out eyes","dizzy"],u:"1f635"},
    {n:["exploding head","mind blown"],u:"1f92f"},
    {n:["cowboy hat face","cowboy"],u:"1f920"},
    {n:["partying face","celebrate"],u:"1f973"},
    {n:["celebration face","party"],u:"1f389"},
    {n:["sunglasses face","cool"],u:"1f60e"},
    {n:["nerd face","nerd"],u:"1f913"},
    {n:["face with monocle","serious"],u:"1f9d0"},
    {n:["confused face","confused"],u:"1f615"},
    {n:["worried face","worried"],u:"1f61f"},
    {n:["slightly frowning face","sad"],u:"1f641"},
    {n:["frowning face","sad"],u:"2639"},
    {n:["face with open mouth","surprised","shocked"],u:"1f62e"},
    {n:["hushed face","quiet","surprised"],u:"1f62f"},
    {n:["astonished face","astonished","shocked"],u:"1f632"},
    {n:["flushed face","flushed","embarrassed"],u:"1f633"},
    {n:["pleading face","plead","beg"],u:"1f97a"},
    {n:["face holding back tears","sad","cry"],u:"1f979"},
    {n:["frowning face with open mouth","sad"],u:"1f626"},
    {n:["anguished face","anguished"],u:"1f627"},
    {n:["fearful face","fear","scared"],u:"1f628"},
    {n:["anxious face with sweat","anxious"],u:"1f630"},
    {n:["sad but relieved face","phew"],u:"1f625"},
    {n:["cry face","cry","sad"],u:"1f622"},
    {n:["loudly crying face","sob"],u:"1f62d"},
    {n:["face screaming in fear","scream","scared"],u:"1f631"},
    {n:["confounded face","confused"],u:"1f616"},
    {n:["persevering face","frustrated"],u:"1f623"},
    {n:["disappointed face","disappointed"],u:"1f61e"},
    {n:["downcast face with sweat","sweat"],u:"1f613"},
    {n:["weary face","tired","exhausted"],u:"1f629"},
    {n:["tired face","tired"],u:"1f62b"},
    {n:["yawning face","yawn"],u:"1f971"},
    {n:["face with steam from nose","pffft"],u:"1f624"},
    {n:["pouting face","angry","pout"],u:"1f621"},
    {n:["angry face","angry"],u:"1f620"},
    {n:["face with symbols on mouth","grawlix"],u:"1f92c"},
    {n:["smiling face with horns","devil"],u:"1f608"},
    {n:["angry face with horns","angry"],u:"1f47f"},
    {n:["skull","skull"],u:"2620"},
    {n:["pile of poo","poo","crap"],u:"1f4a9"},
    {n:["clown face","clown"],u:"1f921"},
    {n:["ogre","monster"],u:"1f479"},
    {n:["goblin","monster"],u:"1f47a"},
    {n:["ghost","ghost"],u:"1f47b"},
    {n:["alien","alien"],u:"1f47d"},
    {n:["alien monster","alien"],u:"1f47e"},
    {n:["robot","robot"],u:"1f916"},
    {n:["grinning cat","cat","smile"],u:"1f63a"},
    {n:["cat with tears of joy","cat","cry"],u:"1f639"},
    {n:["cat with wry smile","cat","smirk"],u:"1f63c"},
    {n:["kissing cat","cat","kiss"],u:"1f63d"},
    {n:["weary cat","cat","tired"],u:"1f640"},
    {n:["crying cat","cat","cry"],u:"1f63f"},
    {n:["pouting cat","cat","angry"],u:"1f63e"},
    {n:["see-no-evil monkey","monkey","blind"],u:"1f648"},
    {n:["hear-no-evil monkey","monkey","deaf"],u:"1f649"},
    {n:["speak-no-evil monkey","monkey","mute"],u:"1f64a"},
    {n:["love letter","love","letter"],u:"1f48c"},
    {n:["heart with arrow","love"],u:"1f498"},
    {n:["heart with ribbon","love"],u:"1f49d"},
    {n:["sparkling heart","love"],u:"1f496"},
    {n:["growing heart","love"],u:"1f497"},
    {n:["beating heart","love","heartbeat"],u:"1f493"},
    {n:["revolving hearts","love"],u:"1f49e"},
    {n:["two hearts","love"],u:"1f49f"},
    {n:["heart decoration","love"],u:"1f49e"},
    {n:["heart exclamation","love"],u:"2763"},
    {n:["broken heart","broken"],u:"1f494"},
    {n:["red heart","love","heart"],u:"2764"},
    {n:["orange heart","heart"],u:"1f9e1"},
    {n:["yellow heart","heart"],u:"1f49b"},
    {n:["green heart","heart"],u:"1f49a"},
    {n:["blue heart","heart"],u:"1f499"},
    {n:["purple heart","heart"],u:"1f49c"},
    {n:["brown heart","heart"],u:"1f90e"},
    {n:["black heart","heart"],u:"1f5a4"},
    {n:["white heart","heart"],u:"1f90d"},
    {n:["hundred points","perfect"],u:"1f4af"},
    {n:["anger symbol","anger"],u:"1f4a2"},
    {n:["collision","boom","explosion"],u:"1f4a5"},
    {n:["dizzy","dizzy"],u:"1f4ab"},
    {n:["sweat droplets","sweat"],u:"1f4a6"},
    {n:["dashing away","dash"],u:"1f4a8"},
    {n:["hole","hole"],u:"1f573"},
    {n:["bomb","bomb"],u:"1f4a3"},
    {n:["speech balloon","speech"],u:"1f4ac"},
    {n:["eye in speech bubble","eye","speech"],u:"1f441"},
    {n:["left speech bubble","speech"],u:"1f5e8"},
    {n:["right anger bubble","anger"],u:"1f5ef"},
    {n:["thought balloon","thought"],u:"1f4ad"},
    {n:["zzz","sleep"],u:"1f4a4"},

    // Animals & Nature
    {n:["dog face","dog","puppy"],u:"1f436"},
    {n:["cat face","cat","kitty"],u:"1f431"},
    {n:["mouse face","mouse"],u:"1f42d"},
    {n:["hamster","hamster"],u:"1f439"},
    {n:["rabbit face","rabbit","bunny"],u:"1f430"},
    {n:["fox face","fox"],u:"1f98a"},
    {n:["bear face","bear"],u:"1f43b"},
    {n:["panda face","panda"],u:"1f43c"},
    {n:["koala face","koala"],u:"1f428"},
    {n:["tiger face","tiger"],u:"1f42f"},
    {n:["lion face","lion"],u:"1f981"},
    {n:["cow face","cow"],u:"1f42e"},
    {n:["pig face","pig"],u:"1f437"},
    {n:["frog face","frog"],u:"1f438"},
    {n:["monkey face","monkey"],u:"1f435"},
    {n:["chicken","chicken"],u:"1f414"},
    {n:["penguin","penguin"],u:"1f427"},
    {n:["bird","bird"],u:"1f426"},
    {n:["baby chick","chick"],u:"1f424"},
    {n:["hatching chick","chick"],u:"1f423"},
    {n:["front-facing baby chick","chick"],u:"1f425"},
    {n:["duck","duck"],u:"1f986"},
    {n:["eagle","eagle"],u:"1f985"},
    {n:["owl","owl"],u:"1f989"},
    {n:["bat","bat"],u:"1f987"},
    {n:["wolf face","wolf"],u:"1f43a"},
    {n:["boar","boar"],u:"1f417"},
    {n:["horse face","horse"],u:"1f434"},
    {n:["unicorn face","unicorn"],u:"1f984"},
    {n:["honeybee","bee"],u:"1f41d"},
    {n:["bug","bug","insect"],u:"1f41b"},
    {n:["ant","ant"],u:"1f41c"},
    {n:["beetle","beetle"],u:"1fab2"},
    {n:["snail","snail"],u:"1f40c"},
    {n:["butterfly","butterfly"],u:"1f98b"},
    {n:["lady beetle","ladybug"],u:"1f41e"},
    {n:["spider","spider"],u:"1f577"},
    {n:["spider web","spider"],u:"1f578"},
    {n:["scorpion","scorpion"],u:"1f982"},
    {n:["turtle","turtle"],u:"1f422"},
    {n:["snake","snake"],u:"1f40d"},
    {n:["lizard","lizard"],u:"1f98e"},
    {n:["t-rex","dinosaur","trex"],u:"1f996"},
    {n:["spouting whale","whale"],u:"1f433"},
    {n:["dolphin","dolphin"],u:"1f42c"},
    {n:["fish","fish"],u:"1f41f"},
    {n:["tropical fish","fish"],u:"1f420"},
    {n:["blowfish","blowfish"],u:"1f421"},
    {n:["shark","shark"],u:"1f988"},
    {n:["octopus","octopus"],u:"1f419"},
    {n:["squid","squid"],u:"1f991"},
    {n:["shrimp","shrimp"],u:"1f990"},
    {n:["crab","crab"],u:"1f980"},
    {n:["lobster","lobster"],u:"1f99e"},
    {n:["paw prints","paw"],u:"1f43e"},
    {n:["chipmunk","chipmunk"],u:"1f43f"},
    {n:["hedgehog","hedgehog"],u:"1f994"},
    {n:["raccoon","raccoon"],u:"1f99a"},
    {n:["llama","llama"],u:"1f999"},
    {n:["giraffe","giraffe"],u:"1f992"},
    {n:["elephant","elephant"],u:"1f418"},
    {n:["mammoth","mammoth"],u:"1f9a3"},
    {n:["rhino","rhinoceros"],u:"1f98f"},
    {n:["hippopotamus","hippo"],u:"1f99b"},
    {n:["crocodile","crocodile"],u:"1f40a"},
    {n:["camel","camel"],u:"1f42b"},
    {n:["zebra","zebra"],u:"1f993"},
    {n:["deer","deer"],u:"1f98c"},
    {n:["maple leaf","leaf"],u:"1f341"},
    {n:["fallen leaf","leaf"],u:"1f342"},
    {n:["leaf fluttering in wind","leaf"],u:"1f343"},
    {n:["herb","herb"],u:"1f33f"},
    {n:["shamrock","clover"],u:"2618"},
    {n:["four leaf clover","clover","luck"],u:"1f340"},
    {n:["palm tree","palm","tree"],u:"1f334"},
    {n:["cactus","cactus"],u:"1f335"},
    {n:["christmas tree","christmas","tree"],u:"1f384"},
    {n:["seedling","seedling","plant"],u:"1f331"},
    {n:["cherry blossom","flower","blossom"],u:"1f338"},
    {n:["white flower","flower"],u:"1f4ae"},
    {n:["lotus","lotus"],u:"1fac4"},
    {n:["sunflower","sunflower"],u:"1f33b"},
    {n:["rose","rose","flower"],u:"1f339"},
    {n:["wilted flower","flower"],u:"1f940"},
    {n:["hibiscus","flower"],u:"1f33a"},
    {n:["tulip","tulip","flower"],u:"1f337"},
    {n:["sun with face","sun","sunny"],u:"1f31e"},
    {n:["full moon","moon"],u:"1f319"},
    {n:["crescent moon","moon"],u:"1f319"},
    {n:["earth americas","earth","globe"],u:"1f30e"},
    {n:["earth europe africa","earth","globe"],u:"1f30d"},
    {n:["earth asia","earth","globe"],u:"1f30f"},
    {n:["ringed planet","planet","saturn"],u:"1fa90"},
    {n:["glowing star","star","sparkle"],u:"1f31f"},
    {n:["sparkles","sparkles"],u:"2728"},
    {n:["star","star"],u:"2b50"},
    {n:["fire","fire","flame"],u:"1f525"},
    {n:["cloud","cloud"],u:"2601"},
    {n:["sun behind cloud","cloud","sun"],u:"26c5"},
    {n:["cloud with lightning","lightning","storm"],u:"1f329"},
    {n:["tornado","tornado","twister"],u:"1f32a"},
    {n:["fog","fog"],u:"1f32b"},
    {n:["wind face","wind"],u:"1f32c"},
    {n:["umbrella with rain drops","umbrella","rain"],u:"2614"},
    {n:["snowflake","snow","snowflake"],u:"2744"},
    {n:["snowman without snow","snowman"],u:"26c4"},
    {n:["snowman","snowman"],u:"2603"},
    {n:["lightning","lightning"],u:"26a1"},
    {n:["rainbow","rainbow"],u:"1f308"},

    // Food & Drink
    {n:["red apple","apple","fruit"],u:"1f34e"},
    {n:["green apple","apple","fruit"],u:"1f34f"},
    {n:["pear","pear","fruit"],u:"1f350"},
    {n:["tangerine","orange","fruit"],u:"1f34a"},
    {n:["lemon","lemon","fruit"],u:"1f34b"},
    {n:["banana","banana","fruit"],u:"1f34c"},
    {n:["watermelon","watermelon","fruit"],u:"1f349"},
    {n:["grapes","grapes","fruit"],u:"1f347"},
    {n:["blueberries","blueberries","fruit"],u:"1fad0"},
    {n:["melon","melon","fruit"],u:"1f348"},
    {n:["cherries","cherries","fruit"],u:"1f352"},
    {n:["strawberry","strawberry","fruit"],u:"1f353"},
    {n:["peach","peach","fruit"],u:"1f351"},
    {n:["mango","mango","fruit"],u:"1f96d"},
    {n:["pineapple","pineapple","fruit"],u:"1f34d"},
    {n:["kiwi fruit","kiwi","fruit"],u:"1fad5"},
    {n:["tomato","tomato","vegetable"],u:"1f345"},
    {n:["eggplant","eggplant","vegetable"],u:"1f346"},
    {n:["avocado","avocado","vegetable"],u:"1f951"},
    {n:["broccoli","broccoli","vegetable"],u:"1f966"},
    {n:["leafy green","lettuce","vegetable"],u:"1f96c"},
    {n:["cucumber","cucumber","vegetable"],u:"1f952"},
    {n:["hot pepper","pepper","spicy"],u:"1f336"},
    {n:["corn","corn","vegetable"],u:"1f33d"},
    {n:["carrot","carrot","vegetable"],u:"1f955"},
    {n:["potato","potato","vegetable"],u:"1f954"},
    {n:["sweet potato","potato","vegetable"],u:"1f360"},
    {n:["croissant","croissant","pastry"],u:"1f96e"},
    {n:["bagel","bagel","breakfast"],u:"1f96f"},
    {n:["bread","bread"],u:"1f35e"},
    {n:["baguette bread","bread","french"],u:"1f956"},
    {n:["pretzel","pretzel"],u:"1f968"},
    {n:["cheese wedge","cheese"],u:"1f9c0"},
    {n:["egg","egg","breakfast"],u:"1f95a"},
    {n:["cooking","egg","frying"],u:"1f373"},
    {n:["pancakes","pancakes","breakfast"],u:"1f95e"},
    {n:["waffle","waffle","breakfast"],u:"1f9c7"},
    {n:["bacon","bacon","breakfast"],u:"1f969"},
    {n:["cut of meat","meat","steak"],u:"1f969"},
    {n:["poultry leg","chicken","meat"],u:"1f357"},
    {n:["meat on bone","meat","bone"],u:"1f356"},
    {n:["hot dog","hotdog","food"],u:"1f32d"},
    {n:["hamburger","hamburger","burger"],u:"1f354"},
    {n:["french fries","fries"],u:"1f35f"},
    {n:["pizza","pizza"],u:"1f355"},
    {n:["flatbread","flatbread","pizza"],u:"1f959"},
    {n:["sandwich","sandwich"],u:"1f96a"},
    {n:["taco","taco","mexican"],u:"1f32e"},
    {n:["burrito","burrito","mexican"],u:"1f32f"},
    {n:["salad","salad","bowl"],u:"1f957"},
    {n:["shallow pan of food","paella","food"],u:"1f958"},
    {n:["spaghetti","pasta","spaghetti"],u:"1f35d"},
    {n:["steaming bowl","ramen","noodles"],u:"1f35c"},
    {n:["curry rice","curry","rice"],u:"1f35b"},
    {n:["rice ball","onigiri","rice"],u:"1f359"},
    {n:["cooked rice","rice","bowl"],u:"1f35a"},
    {n:["rice cracker","senbei","rice"],u:"1f358"},
    {n:["dango","dango","dessert"],u:"1f361"},
    {n:["dumpling","dumpling","gyoza"],u:"1f95f"},
    {n:["fried shrimp","tempura","shrimp"],u:"1f364"},
    {n:["oden","oden","food"],u:"1f362"},
    {n:["sushi","sushi","japanese"],u:"1f363"},
    {n:["shaved ice","ice cream","dessert"],u:"1f367"},
    {n:["ice cream","ice cream","dessert"],u:"1f368"},
    {n:["pie","pie","dessert"],u:"1f967"},
    {n:["cupcake","cupcake","dessert"],u:"1f9c1"},
    {n:["birthday cake","birthday","cake"],u:"1f382"},
    {n:["shortcake","cake","dessert"],u:"1f370"},
    {n:["custard","custard","dessert"],u:"1f36b"},
    {n:["candy","candy","sweets"],u:"1f36c"},
    {n:["lollipop","lollipop","candy"],u:"1f36d"},
    {n:["chocolate bar","chocolate","candy"],u:"1f36b"},
    {n:["popcorn","popcorn","snack"],u:"1f37f"},
    {n:["doughnut","donut","dessert"],u:"1f369"},
    {n:["cookie","cookie","biscuit"],u:"1f36a"},
    {n:["chestnut","chestnut","nut"],u:"1f330"},
    {n:["peanuts","peanuts","nut"],u:"1f95c"},
    {n:["honey pot","honey","sweet"],u:"1f36f"},
    {n:["glass of milk","milk","drink"],u:"1f95b"},
    {n:["cup with straw","juice","drink"],u:"1f964"},
    {n:["coffee","coffee","drink"],u:"2615"},
    {n:["teapot","teapot","tea"],u:"1fad6"},
    {n:["teacup without handle","tea","drink"],u:"1f95b"},
    {n:["sake","sake","alcohol"],u:"1f376"},
    {n:["beer mug","beer","alcohol"],u:"1f37a"},
    {n:["clinking beer mugs","beers","cheers"],u:"1f37b"},
    {n:["wine glass","wine","alcohol"],u:"1f377"},
    {n:["tumbler glass","whiskey","alcohol"],u:"1f943"},
    {n:["cocktail glass","cocktail","alcohol"],u:"1f378"},
    {n:["tropical drink","cocktail","tropical"],u:"1f379"},
    {n:["bottle with popping cork","champagne","celebration"],u:"1f37e"},
    {n:["baby bottle","milk","baby"],u:"1f37c"},
    {n:["fork and knife with plate","dinner","meal"],u:"1f37d"},
    {n:["chopsticks","chopsticks","eating"],u:"1f962"},
    {n:["spoon","spoon","utensil"],u:"1f944"},
    {n:["kitchen knife","knife","cooking"],u:"1f52a"},

    // Activities
    {n:["soccer ball","soccer","football"],u:"1f3c0"},
    {n:["basketball","basketball"],u:"1f3c0"},
    {n:["american football","football","usa"],u:"1f3c8"},
    {n:["baseball","baseball"],u:"26be"},
    {n:["softball","softball"],u:"1f94e"},
    {n:["tennis","tennis"],u:"1f3be"},
    {n:["volleyball","volleyball"],u:"1f3d0"},
    {n:["rugby football","rugby"],u:"1f3c9"},
    {n:["flying disc","frisbee"],u:"1f94f"},
    {n:["pool 8 ball","billiards","8ball"],u:"1f3b1"},
    {n:["ping pong","ping pong","table tennis"],u:"1f3d3"},
    {n:["badminton","badminton"],u:"1f3f8"},
    {n:["hockey","hockey"],u:"1f3d2"},
    {n:["field hockey","hockey"],u:"1f3d2"},
    {n:["golf","golf"],u:"26f3"},
    {n:["bowling","bowling"],u:"1f3b3"},
    {n:["skateboard","skateboard"],u:"1f6f9"},
    {n:["ice skate","skate","ice"],u:"26f8"},
    {n:["snowboarder","snowboard"],u:"1f3c2"},
    {n:["skier","ski","skiing"],u:"26f7"},
    {n:["person swimming","swim","swimming"],u:"1f3ca"},
    {n:["person surfing","surf","surfing"],u:"1f3c4"},
    {n:["water polo","water polo","sport"],u:"1f93d"},
    {n:["person rowing boat","row","boat"],u:"1f6a3"},
    {n:["person climbing","climb","climbing"],u:"1f9d7"},
    {n:["person mountain biking","bike","mountain"],u:"1f6b5"},
    {n:["person biking","bike","cycling"],u:"1f6b4"},
    {n:["trophy","trophy","award"],u:"1f3c6"},
    {n:["first place medal","medal","gold"],u:"1f947"},
    {n:["second place medal","medal","silver"],u:"1f948"},
    {n:["third place medal","medal","bronze"],u:"1f949"},
    {n:["sports medal","medal"],u:"1f3c5"},
    {n:["ticket","ticket","event"],u:"1f3ab"},
    {n:["circus tent","circus","festival"],u:"1f3aa"},
    {n:["person jumping","jump","celebrate"],u:"1f57a"},
    {n:["person cartwheeling","gymnastics","cartwheel"],u:"1f938"},
    {n:["person fencing","fencing","sport"],u:"1f93a"},
    {n:["wrestlers","wrestling","sport"],u:"1f93c"},
    {n:["person playing handball","handball","sport"],u:"1f93e"},
    {n:["person boxing","boxing","sport"],u:"1f94a"},
    {n:["martial arts uniform","karate","martial arts"],u:"1f94b"},
    {n:["person lifting weights","gym","weights"],u:"1f3cb"},
    {n:["person golfing","golf","sport"],u:"1f3cc"},
    {n:["person walking","walk","hiking"],u:"1f6b6"},
    {n:["person running","run","running"],u:"1f3c3"},
    {n:["woman dancing","dance","dancing"],u:"1f483"},
    {n:["horse racing","horse","racing"],u:"1f3c7"},
    {n:["video game","game","video"],u:"1f3ae"},
    {n:["game die","dice","game"],u:"1f3b2"},
    {n:["jigsaw","puzzle","jigsaw"],u:"1f9e9"},
    {n:["teddy bear","teddy","toy"],u:"1f9f8"},
    {n:["spade suit","spade","cards"],u:"2660"},
    {n:["heart suit","heart","cards"],u:"2665"},
    {n:["diamond suit","diamond","cards"],u:"2666"},
    {n:["club suit","club","cards"],u:"2663"},
    {n:["mahjong red dragon","mahjong","game"],u:"1f004"},
    {n:["flower playing cards","cards","flower"],u:"1f3b4"},
    {n:["performing arts","theater","drama"],u:"1f3ad"},
    {n:["artist palette","art","palette"],u:"1f3a8"},
    {n:["musical keyboard","music","keyboard"],u:"1f3b9"},
    {n:["guitar","guitar","music"],u:"1f3b8"},
    {n:["musical notes","music","notes"],u:"1f3b6"},
    {n:["trumpet","trumpet","music"],u:"1f3ba"},
    {n:["saxophone","saxophone","music"],u:"1f3b7"},
    {n:["violin","violin","music"],u:"1f3bb"},
    {n:["drum","drum","music"],u:"1f941"},
    {n:["clapper","clapperboard","movie"],u:"1f3ac"},
    {n:["microphone","mic","music"],u:"1f3a4"},
    {n:["headphone","headphone","music"],u:"1f3a7"},
    {n:["radio","radio","music"],u:"1f4fb"},

    // Travel & Places
    {n:["car","car","automobile"],u:"1f697"},
    {n:["taxi","taxi","cab"],u:"1f695"},
    {n:["sport utility vehicle","suv","car"],u:"1f699"},
    {n:["bus","bus"],u:"1f68c"},
    {n:["trolleybus","trolley","bus"],u:"1f68e"},
    {n:["racing car","race","car"],u:"1f3ce"},
    {n:["ambulance","ambulance","medical"],u:"1f691"},
    {n:["fire engine","fire","truck"],u:"1f692"},
    {n:["police car","police","car"],u:"1f693"},
    {n:["delivery truck","truck","delivery"],u:"1f69a"},
    {n:["dump truck","truck","dump"],u:"1f69b"},
    {n:["articulated lorry","truck","lorry"],u:"1f69b"},
    {n:["tractor","tractor","farm"],u:"1f69c"},
    {n:["probing cane","accessibility","blind"],u:"1f9af"},
    {n:["manual wheelchair","wheelchair","disability"],u:"1f9bd"},
    {n:["bicycle","bike","bicycle"],u:"1f6b2"},
    {n:["scooter","scooter","moped"],u:"1f6f5"},
    {n:["motor scooter","scooter","motorbike"],u:"1f6f5"},
    {n:["bus stop","busstop","stop"],u:"1f68f"},
    {n:["anchor","anchor","boat"],u:"2693"},
    {n:["sailboat","boat","sail"],u:"26f5"},
    {n:["speedboat","boat","speed"],u:"1f6a4"},
    {n:["passenger ship","ship","cruise"],u:"1f6f3"},
    {n:["ferry","ferry","boat"],u:"26f4"},
    {n:["motor boat","boat","motor"],u:"1f6e5"},
    {n:["ship","ship","boat"],u:"1f6a2"},
    {n:["airplane","airplane","flight"],u:"2708"},
    {n:["airplane departure","departure","takeoff"],u:"1f6eb"},
    {n:["airplane arrival","arrival","landing"],u:"1f6ec"},
    {n:["satellite","satellite","space"],u:"1f4f1"},
    {n:["rocket","rocket","space"],u:"1f680"},
    {n:["flying saucer","ufo","alien"],u:"1f6f8"},
    {n:["bellhop bell","bell","hotel"],u:"1f6ce"},
    {n:["luggage","luggage","travel"],u:"1f9f3"},
    {n:["hourglass","hourglass","time"],u:"23f3"},
    {n:["watch","watch","time"],u:"231a"},
    {n:["alarm clock","alarm","clock"],u:"23f0"},
    {n:["stopwatch","stopwatch","time"],u:"23f1"},
    {n:["timer clock","timer","clock"],u:"23f2"},
    {n:["mantlepiece clock","clock","time"],u:"1f570"},
    {n:["newspaper","newspaper","news"],u:"1f4f0"},
    {n:["mobile phone","phone","mobile"],u:"1f4f1"},
    {n:["smartphone","smartphone","phone"],u:"1f4f1"},
    {n:["laptop","laptop","computer"],u:"1f4bb"},
    {n:["desktop computer","computer","desktop"],u:"1f5a5"},
    {n:["printer","printer","computer"],u:"1f5a8"},
    {n:["keyboard","keyboard","computer"],u:"2328"},
    {n:["computer mouse","mouse","computer"],u:"1f5b1"},
    {n:["trackball mouse","trackball","computer"],u:"1f5b2"},
    {n:["floppy disk","floppy","computer"],u:"1f4be"},
    {n:["cd","cd","dvd"],u:"1f4bf"},
    {n:["dvd","dvd","disc"],u:"1f4c0"},
    {n:["movie camera","movie","camera"],u:"1f3ac"},
    {n:["film frames","film","movie"],u:"1f39e"},
    {n:["film projector","projector","movie"],u:"1f4fd"},
    {n:["television","tv","television"],u:"1f4fa"},
    {n:["camera","camera","photo"],u:"1f4f7"},
    {n:["camera with flash","camera","flash"],u:"1f4f8"},
    {n:["video camera","video","camera"],u:"1f4f9"},
    {n:["videocassette","vhs","video"],u:"1f4fc"},
    {n:["magnifying glass tilted left","search","find"],u:"1f50d"},
    {n:["magnifying glass tilted right","search","find"],u:"1f50e"},
    {n:["microscope","microscope","science"],u:"1f52c"},
    {n:["telescope","telescope","science"],u:"1f52d"},
    {n:["satellite antenna","antenna","signal"],u:"1f4e1"},
    {n:["globe showing americas","globe","world"],u:"1f30e"},
    {n:["globe showing europe-africa","globe","world"],u:"1f30d"},
    {n:["globe showing asia-australia","globe","world"],u:"1f30f"},
    {n:["globe with meridians","globe","world"],u:"1f310"},
    {n:["world map","map","world"],u:"1f5fa"},
    {n:["map of japan","japan","map"],u:"1f5fe"},
    {n:["compass","compass","direction"],u:"1f9ed"},
    {n:["snow-capped mountain","mountain","snow"],u:"1f3d4"},
    {n:["mountain","mountain"],u:"26f0"},
    {n:["volcano","volcano"],u:"1f30b"},
    {n:["mount fuji","fuji","mountain"],u:"1f5fb"},
    {n:["camping","camping","tent"],u:"1f3d5"},
    {n:["beach with umbrella","beach","umbrella"],u:"1f3d6"},
    {n:["desert island","island","desert"],u:"1f3dd"},
    {n:["desert","desert"],u:"1f3dc"},
    {n:["national park","park","nature"],u:"1f3de"},
    {n:["stadium","stadium"],u:"1f3df"},
    {n:["classical building","building","classic"],u:"1f3db"},
    {n:["building construction","construction","building"],u:"1f3d7"},
    {n:["houses","houses","buildings"],u:"1f3f8"},
    {n:["cityscape","city","building"],u:"1f3d9"},
    {n:["derelict house","house","abandoned"],u:"1f3da"},
    {n:["house","house","home"],u:"1f3e0"},
    {n:["house with garden","house","garden"],u:"1f3e1"},
    {n:["office building","office","building"],u:"1f3e2"},
    {n:["japanese post office","post","japan"],u:"1f3e3"},
    {n:["post office","post","building"],u:"1f3e4"},
    {n:["hospital","hospital","medical"],u:"1f3e5"},
    {n:["bank","bank","building"],u:"1f3e6"},
    {n:["hotel","hotel","building"],u:"1f3e8"},
    {n:["love hotel","love","hotel"],u:"1f3e9"},
    {n:["convenience store","store","convenience"],u:"1f3ea"},
    {n:["school","school","building"],u:"1f3eb"},
    {n:["department store","store","department"],u:"1f3ec"},
    {n:["factory","factory","building"],u:"1f3ed"},
    {n:["japanese castle","castle","japan"],u:"1f3ef"},
    {n:["castle","castle","building"],u:"1f3f0"},
    {n:["wedding","wedding","love"],u:"1f492"},
    {n:["tokyo tower","tower","tokyo"],u:"1f5fc"},
    {n:["statue of liberty","liberty","statue"],u:"1f5fd"},
    {n:["church","church","religion"],u:"26ea"},
    {n:["mosque","mosque","religion"],u:"1f54c"},
    {n:["synagogue","synagogue","religion"],u:"1f6d8"},
    {n:["shinto shrine","shrine","religion"],u:"26e9"},
    {n:["kaaba","kaaba","religion"],u:"1f54b"},
    {n:["fountain","fountain","water"],u:"26f2"},
    {n:["tent","tent","camping"],u:"26fa"},
    {n:["foggy","fog","weather"],u:"1f301"},
    {n:["night with stars","night","stars"],u:"1f303"},
    {n:["sunrise over mountains","sunrise","morning"],u:"1f304"},
    {n:["sunrise","sunrise","morning"],u:"1f305"},
    {n:["cityscape at dusk","city","dusk"],u:"1f306"},
    {n:["sunset","sunset","evening"],u:"1f307"},
    {n:["bridge at night","bridge","night"],u:"1f309"},
    {n:["carousel horse","horse","carousel"],u:"1f3a0"},
    {n:["ferris wheel","ferris","wheel"],u:"1f3a1"},
    {n:["roller coaster","roller","coaster"],u:"1f3a2"},

    // Objects
    {n:["wristwatch","watch","time"],u:"231a"},
    {n:["stopwatch","stopwatch","time"],u:"23f1"},
    {n:["timer clock","timer","time"],u:"23f2"},
    {n:["alarm clock","alarm","clock"],u:"23f0"},
    {n:["mantlepiece clock","clock","fireplace"],u:"1f570"},
    {n:["hourglass","hourglass","time"],u:"23f3"},
    {n:["mobile phone","phone","mobile"],u:"1f4f1"},
    {n:["smartphone","smartphone","phone"],u:"1f4f1"},
    {n:["laptop","laptop","computer"],u:"1f4bb"},
    {n:["desktop computer","computer","desktop"],u:"1f5a5"},
    {n:["keyboard","keyboard","computer"],u:"2328"},
    {n:["printer","printer","computer"],u:"1f5a8"},
    {n:["computer mouse","mouse","computer"],u:"1f5b1"},
    {n:["floppy disk","floppy","computer"],u:"1f4be"},
    {n:["cd","cd","disc"],u:"1f4bf"},
    {n:["dvd","dvd","disc"],u:"1f4c0"},
    {n:["ballpoint pen","pen","writing"],u:"1f58a"},
    {n:["fountain pen","pen","writing"],u:"1f58b"},
    {n:["paintbrush","brush","art"],u:"1f58c"},
    {n:["crayon","crayon","art"],u:"1f58d"},
    {n:["pencil","pencil","writing"],u:"270f"},
    {n:["memo","memo","note"],u:"1f4dd"},
    {n:["briefcase","briefcase","work"],u:"1f4bc"},
    {n:["file folder","folder","file"],u:"1f4c1"},
    {n:["open file folder","folder","open"],u:"1f4c2"},
    {n:["card file box","box","file"],u:"1f5c3"},
    {n:["file cabinet","cabinet","file"],u:"1f5c4"},
    {n:["wastebasket","trash","bin"],u:"1f4d4"},
    {n:["notepad","notepad","paper"],u:"1f4d3"},
    {n:["ledger","ledger","book"],u:"1f4d2"},
    {n:["page facing up","page","paper"],u:"1f4c4"},
    {n:["calendar","calendar","date"],u:"1f4c5"},
    {n:["tear-off calendar","calendar","tear"],u:"1f4c6"},
    {n:["chart increasing","chart","graph"],u:"1f4c8"},
    {n:["bar chart","chart","bar"],u:"1f4ca"},
    {n:["clipboard","clipboard","paper"],u:"1f4cb"},
    {n:["pushpin","pushpin","pin"],u:"1f4cc"},
    {n:["round pushpin","pin","pushpin"],u:"1f4cd"},
    {n:["paperclip","paperclip","attachment"],u:"1f4ce"},
    {n:["linked paperclips","paperclip","link"],u:"1f587"},
    {n:["scissors","scissors","cut"],u:"2702"},
    {n:["lock","lock","security"],u:"1f512"},
    {n:["open lock","lock","unlock"],u:"1f513"},
    {n:["lock with ink pen","lock","secret"],u:"1f50f"},
    {n:["closed lock with key","lock","key"],u:"1f510"},
    {n:["key","key"],u:"1f511"},
    {n:["old key","key","vintage"],u:"1f5dd"},
    {n:["hammer","hammer","tool"],u:"1f528"},
    {n:["axe","axe","tool"],u:"1fa93"},
    {n:["hammer and pick","tool","repair"],u:"2692"},
    {n:["hammer and wrench","tool","repair"],u:"1f6e0"},
    {n:["dagger","dagger","weapon"],u:"1f5e1"},
    {n:["crossed swords","swords","weapon"],u:"2694"},
    {n:["bomb","bomb","explosive"],u:"1f4a3"},
    {n:["bow and arrow","bow","archery"],u:"1f3f9"},
    {n:["shield","shield","protection"],u:"1f6e1"},
    {n:["cigarette","cigarette","smoking"],u:"1faac"},
    {n:["coffin","coffin","death"],u:"26b0"},
    {n:["funeral urn","urn","death"],u:"26b1"},
    {n:["amphora","amphora","vase"],u:"1f3fa"},
    {n:["crystal ball","crystal","magic"],u:"1f52e"},
    {n:["nazar amulet","nazar","amulet"],u:"1f9ff"},
    {n:["diya lamp","lamp","diya"],u:"1fa94"},
    {n:["seat","seat","chair"],u:"1f4ba"},
    {n:["couch and lamp","couch","sofa"],u:"1f6cb"},
    {n:["bed","bed","sleep"],u:"1f6cf"},
    {n:["toilet","toilet","bathroom"],u:"1f6bd"},
    {n:["shower","shower","bathroom"],u:"1f6bf"},
    {n:["bathtub","bathtub","bathroom"],u:"1f6c1"},
    {n:["bath","bath","hot tub"],u:"1f6c0"},
    {n:["soap","soap","bathroom"],u:"1f9fc"},
    {n:["toothbrush","toothbrush","dental"],u:"1faa5"},
    {n:["fire extinguisher","extinguisher","fire"],u:"1f9ef"},
    {n:["warning","warning","sign"],u:"26a0"},
    {n:["no entry","no","entry"],u:"26d4"},
    {n:["prohibited","no","prohibited"],u:"1f6ab"},
    {n:["safety pin","pin","safety"],u:"1fa77"},
    {n:["safety goggles","goggles","safety"],u:"1f9b0"},
    {n:["safety vest","vest","safety"],u:"1f9ba"},
    {n:["balance scale","scale","balance"],u:"2696"},
    {n:["ladder","ladder","tool"],u:"1fa9c"},

    // Symbols
    {n:["red heart","heart","love"],u:"2764"},
    {n:["pink heart","heart","pink"],u:"1f493"},
    {n:["orange heart","heart","orange"],u:"1f9e1"},
    {n:["yellow heart","heart","yellow"],u:"1f49b"},
    {n:["green heart","heart","green"],u:"1f49a"},
    {n:["blue heart","heart","blue"],u:"1f499"},
    {n:["purple heart","heart","purple"],u:"1f49c"},
    {n:["brown heart","heart","brown"],u:"1f90e"},
    {n:["black heart","heart","black"],u:"1f5a4"},
    {n:["white heart","heart","white"],u:"1f90d"},
    {n:["broken heart","heart","broken"],u:"1f494"},
    {n:["heart exclamation","heart","exclamation"],u:"2763"},
    {n:["heart with ribbon","heart","ribbon"],u:"1f49d"},
    {n:["heart with arrow","heart","cupid"],u:"1f498"},
    {n:["sparkling heart","heart","sparkle"],u:"1f496"},
    {n:["growing heart","heart","growing"],u:"1f497"},
    {n:["beating heart","heart","beating"],u:"1f493"},
    {n:["revolving hearts","hearts","revolving"],u:"1f49e"},
    {n:["two hearts","hearts","double"],u:"1f49f"},
    {n:["love letter","letter","love"],u:"1f48c"},
    {n:["kiss mark","kiss","lip"],u:"1f48b"},
    {n:["smiling face with hearts","face","hearts"],u:"1f970"},
    {n:["star","star"],u:"2b50"},
    {n:["glowing star","star","sparkle"],u:"1f31f"},
    {n:["sparkles","sparkles","shine"],u:"2728"},
    {n:["collision","boom","collision"],u:"1f4a5"},
    {n:["fire","fire","flame"],u:"1f525"},
    {n:["droplet","droplet","water"],u:"1f4a7"},
    {n:["dash","dash","running"],u:"1f4a8"},
    {n:["zzz","sleep","tired"],u:"1f4a4"},
    {n:["thought balloon","thought","bubble"],u:"1f4ad"},
    {n:["speech balloon","speech","bubble"],u:"1f4ac"},
    {n:["right anger bubble","anger","bubble"],u:"1f5ef"},
    {n:["left speech bubble","speech","bubble"],u:"1f5e8"},
    {n:["eye","eye","see"],u:"1f441"},
    {n:["brain","brain","head"],u:"1f9e0"},
    {n:["lightning","lightning","bolt"],u:"26a1"},
    {n:["sun","sun","weather"],u:"2600"},
    {n:["cloud","cloud","weather"],u:"2601"},
    {n:["umbrella","umbrella","weather"],u:"2614"},
    {n:["rainbow","rainbow","weather"],u:"1f308"},
    {n:["snowflake","snow","snowflake"],u:"2744"},
    {n:["check mark","check","done"],u:"2713"},
    {n:["cross mark","cross","wrong"],u:"2717"},
    {n:["cross mark button","cross","button"],u:"274e"},
    {n:["check mark button","check","button"],u:"2705"},
    {n:["plus","plus","add"],u:"2795"},
    {n:["minus","minus","subtract"],u:"2796"},
    {n:["division","divide","math"],u:"2797"},
    {n:["multiply","multiply","math"],u:"2716"},
    {n:["infinity","infinity","math"],u:"267e"},
    {n:["double exclamation mark","exclamation","alert"],u:"203c"},
    {n:["exclamation question mark","exclamation","question"],u:"2049"},
    {n:["question mark","question","what"],u:"2753"},
    {n:["white question mark","question","white"],u:"2754"},
    {n:["white exclamation mark","exclamation","white"],u:"2755"},
    {n:["exclamation mark","exclamation","alert"],u:"2757"},
    {n:["currency exchange","exchange","currency"],u:"1f4b1"},
    {n:["heavy dollar sign","dollar","money"],u:"1f4b2"},
    {n:["tm","tm","trademark"],u:"2122"},
    {n:["registered","registered","trademark"],u:"00ae"},
    {n:["copyright","copyright"],u:"00a9"},
    {n:["speaker","speaker","volume"],u:"1f508"},
    {n:["speaker with sound waves","speaker","sound"],u:"1f50a"},
    {n:["speaker with cancellation slash","mute","speaker"],u:"1f507"},
    {n:["bell","bell","notification"],u:"1f514"},
    {n:["bell with cancellation slash","mute","bell"],u:"1f515"},
    {n:["megaphone","megaphone","announcement"],u:"1f4e3"},
    {n:["studio microphone","microphone","studio"],u:"1f3a4"},
    {n:["level slider","slider","audio"],u:"1f39a"},
    {n:["control knobs","knobs","audio"],u:"1f39b"},
    {n:["radio","radio"],u:"1f4fb"},
    {n:["clapper board","clapper","film"],u:"1f3ac"},
    {n:["low brightness","brightness","dim"],u:"1f505"},
    {n:["high brightness","brightness","sun"],u:"1f506"},
    {n:["mobile phone off","phone","off"],u:"1f4f4"},
    {n:["vibration mode","vibrate","phone"],u:"1f4f3"},
    {n:["antenna bars","antenna","signal"],u:"1f4f6"},
    {n:["camera","camera","photo"],u:"1f4f7"},
    {n:["camera with flash","camera","flash"],u:"1f4f8"},
    {n:["video camera","video","camera"],u:"1f4f9"},
    {n:["television","tv","television"],u:"1f4fa"},
    {n:["optical disc","disc","cd"],u:"1f4bf"},
    {n:["dvd","dvd","disc"],u:"1f4c0"},
    {n:["floppy disk","floppy","disk"],u:"1f4be"},
    {n:["key","key","password"],u:"1f511"},
    {n:["lock","lock","security"],u:"1f512"},
    {n:["unlock","unlock","open"],u:"1f513"},
    {n:["bookmark","bookmark"],u:"1f516"},
    {n:["link","link","chain"],u:"1f517"},
    {n:["radio button","radio","button"],u:"1f518"},
    {n:["location pin","pin","location"],u:"1f4cd"},
    {n:["magnifying glass","search","find"],u:"1f50e"},
    {n:["microphone","mic","microphone"],u:"1f3a4"},
    {n:["movie camera","movie","camera"],u:"1f3ac"},
    {n:["telescope","telescope"],u:"1f52d"},
    {n:["syringe","syringe","medical"],u:"1f489"},
    {n:["pill","pill","medical"],u:"1f48a"},
    {n:["adhesive bandage","bandage","medical"],u:"1fa79"},
    {n:["crutch","crutch","medical"],u:"1fa7c"},
    {n:["stethoscope","stethoscope","medical"],u:"1fa7a"},
    {n:["door","door","entry"],u:"1f6aa"},
    {n:["elevator","elevator","lift"],u:"1f6d7"},

    // Flags
    {n:["chequered flag","flag","finish"],u:"1f3c1"},
    {n:["triangular flag","flag","triangle"],u:"1f6a9"},
    {n:["crossed flags","flag","crossed"],u:"1f38c"},
    {n:["black flag","flag","black"],u:"1f3f4"},
    {n:["white flag","flag","white"],u:"1f3f3"},
    {n:["rainbow flag","rainbow","lgbt"],u:"1f3f3"},
    {n:["transgender flag","transgender","lgbt"],u:"1f3f3"},
    {n:["pirate flag","pirate","flag"],u:"1f3f4"},
    {n:["flag in hole","flag","golf"],u:"26f3"},
    {n:["military medal","medal","military"],u:"1f396"},
    {n:["rosette","rosette","plant"],u:"1f3f5"},
    {n:["label","tag","label"],u:"1f3f7"},
    {n:["admission ticket","ticket","admission"],u:"1f39f"},
  ];

  var CATEGORIES = [
    { id: 'recent', label: 'Recently Used', icon: '🕐' },
    { id: 'smileys_people', label: 'Smileys & People', icon: '😀' },
    { id: 'animals_nature', label: 'Animals & Nature', icon: '🐾' },
    { id: 'food_drink', label: 'Food & Drink', icon: '🍔' },
    { id: 'activities', label: 'Activities', icon: '⚽' },
    { id: 'travel_places', label: 'Travel & Places', icon: '✈️' },
    { id: 'objects', label: 'Objects', icon: '💡' },
    { id: 'symbols', label: 'Symbols', icon: '❤️' },
    { id: 'flags', label: 'Flags', icon: '🏳️' },
  ];

  var SKIN_TONES = [
    { id: 'neutral', label: 'Neutral', code: '' },
    { id: 'light', label: 'Light', code: '1f3fb' },
    { id: 'medium_light', label: 'Medium Light', code: '1f3fc' },
    { id: 'medium', label: 'Medium', code: '1f3fd' },
    { id: 'medium_dark', label: 'Medium Dark', code: '1f3fe' },
    { id: 'dark', label: 'Dark', code: '1f3ff' },
  ];

  function getEmojiImageUrl(unicode) {
    return EMOJI_CDN_BASE + unicode + '.png';
  }

  function hexToEmoji(hex) {
    return String.fromCodePoint(parseInt(hex, 16));
  }

  function getEmojiDisplay(emoji) {
    return hexToEmoji(emoji.u);
  }

  function getEmojiVariants(emoji) {
    if (!emoji.v || emoji.v.length === 0) {
      return [{ unicode: emoji.u, display: hexToEmoji(emoji.u), image: getEmojiImageUrl(emoji.u) }];
    }
    var variants = [{ unicode: emoji.u, display: hexToEmoji(emoji.u), image: getEmojiImageUrl(emoji.u) }];
    for (var i = 0; i < emoji.v.length; i++) {
      variants.push({ unicode: emoji.v[i], display: hexToEmoji(emoji.v[i]), image: getEmojiImageUrl(emoji.v[i]) });
    }
    return variants;
  }

  function searchEmojis(query) {
    if (!query) return [];
    query = query.toLowerCase();
    var results = [];
    for (var i = 0; i < EMOJIS.length; i++) {
      var emoji = EMOJIS[i];
      for (var j = 0; j < emoji.n.length; j++) {
        if (emoji.n[j].toLowerCase().includes(query)) {
          results.push(emoji);
          break;
        }
      }
    }
    return results.slice(0, 50);
  }

  global.HelpinEmojiBundle = {
    emojis: EMOJIS,
    categories: CATEGORIES,
    skinTones: SKIN_TONES,
    getEmojiImageUrl: getEmojiImageUrl,
    hexToEmoji: hexToEmoji,
    getEmojiDisplay: getEmojiDisplay,
    getEmojiVariants: getEmojiVariants,
    searchEmojis: searchEmojis,
    cdnBase: EMOJI_CDN_BASE
  };
})(typeof window !== 'undefined' ? window : this);
