// Code generated by scripts/generate-commercial-event-catalog.go; DO NOT EDIT.
package eventcatalog

// ServerOnlyEventNames contains events rejected when presented with browser credentials.
var ServerOnlyEventNames = map[string]struct{}{
	"commercial_state_updated": {},
	"downgrade_requested":      {},
	"payment_failed":           {},
	"subscription_canceled":    {},
	"subscription_changed":     {},
	"subscription_renewed":     {},
	"workflow_failed":          {},
}

// ServerOnlyCompanyFields contains protected company payload fields.
var ServerOnlyCompanyFields = map[string]struct{}{
	"commercial_state": {},
}

// IsServerOnlyEvent reports whether an event requires a server credential.
func IsServerOnlyEvent(name string) bool { _, ok := ServerOnlyEventNames[name]; return ok }

// IsServerOnlyCompanyField reports whether a company field requires a server credential.
func IsServerOnlyCompanyField(name string) bool { _, ok := ServerOnlyCompanyFields[name]; return ok }
