apiVersion: batch/v1
kind: Job
metadata:
  name: helpin-clickhouse-migrate
  namespace: helpin
  labels:
    app: helpin-clickhouse-migrate
    env: stage
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 20
  template:
    metadata:
      labels:
        app: helpin-clickhouse-migrate
        env: stage
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-helpin-json-key
      containers:
        - name: migrate
          image: ghcr.io/helpin-ai/helpin/server-migrate:server-v0.95.433-rc.1
          command: ["./clickhouse-migrate", "up"]
          env:
            - name: CLICKHOUSE_MIGRATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: helpin-eventpipeline-secrets
                  key: CLICKHOUSE_MIGRATION_PASSWORD
            - name: CLICKHOUSE_DSN
              value: clickhouse://helpin_migration:$(CLICKHOUSE_MIGRATION_PASSWORD)@helpin-clickhouse.helpin.svc.cluster.local:9000/default
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
