/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SpaceSlugRouteImport } from './routes/$spaceSlug'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpaceSlugIndexRouteImport } from './routes/$spaceSlug/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as PreviewDocIdRouteImport } from './routes/preview.$docId'
import { Route as SpaceSlugArticleSlugRouteImport } from './routes/$spaceSlug/$articleSlug'
import { Route as LocaleSearchRouteImport } from './routes/$locale/search'
import { Route as LocaleSpaceSlugRouteImport } from './routes/$locale/$spaceSlug'
import { Route as LocaleSpaceSlugIndexRouteImport } from './routes/$locale/$spaceSlug/index'
import { Route as LocaleSpaceSlugCollectionSlugIndexRouteImport } from './routes/$locale/$spaceSlug/$collectionSlug/index'
import { Route as LocaleSpaceSlugCollectionSlugArticleSlugRouteImport } from './routes/$locale/$spaceSlug/$collectionSlug/$articleSlug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSlugRoute = SpaceSlugRouteImport.update({
  id: '/$spaceSlug',
  path: '/$spaceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSlugIndexRoute = SpaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpaceSlugRoute,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const PreviewDocIdRoute = PreviewDocIdRouteImport.update({
  id: '/preview/$docId',
  path: '/preview/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSlugArticleSlugRoute = SpaceSlugArticleSlugRouteImport.update({
  id: '/$articleSlug',
  path: '/$articleSlug',
  getParentRoute: () => SpaceSlugRoute,
} as any)
const LocaleSearchRoute = LocaleSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSpaceSlugRoute = LocaleSpaceSlugRouteImport.update({
  id: '/$spaceSlug',
  path: '/$spaceSlug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSpaceSlugIndexRoute = LocaleSpaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleSpaceSlugRoute,
} as any)
const LocaleSpaceSlugCollectionSlugIndexRoute =
  LocaleSpaceSlugCollectionSlugIndexRouteImport.update({
    id: '/$collectionSlug/',
    path: '/$collectionSlug/',
    getParentRoute: () => LocaleSpaceSlugRoute,
  } as any)
const LocaleSpaceSlugCollectionSlugArticleSlugRoute =
  LocaleSpaceSlugCollectionSlugArticleSlugRouteImport.update({
    id: '/$collectionSlug/$articleSlug',
    path: '/$collectionSlug/$articleSlug',
    getParentRoute: () => LocaleSpaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$spaceSlug': typeof SpaceSlugRouteWithChildren
  '/search': typeof SearchRoute
  '/$locale/$spaceSlug': typeof LocaleSpaceSlugRouteWithChildren
  '/$locale/search': typeof LocaleSearchRoute
  '/$spaceSlug/$articleSlug': typeof SpaceSlugArticleSlugRoute
  '/preview/$docId': typeof PreviewDocIdRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$spaceSlug/': typeof SpaceSlugIndexRoute
  '/$locale/$spaceSlug/': typeof LocaleSpaceSlugIndexRoute
  '/$locale/$spaceSlug/$collectionSlug/$articleSlug': typeof LocaleSpaceSlugCollectionSlugArticleSlugRoute
  '/$locale/$spaceSlug/$collectionSlug/': typeof LocaleSpaceSlugCollectionSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$spaceSlug/$articleSlug': typeof SpaceSlugArticleSlugRoute
  '/preview/$docId': typeof PreviewDocIdRoute
  '/$locale': typeof LocaleIndexRoute
  '/$spaceSlug': typeof SpaceSlugIndexRoute
  '/$locale/$spaceSlug': typeof LocaleSpaceSlugIndexRoute
  '/$locale/$spaceSlug/$collectionSlug/$articleSlug': typeof LocaleSpaceSlugCollectionSlugArticleSlugRoute
  '/$locale/$spaceSlug/$collectionSlug': typeof LocaleSpaceSlugCollectionSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$spaceSlug': typeof SpaceSlugRouteWithChildren
  '/search': typeof SearchRoute
  '/$locale/$spaceSlug': typeof LocaleSpaceSlugRouteWithChildren
  '/$locale/search': typeof LocaleSearchRoute
  '/$spaceSlug/$articleSlug': typeof SpaceSlugArticleSlugRoute
  '/preview/$docId': typeof PreviewDocIdRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$spaceSlug/': typeof SpaceSlugIndexRoute
  '/$locale/$spaceSlug/': typeof LocaleSpaceSlugIndexRoute
  '/$locale/$spaceSlug/$collectionSlug/$articleSlug': typeof LocaleSpaceSlugCollectionSlugArticleSlugRoute
  '/$locale/$spaceSlug/$collectionSlug/': typeof LocaleSpaceSlugCollectionSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$spaceSlug'
    | '/search'
    | '/$locale/$spaceSlug'
    | '/$locale/search'
    | '/$spaceSlug/$articleSlug'
    | '/preview/$docId'
    | '/$locale/'
    | '/$spaceSlug/'
    | '/$locale/$spaceSlug/'
    | '/$locale/$spaceSlug/$collectionSlug/$articleSlug'
    | '/$locale/$spaceSlug/$collectionSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/$locale/search'
    | '/$spaceSlug/$articleSlug'
    | '/preview/$docId'
    | '/$locale'
    | '/$spaceSlug'
    | '/$locale/$spaceSlug'
    | '/$locale/$spaceSlug/$collectionSlug/$articleSlug'
    | '/$locale/$spaceSlug/$collectionSlug'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$spaceSlug'
    | '/search'
    | '/$locale/$spaceSlug'
    | '/$locale/search'
    | '/$spaceSlug/$articleSlug'
    | '/preview/$docId'
    | '/$locale/'
    | '/$spaceSlug/'
    | '/$locale/$spaceSlug/'
    | '/$locale/$spaceSlug/$collectionSlug/$articleSlug'
    | '/$locale/$spaceSlug/$collectionSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  SpaceSlugRoute: typeof SpaceSlugRouteWithChildren
  SearchRoute: typeof SearchRoute
  PreviewDocIdRoute: typeof PreviewDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$spaceSlug': {
      id: '/$spaceSlug'
      path: '/$spaceSlug'
      fullPath: '/$spaceSlug'
      preLoaderRoute: typeof SpaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$spaceSlug/': {
      id: '/$spaceSlug/'
      path: '/'
      fullPath: '/$spaceSlug/'
      preLoaderRoute: typeof SpaceSlugIndexRouteImport
      parentRoute: typeof SpaceSlugRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/preview/$docId': {
      id: '/preview/$docId'
      path: '/preview/$docId'
      fullPath: '/preview/$docId'
      preLoaderRoute: typeof PreviewDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$spaceSlug/$articleSlug': {
      id: '/$spaceSlug/$articleSlug'
      path: '/$articleSlug'
      fullPath: '/$spaceSlug/$articleSlug'
      preLoaderRoute: typeof SpaceSlugArticleSlugRouteImport
      parentRoute: typeof SpaceSlugRoute
    }
    '/$locale/search': {
      id: '/$locale/search'
      path: '/search'
      fullPath: '/$locale/search'
      preLoaderRoute: typeof LocaleSearchRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/$spaceSlug': {
      id: '/$locale/$spaceSlug'
      path: '/$spaceSlug'
      fullPath: '/$locale/$spaceSlug'
      preLoaderRoute: typeof LocaleSpaceSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/$spaceSlug/': {
      id: '/$locale/$spaceSlug/'
      path: '/'
      fullPath: '/$locale/$spaceSlug/'
      preLoaderRoute: typeof LocaleSpaceSlugIndexRouteImport
      parentRoute: typeof LocaleSpaceSlugRoute
    }
    '/$locale/$spaceSlug/$collectionSlug/': {
      id: '/$locale/$spaceSlug/$collectionSlug/'
      path: '/$collectionSlug'
      fullPath: '/$locale/$spaceSlug/$collectionSlug/'
      preLoaderRoute: typeof LocaleSpaceSlugCollectionSlugIndexRouteImport
      parentRoute: typeof LocaleSpaceSlugRoute
    }
    '/$locale/$spaceSlug/$collectionSlug/$articleSlug': {
      id: '/$locale/$spaceSlug/$collectionSlug/$articleSlug'
      path: '/$collectionSlug/$articleSlug'
      fullPath: '/$locale/$spaceSlug/$collectionSlug/$articleSlug'
      preLoaderRoute: typeof LocaleSpaceSlugCollectionSlugArticleSlugRouteImport
      parentRoute: typeof LocaleSpaceSlugRoute
    }
  }
}

interface LocaleSpaceSlugRouteChildren {
  LocaleSpaceSlugIndexRoute: typeof LocaleSpaceSlugIndexRoute
  LocaleSpaceSlugCollectionSlugArticleSlugRoute: typeof LocaleSpaceSlugCollectionSlugArticleSlugRoute
  LocaleSpaceSlugCollectionSlugIndexRoute: typeof LocaleSpaceSlugCollectionSlugIndexRoute
}

const LocaleSpaceSlugRouteChildren: LocaleSpaceSlugRouteChildren = {
  LocaleSpaceSlugIndexRoute: LocaleSpaceSlugIndexRoute,
  LocaleSpaceSlugCollectionSlugArticleSlugRoute:
    LocaleSpaceSlugCollectionSlugArticleSlugRoute,
  LocaleSpaceSlugCollectionSlugIndexRoute:
    LocaleSpaceSlugCollectionSlugIndexRoute,
}

const LocaleSpaceSlugRouteWithChildren = LocaleSpaceSlugRoute._addFileChildren(
  LocaleSpaceSlugRouteChildren,
)

interface LocaleRouteChildren {
  LocaleSpaceSlugRoute: typeof LocaleSpaceSlugRouteWithChildren
  LocaleSearchRoute: typeof LocaleSearchRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleSpaceSlugRoute: LocaleSpaceSlugRouteWithChildren,
  LocaleSearchRoute: LocaleSearchRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface SpaceSlugRouteChildren {
  SpaceSlugArticleSlugRoute: typeof SpaceSlugArticleSlugRoute
  SpaceSlugIndexRoute: typeof SpaceSlugIndexRoute
}

const SpaceSlugRouteChildren: SpaceSlugRouteChildren = {
  SpaceSlugArticleSlugRoute: SpaceSlugArticleSlugRoute,
  SpaceSlugIndexRoute: SpaceSlugIndexRoute,
}

const SpaceSlugRouteWithChildren = SpaceSlugRoute._addFileChildren(
  SpaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  SpaceSlugRoute: SpaceSlugRouteWithChildren,
  SearchRoute: SearchRoute,
  PreviewDocIdRoute: PreviewDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
