/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionSlugIndexRouteImport } from './routes/$collectionSlug/index'
import { Route as ArticlesArticleSlugRouteImport } from './routes/articles/$articleSlug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugIndexRoute = CollectionSlugIndexRouteImport.update({
  id: '/$collectionSlug/',
  path: '/$collectionSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleSlugRoute = ArticlesArticleSlugRouteImport.update({
  id: '/articles/$articleSlug',
  path: '/articles/$articleSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/$collectionSlug/': typeof CollectionSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/$collectionSlug': typeof CollectionSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/$collectionSlug/': typeof CollectionSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/articles/$articleSlug' | '/$collectionSlug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/articles/$articleSlug' | '/$collectionSlug'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/articles/$articleSlug'
    | '/$collectionSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  ArticlesArticleSlugRoute: typeof ArticlesArticleSlugRoute
  CollectionSlugIndexRoute: typeof CollectionSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$collectionSlug/': {
      id: '/$collectionSlug/'
      path: '/$collectionSlug'
      fullPath: '/$collectionSlug/'
      preLoaderRoute: typeof CollectionSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleSlug': {
      id: '/articles/$articleSlug'
      path: '/articles/$articleSlug'
      fullPath: '/articles/$articleSlug'
      preLoaderRoute: typeof ArticlesArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  ArticlesArticleSlugRoute: ArticlesArticleSlugRoute,
  CollectionSlugIndexRoute: CollectionSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
