apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: helpin-staging-doppler
  namespace: helpin
spec:
  tokenSecret:
    name: doppler-token-helpin
  managedSecret:
    name: helpin-secrets
    namespace: helpin
