import { test, expect } from '@playwright/test';
for (const mode of ['light', 'dark', 'narrow']) test(`AI profile progressive disclosure ${mode}`, async ({ page }) => {
  if (mode === 'narrow') await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`/e2e/crm/harness/ai-profile.html${mode === 'dark' ? '?dark' : ''}`);
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByLabel('Profile name', { exact: true })).toBeFocused();
  await expect(page.getByRole('tooltip')).toHaveCount(0);
  await dialog.getByLabel('Profile name', { exact: true }).fill('Everyday tasks');
  await dialog.getByRole('combobox', { name: 'Connection', exact: true }).click();
  await page.getByRole('option', { name: 'My OpenAI', exact: true }).click();
  await expect(dialog.getByLabel('Reasoning effort', { exact: true })).toBeHidden();
  await dialog.locator('summary').click();
  await dialog.getByLabel('Reasoning effort', { exact: true }).click();
  await page.getByRole('option', { name: 'high', exact: true }).click();
  await dialog.locator('summary').click();
  await expect(dialog.locator('summary')).toContainText('Customized');
  await dialog.locator('summary').click();
  await expect(dialog.getByLabel('Reasoning effort', { exact: true })).toHaveText('high');
  await dialog.locator('summary').click();
  await dialog.getByRole('button', { name: 'About fallback', exact: true }).focus();
  await expect(page.getByRole('tooltip', { name: /Optional. Uses a different connection/ })).toBeVisible();
  await page.keyboard.press('Escape');
  await dialog.getByLabel('Profile name', { exact: true }).focus();
  await expect(page.getByRole('tooltip')).toHaveCount(0);
  await page.screenshot({ path: `/tmp/ai-profile-${mode}.png`, fullPage: true });
  await dialog.getByRole('button', { name: 'Add fallback', exact: true }).click();
  await expect(dialog.getByRole('heading', { name: 'Fallback model' })).toBeVisible();
  await dialog.getByRole('button', { name: 'Remove fallback', exact: true }).click();
  await expect(dialog.getByRole('heading', { name: 'Fallback model' })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
