import { test, expect } from '@playwright/test';
for (const mode of ['light', 'dark', 'narrow']) test(`notification preferences ${mode}`, async ({ page }) => {
  if (mode === 'narrow') await page.setViewportSize({ width: 390, height: 844 });
  let account = { user_id: 'me', email_enabled: true, email_digest_frequency: 'daily', email_digest_time: '09:00', email_digest_day: 1, timezone: 'Asia/Karachi', do_not_disturb: false, dnd_until: null, badge_mode: 'all' };
  let workspace = { workspace_id: 'ws-settings', user_id: 'me', mute_workspace: false, channel_preferences: { comments: { in_app: false, email: true } } };
  await page.route('**/api/user/notification-settings*', async route => {
    if (route.request().method() === 'PUT') account = { ...account, ...route.request().postDataJSON() };
    await route.fulfill({ json: account });
  });
  await page.route('**/api/notifications/preferences?*', async route => {
    if (route.request().method() === 'PUT') workspace = { ...workspace, ...route.request().postDataJSON() };
    await route.fulfill({ json: workspace });
  });
  await page.route('**/api/workspaces/ws-settings/me', route => route.fulfill({ json: { modules: ['pm', 'docs', 'support', 'crm'], permissions: ['settings.read'], membership: { role: 'member' }, team_memberships: [] } }));
  await page.goto(`/e2e/crm/harness/notification-settings.html${mode === 'dark' ? '?dark' : ''}`);
  await expect(page.getByRole('switch', { name: 'Email notifications', exact: true })).toBeChecked();
  await expect(page.getByRole('tab', { name: 'Account', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(page.getByRole('heading', { name: 'Projects & docs', exact: true })).toBeHidden();
  await expect(page.getByText('Pause in-app and email updates across all workspaces.', { exact: true })).toHaveCount(0);
  await expect(page.getByLabel('Unread notification count', { exact: true })).toBeVisible();
  await expect(page.getByText('Choose what counts toward the number on the notification bell.', { exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'About unread notification count', exact: true }).focus();
  await expect(page.getByRole('tooltip')).toContainText('number on the notification bell');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('tooltip')).toHaveCount(0);
  await expect(page.getByRole('combobox', { name: 'Timezone', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'About delivery time', exact: true }).focus();
  await expect(page.getByRole('tooltip')).toContainText('Asia/Karachi');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('tooltip')).toHaveCount(0);
  await page.getByRole('tab', { name: 'Workspace', exact: true }).click();
  await expect(page.getByRole('switch', { name: 'Email notifications', exact: true })).toBeHidden();
  await expect(page.getByRole('heading', { name: 'Projects & docs', exact: true })).toBeVisible();
  await page.screenshot({ path: `/tmp/notification-settings-${mode}-sections.png`, fullPage: true });
  await expect(page.getByRole('switch', { name: 'Comments and replies: in-app', exact: true })).toBeHidden();
  await page.getByRole('heading', { name: 'Projects & docs', exact: true }).click();
  await expect(page.getByRole('switch', { name: 'Comments and replies: in-app', exact: true })).not.toBeChecked();
  await expect(page.getByLabel('Delivery day', { exact: true })).toHaveCount(0);
  await page.screenshot({ path: `/tmp/notification-settings-${mode}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('tab', { name: 'Account', exact: true }).click();
  await page.getByRole('button', { name: 'About email frequency', exact: true }).focus();
  await expect(page.getByRole('tooltip')).toContainText('five per hour');
  await page.keyboard.press('Tab');
  await expect(page.getByRole('tooltip')).toHaveCount(0);
  await page.getByRole('tab', { name: 'Workspace', exact: true }).click();
  await page.getByRole('heading', { name: 'Support inbox', exact: true }).click();
  await page.getByRole('button', { name: 'About customer replies', exact: true }).focus();
  await expect(page.getByRole('tooltip')).toContainText('after 3 minutes');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('tooltip')).toHaveCount(0);
  await page.getByRole('tab', { name: 'Account', exact: true }).click();
  await page.getByLabel('Email frequency', { exact: true }).click();
  await page.getByRole('option', { name: 'Weekly digest', exact: true }).click();
  await expect(page.getByLabel('Delivery day', { exact: true })).toBeVisible();
  await page.getByLabel('Delivery day', { exact: true }).click();
  await page.getByRole('option', { name: 'Friday', exact: true }).click();
  await expect.poll(() => account.email_digest_day).toBe(5);
  expect(account.timezone).toBe('Asia/Karachi');
  await page.getByRole('switch', { name: 'Email notifications', exact: true }).click();
  await expect(page.getByLabel('Email frequency', { exact: true })).toHaveCount(0);
  await page.getByRole('tab', { name: 'Workspace', exact: true }).click();
  await expect(page.getByRole('status')).toHaveCount(1);
  await expect(page.getByRole('status')).toContainText('Email notifications are off');
  await page.getByRole('switch', { name: 'Mute this workspace', exact: true }).click();
  await expect(page.getByRole('status')).toHaveCount(1);
  await expect(page.getByRole('status')).toContainText('This workspace is muted');
  await page.getByRole('switch', { name: 'Assignments: email', exact: true }).click();
  await expect(page.getByRole('switch', { name: 'Assignments: email', exact: true })).not.toBeChecked();
  expect(workspace.channel_preferences.comments).toEqual({ in_app: false, email: true });
  await page.getByRole('tab', { name: 'Account', exact: true }).click();
  await page.getByRole('switch', { name: 'Pause all notifications', exact: true }).click();
  await page.getByRole('tab', { name: 'Workspace', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('All notifications are paused');
});

test('module access controls visible categories without resetting preferences', async ({ page }) => {
  let modules = ['pm', 'docs'];
  await page.route('**/api/workspaces/ws-settings/me', route => route.fulfill({ json: { modules, permissions: [], membership: { role: 'member' }, team_memberships: [] } }));
  await page.route('**/api/user/notification-settings*', route => route.fulfill({ json: { email_enabled: true, timezone: 'UTC', email_digest_frequency: 'daily' } }));
  await page.route('**/api/notifications/preferences?*', route => route.fulfill({ json: { mute_workspace: false, channel_preferences: { support_replies: { email: false } } } }));
  await page.goto('/e2e/crm/harness/notification-settings.html');
  await page.getByRole('tab', { name: 'Workspace', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Projects & docs' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Support inbox', exact: true })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'CRM', exact: true })).toHaveCount(0);
  modules = ['pm', 'docs', 'support', 'crm'];
  await page.reload();
  await page.getByRole('tab', { name: 'Workspace', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Support inbox', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'CRM', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Workspace', exact: true }).click();
  await page.getByRole('heading', { name: 'Support inbox', exact: true }).click();
  await expect(page.getByRole('switch', { name: 'Customer replies: email', exact: true })).not.toBeChecked();
});
