/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWSlugRouteImport } from './routes/_authenticated/w/$slug'
import { Route as AuthenticatedWSlugIndexRouteImport } from './routes/_authenticated/w/$slug/index'
import { Route as AuthenticatedWSlugTeamGoalsRouteImport } from './routes/_authenticated/w/$slug/team-goals'
import { Route as AuthenticatedWSlugTasksRouteImport } from './routes/_authenticated/w/$slug/tasks'
import { Route as AuthenticatedWSlugMyQuarterRouteImport } from './routes/_authenticated/w/$slug/my-quarter'
import { Route as AuthenticatedWSlugGoalsRouteImport } from './routes/_authenticated/w/$slug/goals'
import { Route as AuthenticatedWSlugDocsRouteImport } from './routes/_authenticated/w/$slug/docs'
import { Route as AuthenticatedWSlugDashboardRouteImport } from './routes/_authenticated/w/$slug/dashboard'
import { Route as AuthenticatedWSlugBonusRouteImport } from './routes/_authenticated/w/$slug/bonus'
import { Route as AuthenticatedWSlugSprintsIndexRouteImport } from './routes/_authenticated/w/$slug/sprints/index'
import { Route as AuthenticatedWSlugSettingsIndexRouteImport } from './routes/_authenticated/w/$slug/settings/index'
import { Route as AuthenticatedWSlugPmIndexRouteImport } from './routes/_authenticated/w/$slug/pm/index'
import { Route as AuthenticatedWSlugSprintsSprintIdRouteImport } from './routes/_authenticated/w/$slug/sprints/$sprintId'
import { Route as AuthenticatedWSlugSettingsSectionRouteImport } from './routes/_authenticated/w/$slug/settings/$section'
import { Route as AuthenticatedWSlugPmStoriesRouteImport } from './routes/_authenticated/w/$slug/pm/stories'
import { Route as AuthenticatedWSlugPmRoadmapRouteImport } from './routes/_authenticated/w/$slug/pm/roadmap'
import { Route as AuthenticatedWSlugPmReportsRouteImport } from './routes/_authenticated/w/$slug/pm/reports'
import { Route as AuthenticatedWSlugPmObjectivesRouteImport } from './routes/_authenticated/w/$slug/pm/objectives'
import { Route as AuthenticatedWSlugPmIterationsIndexRouteImport } from './routes/_authenticated/w/$slug/pm/iterations/index'
import { Route as AuthenticatedWSlugPmEpicsIndexRouteImport } from './routes/_authenticated/w/$slug/pm/epics/index'
import { Route as AuthenticatedWSlugPmIterationsIterationIdRouteImport } from './routes/_authenticated/w/$slug/pm/iterations/$iterationId'
import { Route as AuthenticatedWSlugPmEpicsEpicIdRouteImport } from './routes/_authenticated/w/$slug/pm/epics/$epicId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWSlugRoute = AuthenticatedWSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWSlugIndexRoute = AuthenticatedWSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedWSlugRoute,
} as any)
const AuthenticatedWSlugTeamGoalsRoute =
  AuthenticatedWSlugTeamGoalsRouteImport.update({
    id: '/team-goals',
    path: '/team-goals',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugTasksRoute = AuthenticatedWSlugTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedWSlugRoute,
} as any)
const AuthenticatedWSlugMyQuarterRoute =
  AuthenticatedWSlugMyQuarterRouteImport.update({
    id: '/my-quarter',
    path: '/my-quarter',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugGoalsRoute = AuthenticatedWSlugGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedWSlugRoute,
} as any)
const AuthenticatedWSlugDocsRoute = AuthenticatedWSlugDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedWSlugRoute,
} as any)
const AuthenticatedWSlugDashboardRoute =
  AuthenticatedWSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugBonusRoute = AuthenticatedWSlugBonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => AuthenticatedWSlugRoute,
} as any)
const AuthenticatedWSlugSprintsIndexRoute =
  AuthenticatedWSlugSprintsIndexRouteImport.update({
    id: '/sprints/',
    path: '/sprints/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsIndexRoute =
  AuthenticatedWSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmIndexRoute =
  AuthenticatedWSlugPmIndexRouteImport.update({
    id: '/pm/',
    path: '/pm/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSprintsSprintIdRoute =
  AuthenticatedWSlugSprintsSprintIdRouteImport.update({
    id: '/sprints/$sprintId',
    path: '/sprints/$sprintId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsSectionRoute =
  AuthenticatedWSlugSettingsSectionRouteImport.update({
    id: '/settings/$section',
    path: '/settings/$section',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmStoriesRoute =
  AuthenticatedWSlugPmStoriesRouteImport.update({
    id: '/pm/stories',
    path: '/pm/stories',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmRoadmapRoute =
  AuthenticatedWSlugPmRoadmapRouteImport.update({
    id: '/pm/roadmap',
    path: '/pm/roadmap',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmReportsRoute =
  AuthenticatedWSlugPmReportsRouteImport.update({
    id: '/pm/reports',
    path: '/pm/reports',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmObjectivesRoute =
  AuthenticatedWSlugPmObjectivesRouteImport.update({
    id: '/pm/objectives',
    path: '/pm/objectives',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmIterationsIndexRoute =
  AuthenticatedWSlugPmIterationsIndexRouteImport.update({
    id: '/pm/iterations/',
    path: '/pm/iterations/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmEpicsIndexRoute =
  AuthenticatedWSlugPmEpicsIndexRouteImport.update({
    id: '/pm/epics/',
    path: '/pm/epics/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmIterationsIterationIdRoute =
  AuthenticatedWSlugPmIterationsIterationIdRouteImport.update({
    id: '/pm/iterations/$iterationId',
    path: '/pm/iterations/$iterationId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmEpicsEpicIdRoute =
  AuthenticatedWSlugPmEpicsEpicIdRouteImport.update({
    id: '/pm/epics/$epicId',
    path: '/pm/epics/$epicId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/w/$slug': typeof AuthenticatedWSlugRouteWithChildren
  '/w/$slug/bonus': typeof AuthenticatedWSlugBonusRoute
  '/w/$slug/dashboard': typeof AuthenticatedWSlugDashboardRoute
  '/w/$slug/docs': typeof AuthenticatedWSlugDocsRoute
  '/w/$slug/goals': typeof AuthenticatedWSlugGoalsRoute
  '/w/$slug/my-quarter': typeof AuthenticatedWSlugMyQuarterRoute
  '/w/$slug/tasks': typeof AuthenticatedWSlugTasksRoute
  '/w/$slug/team-goals': typeof AuthenticatedWSlugTeamGoalsRoute
  '/w/$slug/': typeof AuthenticatedWSlugIndexRoute
  '/w/$slug/pm/objectives': typeof AuthenticatedWSlugPmObjectivesRoute
  '/w/$slug/pm/reports': typeof AuthenticatedWSlugPmReportsRoute
  '/w/$slug/pm/roadmap': typeof AuthenticatedWSlugPmRoadmapRoute
  '/w/$slug/pm/stories': typeof AuthenticatedWSlugPmStoriesRoute
  '/w/$slug/settings/$section': typeof AuthenticatedWSlugSettingsSectionRoute
  '/w/$slug/sprints/$sprintId': typeof AuthenticatedWSlugSprintsSprintIdRoute
  '/w/$slug/pm/': typeof AuthenticatedWSlugPmIndexRoute
  '/w/$slug/settings/': typeof AuthenticatedWSlugSettingsIndexRoute
  '/w/$slug/sprints/': typeof AuthenticatedWSlugSprintsIndexRoute
  '/w/$slug/pm/epics/$epicId': typeof AuthenticatedWSlugPmEpicsEpicIdRoute
  '/w/$slug/pm/iterations/$iterationId': typeof AuthenticatedWSlugPmIterationsIterationIdRoute
  '/w/$slug/pm/epics/': typeof AuthenticatedWSlugPmEpicsIndexRoute
  '/w/$slug/pm/iterations/': typeof AuthenticatedWSlugPmIterationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/w/$slug/bonus': typeof AuthenticatedWSlugBonusRoute
  '/w/$slug/dashboard': typeof AuthenticatedWSlugDashboardRoute
  '/w/$slug/docs': typeof AuthenticatedWSlugDocsRoute
  '/w/$slug/goals': typeof AuthenticatedWSlugGoalsRoute
  '/w/$slug/my-quarter': typeof AuthenticatedWSlugMyQuarterRoute
  '/w/$slug/tasks': typeof AuthenticatedWSlugTasksRoute
  '/w/$slug/team-goals': typeof AuthenticatedWSlugTeamGoalsRoute
  '/w/$slug': typeof AuthenticatedWSlugIndexRoute
  '/w/$slug/pm/objectives': typeof AuthenticatedWSlugPmObjectivesRoute
  '/w/$slug/pm/reports': typeof AuthenticatedWSlugPmReportsRoute
  '/w/$slug/pm/roadmap': typeof AuthenticatedWSlugPmRoadmapRoute
  '/w/$slug/pm/stories': typeof AuthenticatedWSlugPmStoriesRoute
  '/w/$slug/settings/$section': typeof AuthenticatedWSlugSettingsSectionRoute
  '/w/$slug/sprints/$sprintId': typeof AuthenticatedWSlugSprintsSprintIdRoute
  '/w/$slug/pm': typeof AuthenticatedWSlugPmIndexRoute
  '/w/$slug/settings': typeof AuthenticatedWSlugSettingsIndexRoute
  '/w/$slug/sprints': typeof AuthenticatedWSlugSprintsIndexRoute
  '/w/$slug/pm/epics/$epicId': typeof AuthenticatedWSlugPmEpicsEpicIdRoute
  '/w/$slug/pm/iterations/$iterationId': typeof AuthenticatedWSlugPmIterationsIterationIdRoute
  '/w/$slug/pm/epics': typeof AuthenticatedWSlugPmEpicsIndexRoute
  '/w/$slug/pm/iterations': typeof AuthenticatedWSlugPmIterationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/_authenticated/w/$slug': typeof AuthenticatedWSlugRouteWithChildren
  '/_authenticated/w/$slug/bonus': typeof AuthenticatedWSlugBonusRoute
  '/_authenticated/w/$slug/dashboard': typeof AuthenticatedWSlugDashboardRoute
  '/_authenticated/w/$slug/docs': typeof AuthenticatedWSlugDocsRoute
  '/_authenticated/w/$slug/goals': typeof AuthenticatedWSlugGoalsRoute
  '/_authenticated/w/$slug/my-quarter': typeof AuthenticatedWSlugMyQuarterRoute
  '/_authenticated/w/$slug/tasks': typeof AuthenticatedWSlugTasksRoute
  '/_authenticated/w/$slug/team-goals': typeof AuthenticatedWSlugTeamGoalsRoute
  '/_authenticated/w/$slug/': typeof AuthenticatedWSlugIndexRoute
  '/_authenticated/w/$slug/pm/objectives': typeof AuthenticatedWSlugPmObjectivesRoute
  '/_authenticated/w/$slug/pm/reports': typeof AuthenticatedWSlugPmReportsRoute
  '/_authenticated/w/$slug/pm/roadmap': typeof AuthenticatedWSlugPmRoadmapRoute
  '/_authenticated/w/$slug/pm/stories': typeof AuthenticatedWSlugPmStoriesRoute
  '/_authenticated/w/$slug/settings/$section': typeof AuthenticatedWSlugSettingsSectionRoute
  '/_authenticated/w/$slug/sprints/$sprintId': typeof AuthenticatedWSlugSprintsSprintIdRoute
  '/_authenticated/w/$slug/pm/': typeof AuthenticatedWSlugPmIndexRoute
  '/_authenticated/w/$slug/settings/': typeof AuthenticatedWSlugSettingsIndexRoute
  '/_authenticated/w/$slug/sprints/': typeof AuthenticatedWSlugSprintsIndexRoute
  '/_authenticated/w/$slug/pm/epics/$epicId': typeof AuthenticatedWSlugPmEpicsEpicIdRoute
  '/_authenticated/w/$slug/pm/iterations/$iterationId': typeof AuthenticatedWSlugPmIterationsIterationIdRoute
  '/_authenticated/w/$slug/pm/epics/': typeof AuthenticatedWSlugPmEpicsIndexRoute
  '/_authenticated/w/$slug/pm/iterations/': typeof AuthenticatedWSlugPmIterationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/profile'
    | '/workspaces'
    | '/w/$slug'
    | '/w/$slug/bonus'
    | '/w/$slug/dashboard'
    | '/w/$slug/docs'
    | '/w/$slug/goals'
    | '/w/$slug/my-quarter'
    | '/w/$slug/tasks'
    | '/w/$slug/team-goals'
    | '/w/$slug/'
    | '/w/$slug/pm/objectives'
    | '/w/$slug/pm/reports'
    | '/w/$slug/pm/roadmap'
    | '/w/$slug/pm/stories'
    | '/w/$slug/settings/$section'
    | '/w/$slug/sprints/$sprintId'
    | '/w/$slug/pm/'
    | '/w/$slug/settings/'
    | '/w/$slug/sprints/'
    | '/w/$slug/pm/epics/$epicId'
    | '/w/$slug/pm/iterations/$iterationId'
    | '/w/$slug/pm/epics/'
    | '/w/$slug/pm/iterations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/profile'
    | '/workspaces'
    | '/w/$slug/bonus'
    | '/w/$slug/dashboard'
    | '/w/$slug/docs'
    | '/w/$slug/goals'
    | '/w/$slug/my-quarter'
    | '/w/$slug/tasks'
    | '/w/$slug/team-goals'
    | '/w/$slug'
    | '/w/$slug/pm/objectives'
    | '/w/$slug/pm/reports'
    | '/w/$slug/pm/roadmap'
    | '/w/$slug/pm/stories'
    | '/w/$slug/settings/$section'
    | '/w/$slug/sprints/$sprintId'
    | '/w/$slug/pm'
    | '/w/$slug/settings'
    | '/w/$slug/sprints'
    | '/w/$slug/pm/epics/$epicId'
    | '/w/$slug/pm/iterations/$iterationId'
    | '/w/$slug/pm/epics'
    | '/w/$slug/pm/iterations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/profile'
    | '/_authenticated/workspaces'
    | '/_authenticated/w/$slug'
    | '/_authenticated/w/$slug/bonus'
    | '/_authenticated/w/$slug/dashboard'
    | '/_authenticated/w/$slug/docs'
    | '/_authenticated/w/$slug/goals'
    | '/_authenticated/w/$slug/my-quarter'
    | '/_authenticated/w/$slug/tasks'
    | '/_authenticated/w/$slug/team-goals'
    | '/_authenticated/w/$slug/'
    | '/_authenticated/w/$slug/pm/objectives'
    | '/_authenticated/w/$slug/pm/reports'
    | '/_authenticated/w/$slug/pm/roadmap'
    | '/_authenticated/w/$slug/pm/stories'
    | '/_authenticated/w/$slug/settings/$section'
    | '/_authenticated/w/$slug/sprints/$sprintId'
    | '/_authenticated/w/$slug/pm/'
    | '/_authenticated/w/$slug/settings/'
    | '/_authenticated/w/$slug/sprints/'
    | '/_authenticated/w/$slug/pm/epics/$epicId'
    | '/_authenticated/w/$slug/pm/iterations/$iterationId'
    | '/_authenticated/w/$slug/pm/epics/'
    | '/_authenticated/w/$slug/pm/iterations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$slug': {
      id: '/_authenticated/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof AuthenticatedWSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$slug/': {
      id: '/_authenticated/w/$slug/'
      path: '/'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof AuthenticatedWSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/team-goals': {
      id: '/_authenticated/w/$slug/team-goals'
      path: '/team-goals'
      fullPath: '/w/$slug/team-goals'
      preLoaderRoute: typeof AuthenticatedWSlugTeamGoalsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/tasks': {
      id: '/_authenticated/w/$slug/tasks'
      path: '/tasks'
      fullPath: '/w/$slug/tasks'
      preLoaderRoute: typeof AuthenticatedWSlugTasksRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/my-quarter': {
      id: '/_authenticated/w/$slug/my-quarter'
      path: '/my-quarter'
      fullPath: '/w/$slug/my-quarter'
      preLoaderRoute: typeof AuthenticatedWSlugMyQuarterRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/goals': {
      id: '/_authenticated/w/$slug/goals'
      path: '/goals'
      fullPath: '/w/$slug/goals'
      preLoaderRoute: typeof AuthenticatedWSlugGoalsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/docs': {
      id: '/_authenticated/w/$slug/docs'
      path: '/docs'
      fullPath: '/w/$slug/docs'
      preLoaderRoute: typeof AuthenticatedWSlugDocsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/dashboard': {
      id: '/_authenticated/w/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/w/$slug/dashboard'
      preLoaderRoute: typeof AuthenticatedWSlugDashboardRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/bonus': {
      id: '/_authenticated/w/$slug/bonus'
      path: '/bonus'
      fullPath: '/w/$slug/bonus'
      preLoaderRoute: typeof AuthenticatedWSlugBonusRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/sprints/': {
      id: '/_authenticated/w/$slug/sprints/'
      path: '/sprints'
      fullPath: '/w/$slug/sprints/'
      preLoaderRoute: typeof AuthenticatedWSlugSprintsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/': {
      id: '/_authenticated/w/$slug/settings/'
      path: '/settings'
      fullPath: '/w/$slug/settings/'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/': {
      id: '/_authenticated/w/$slug/pm/'
      path: '/pm'
      fullPath: '/w/$slug/pm/'
      preLoaderRoute: typeof AuthenticatedWSlugPmIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/sprints/$sprintId': {
      id: '/_authenticated/w/$slug/sprints/$sprintId'
      path: '/sprints/$sprintId'
      fullPath: '/w/$slug/sprints/$sprintId'
      preLoaderRoute: typeof AuthenticatedWSlugSprintsSprintIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/$section': {
      id: '/_authenticated/w/$slug/settings/$section'
      path: '/settings/$section'
      fullPath: '/w/$slug/settings/$section'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsSectionRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/stories': {
      id: '/_authenticated/w/$slug/pm/stories'
      path: '/pm/stories'
      fullPath: '/w/$slug/pm/stories'
      preLoaderRoute: typeof AuthenticatedWSlugPmStoriesRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/roadmap': {
      id: '/_authenticated/w/$slug/pm/roadmap'
      path: '/pm/roadmap'
      fullPath: '/w/$slug/pm/roadmap'
      preLoaderRoute: typeof AuthenticatedWSlugPmRoadmapRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/reports': {
      id: '/_authenticated/w/$slug/pm/reports'
      path: '/pm/reports'
      fullPath: '/w/$slug/pm/reports'
      preLoaderRoute: typeof AuthenticatedWSlugPmReportsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/objectives': {
      id: '/_authenticated/w/$slug/pm/objectives'
      path: '/pm/objectives'
      fullPath: '/w/$slug/pm/objectives'
      preLoaderRoute: typeof AuthenticatedWSlugPmObjectivesRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/iterations/': {
      id: '/_authenticated/w/$slug/pm/iterations/'
      path: '/pm/iterations'
      fullPath: '/w/$slug/pm/iterations/'
      preLoaderRoute: typeof AuthenticatedWSlugPmIterationsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/epics/': {
      id: '/_authenticated/w/$slug/pm/epics/'
      path: '/pm/epics'
      fullPath: '/w/$slug/pm/epics/'
      preLoaderRoute: typeof AuthenticatedWSlugPmEpicsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/iterations/$iterationId': {
      id: '/_authenticated/w/$slug/pm/iterations/$iterationId'
      path: '/pm/iterations/$iterationId'
      fullPath: '/w/$slug/pm/iterations/$iterationId'
      preLoaderRoute: typeof AuthenticatedWSlugPmIterationsIterationIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/epics/$epicId': {
      id: '/_authenticated/w/$slug/pm/epics/$epicId'
      path: '/pm/epics/$epicId'
      fullPath: '/w/$slug/pm/epics/$epicId'
      preLoaderRoute: typeof AuthenticatedWSlugPmEpicsEpicIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
  }
}

interface AuthenticatedWSlugRouteChildren {
  AuthenticatedWSlugBonusRoute: typeof AuthenticatedWSlugBonusRoute
  AuthenticatedWSlugDashboardRoute: typeof AuthenticatedWSlugDashboardRoute
  AuthenticatedWSlugDocsRoute: typeof AuthenticatedWSlugDocsRoute
  AuthenticatedWSlugGoalsRoute: typeof AuthenticatedWSlugGoalsRoute
  AuthenticatedWSlugMyQuarterRoute: typeof AuthenticatedWSlugMyQuarterRoute
  AuthenticatedWSlugTasksRoute: typeof AuthenticatedWSlugTasksRoute
  AuthenticatedWSlugTeamGoalsRoute: typeof AuthenticatedWSlugTeamGoalsRoute
  AuthenticatedWSlugIndexRoute: typeof AuthenticatedWSlugIndexRoute
  AuthenticatedWSlugPmObjectivesRoute: typeof AuthenticatedWSlugPmObjectivesRoute
  AuthenticatedWSlugPmReportsRoute: typeof AuthenticatedWSlugPmReportsRoute
  AuthenticatedWSlugPmRoadmapRoute: typeof AuthenticatedWSlugPmRoadmapRoute
  AuthenticatedWSlugPmStoriesRoute: typeof AuthenticatedWSlugPmStoriesRoute
  AuthenticatedWSlugSettingsSectionRoute: typeof AuthenticatedWSlugSettingsSectionRoute
  AuthenticatedWSlugSprintsSprintIdRoute: typeof AuthenticatedWSlugSprintsSprintIdRoute
  AuthenticatedWSlugPmIndexRoute: typeof AuthenticatedWSlugPmIndexRoute
  AuthenticatedWSlugSettingsIndexRoute: typeof AuthenticatedWSlugSettingsIndexRoute
  AuthenticatedWSlugSprintsIndexRoute: typeof AuthenticatedWSlugSprintsIndexRoute
  AuthenticatedWSlugPmEpicsEpicIdRoute: typeof AuthenticatedWSlugPmEpicsEpicIdRoute
  AuthenticatedWSlugPmIterationsIterationIdRoute: typeof AuthenticatedWSlugPmIterationsIterationIdRoute
  AuthenticatedWSlugPmEpicsIndexRoute: typeof AuthenticatedWSlugPmEpicsIndexRoute
  AuthenticatedWSlugPmIterationsIndexRoute: typeof AuthenticatedWSlugPmIterationsIndexRoute
}

const AuthenticatedWSlugRouteChildren: AuthenticatedWSlugRouteChildren = {
  AuthenticatedWSlugBonusRoute: AuthenticatedWSlugBonusRoute,
  AuthenticatedWSlugDashboardRoute: AuthenticatedWSlugDashboardRoute,
  AuthenticatedWSlugDocsRoute: AuthenticatedWSlugDocsRoute,
  AuthenticatedWSlugGoalsRoute: AuthenticatedWSlugGoalsRoute,
  AuthenticatedWSlugMyQuarterRoute: AuthenticatedWSlugMyQuarterRoute,
  AuthenticatedWSlugTasksRoute: AuthenticatedWSlugTasksRoute,
  AuthenticatedWSlugTeamGoalsRoute: AuthenticatedWSlugTeamGoalsRoute,
  AuthenticatedWSlugIndexRoute: AuthenticatedWSlugIndexRoute,
  AuthenticatedWSlugPmObjectivesRoute: AuthenticatedWSlugPmObjectivesRoute,
  AuthenticatedWSlugPmReportsRoute: AuthenticatedWSlugPmReportsRoute,
  AuthenticatedWSlugPmRoadmapRoute: AuthenticatedWSlugPmRoadmapRoute,
  AuthenticatedWSlugPmStoriesRoute: AuthenticatedWSlugPmStoriesRoute,
  AuthenticatedWSlugSettingsSectionRoute:
    AuthenticatedWSlugSettingsSectionRoute,
  AuthenticatedWSlugSprintsSprintIdRoute:
    AuthenticatedWSlugSprintsSprintIdRoute,
  AuthenticatedWSlugPmIndexRoute: AuthenticatedWSlugPmIndexRoute,
  AuthenticatedWSlugSettingsIndexRoute: AuthenticatedWSlugSettingsIndexRoute,
  AuthenticatedWSlugSprintsIndexRoute: AuthenticatedWSlugSprintsIndexRoute,
  AuthenticatedWSlugPmEpicsEpicIdRoute: AuthenticatedWSlugPmEpicsEpicIdRoute,
  AuthenticatedWSlugPmIterationsIterationIdRoute:
    AuthenticatedWSlugPmIterationsIterationIdRoute,
  AuthenticatedWSlugPmEpicsIndexRoute: AuthenticatedWSlugPmEpicsIndexRoute,
  AuthenticatedWSlugPmIterationsIndexRoute:
    AuthenticatedWSlugPmIterationsIndexRoute,
}

const AuthenticatedWSlugRouteWithChildren =
  AuthenticatedWSlugRoute._addFileChildren(AuthenticatedWSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedWSlugRoute: typeof AuthenticatedWSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedWSlugRoute: AuthenticatedWSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
