/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareShareTokenRouteImport } from './routes/share/$shareToken'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWSlugRouteImport } from './routes/_authenticated/w/$slug'
import { Route as AuthenticatedWSlugIndexRouteImport } from './routes/_authenticated/w/$slug/index'
import { Route as AuthenticatedWSlugTeamGoalsRouteImport } from './routes/_authenticated/w/$slug/team-goals'
import { Route as AuthenticatedWSlugTasksRouteImport } from './routes/_authenticated/w/$slug/tasks'
import { Route as AuthenticatedWSlugNotificationsRouteImport } from './routes/_authenticated/w/$slug/notifications'
import { Route as AuthenticatedWSlugDocsRouteImport } from './routes/_authenticated/w/$slug/docs'
import { Route as AuthenticatedWSlugDashboardRouteImport } from './routes/_authenticated/w/$slug/dashboard'
import { Route as AuthenticatedWSlugSupportIndexRouteImport } from './routes/_authenticated/w/$slug/support/index'
import { Route as AuthenticatedWSlugSprintsIndexRouteImport } from './routes/_authenticated/w/$slug/sprints/index'
import { Route as AuthenticatedWSlugSettingsIndexRouteImport } from './routes/_authenticated/w/$slug/settings/index'
import { Route as AuthenticatedWSlugPmIndexRouteImport } from './routes/_authenticated/w/$slug/pm/index'
import { Route as AuthenticatedWSlugDocsIndexRouteImport } from './routes/_authenticated/w/$slug/docs/index'
import { Route as AuthenticatedWSlugCrmIndexRouteImport } from './routes/_authenticated/w/$slug/crm/index'
import { Route as AuthenticatedWSlugSupportConversationIdRouteImport } from './routes/_authenticated/w/$slug/support/$conversationId'
import { Route as AuthenticatedWSlugSprintsSprintIdRouteImport } from './routes/_authenticated/w/$slug/sprints/$sprintId'
import { Route as AuthenticatedWSlugSettingsWorkflowsRouteImport } from './routes/_authenticated/w/$slug/settings/workflows'
import { Route as AuthenticatedWSlugSettingsTeamsRouteImport } from './routes/_authenticated/w/$slug/settings/teams'
import { Route as AuthenticatedWSlugSettingsStoryTemplatesRouteImport } from './routes/_authenticated/w/$slug/settings/story-templates'
import { Route as AuthenticatedWSlugSettingsRedirectsRouteImport } from './routes/_authenticated/w/$slug/settings/redirects'
import { Route as AuthenticatedWSlugSettingsRecurringTasksRouteImport } from './routes/_authenticated/w/$slug/settings/recurring-tasks'
import { Route as AuthenticatedWSlugSettingsMembersRouteImport } from './routes/_authenticated/w/$slug/settings/members'
import { Route as AuthenticatedWSlugSettingsLabelsRouteImport } from './routes/_authenticated/w/$slug/settings/labels'
import { Route as AuthenticatedWSlugSettingsKnowledgeRouteImport } from './routes/_authenticated/w/$slug/settings/knowledge'
import { Route as AuthenticatedWSlugSettingsInboxesRoutingRouteImport } from './routes/_authenticated/w/$slug/settings/inboxes-routing'
import { Route as AuthenticatedWSlugSettingsImportRouteImport } from './routes/_authenticated/w/$slug/settings/import'
import { Route as AuthenticatedWSlugSettingsHelpcenterRouteImport } from './routes/_authenticated/w/$slug/settings/helpcenter'
import { Route as AuthenticatedWSlugSettingsGeneralRouteImport } from './routes/_authenticated/w/$slug/settings/general'
import { Route as AuthenticatedWSlugSettingsDeliveryRouteImport } from './routes/_authenticated/w/$slug/settings/delivery'
import { Route as AuthenticatedWSlugSettingsCrmPipelinesRouteImport } from './routes/_authenticated/w/$slug/settings/crm-pipelines'
import { Route as AuthenticatedWSlugSettingsCrmEmailRouteImport } from './routes/_authenticated/w/$slug/settings/crm-email'
import { Route as AuthenticatedWSlugSettingsCrmAutonomyRouteImport } from './routes/_authenticated/w/$slug/settings/crm-autonomy'
import { Route as AuthenticatedWSlugSettingsChatGeneralRouteImport } from './routes/_authenticated/w/$slug/settings/chat-general'
import { Route as AuthenticatedWSlugSettingsAutomationsRouteImport } from './routes/_authenticated/w/$slug/settings/automations'
import { Route as AuthenticatedWSlugSettingsAiAutomationsRouteImport } from './routes/_authenticated/w/$slug/settings/ai-automations'
import { Route as AuthenticatedWSlugSettingsSectionRouteImport } from './routes/_authenticated/w/$slug/settings/$section'
import { Route as AuthenticatedWSlugPmToolCatalogRouteImport } from './routes/_authenticated/w/$slug/pm/tool-catalog'
import { Route as AuthenticatedWSlugPmSupportRouteImport } from './routes/_authenticated/w/$slug/pm/support'
import { Route as AuthenticatedWSlugPmRoadmapRouteImport } from './routes/_authenticated/w/$slug/pm/roadmap'
import { Route as AuthenticatedWSlugPmReportsRouteImport } from './routes/_authenticated/w/$slug/pm/reports'
import { Route as AuthenticatedWSlugPmMyWorkRouteImport } from './routes/_authenticated/w/$slug/pm/my-work'
import { Route as AuthenticatedWSlugPmLabelsRouteImport } from './routes/_authenticated/w/$slug/pm/labels'
import { Route as AuthenticatedWSlugPmAgentsRouteImport } from './routes/_authenticated/w/$slug/pm/agents'
import { Route as AuthenticatedWSlugPmAgentRunsRouteImport } from './routes/_authenticated/w/$slug/pm/agent-runs'
import { Route as AuthenticatedWSlugDocsRecentRouteImport } from './routes/_authenticated/w/$slug/docs/recent'
import { Route as AuthenticatedWSlugDocsMyRouteImport } from './routes/_authenticated/w/$slug/docs/my'
import { Route as AuthenticatedWSlugDocsDraftsRouteImport } from './routes/_authenticated/w/$slug/docs/drafts'
import { Route as AuthenticatedWSlugCrmReviewRouteImport } from './routes/_authenticated/w/$slug/crm/review'
import { Route as AuthenticatedWSlugCrmInsightsRouteImport } from './routes/_authenticated/w/$slug/crm/insights'
import { Route as AuthenticatedWSlugPmStoriesIndexRouteImport } from './routes/_authenticated/w/$slug/pm/stories/index'
import { Route as AuthenticatedWSlugPmSprintsIndexRouteImport } from './routes/_authenticated/w/$slug/pm/sprints/index'
import { Route as AuthenticatedWSlugPmObjectivesIndexRouteImport } from './routes/_authenticated/w/$slug/pm/objectives/index'
import { Route as AuthenticatedWSlugPmEpicsIndexRouteImport } from './routes/_authenticated/w/$slug/pm/epics/index'
import { Route as AuthenticatedWSlugCrmSequencesIndexRouteImport } from './routes/_authenticated/w/$slug/crm/sequences/index'
import { Route as AuthenticatedWSlugCrmListsIndexRouteImport } from './routes/_authenticated/w/$slug/crm/lists/index'
import { Route as AuthenticatedWSlugCrmDealsIndexRouteImport } from './routes/_authenticated/w/$slug/crm/deals/index'
import { Route as AuthenticatedWSlugCrmContactsIndexRouteImport } from './routes/_authenticated/w/$slug/crm/contacts/index'
import { Route as AuthenticatedWSlugCrmCompaniesIndexRouteImport } from './routes/_authenticated/w/$slug/crm/companies/index'
import { Route as AuthenticatedWSlugPmStoriesStoryIdRouteImport } from './routes/_authenticated/w/$slug/pm/stories/$storyId'
import { Route as AuthenticatedWSlugPmSprintsSprintIdRouteImport } from './routes/_authenticated/w/$slug/pm/sprints/$sprintId'
import { Route as AuthenticatedWSlugPmObjectivesObjectiveIdRouteImport } from './routes/_authenticated/w/$slug/pm/objectives/$objectiveId'
import { Route as AuthenticatedWSlugPmEpicsEpicIdRouteImport } from './routes/_authenticated/w/$slug/pm/epics/$epicId'
import { Route as AuthenticatedWSlugPmCodingSessionsSessionIdRouteImport } from './routes/_authenticated/w/$slug/pm/coding-sessions/$sessionId'
import { Route as AuthenticatedWSlugDocsSpacesSpaceIdRouteImport } from './routes/_authenticated/w/$slug/docs/spaces/$spaceId'
import { Route as AuthenticatedWSlugDocsDocumentsDocIdRouteImport } from './routes/_authenticated/w/$slug/docs/documents/$docId'
import { Route as AuthenticatedWSlugCrmSequencesSequenceIdRouteImport } from './routes/_authenticated/w/$slug/crm/sequences/$sequenceId'
import { Route as AuthenticatedWSlugCrmDealsDealIdRouteImport } from './routes/_authenticated/w/$slug/crm/deals/$dealId'
import { Route as AuthenticatedWSlugCrmContactsContactIdRouteImport } from './routes/_authenticated/w/$slug/crm/contacts/$contactId'
import { Route as AuthenticatedWSlugCrmCompaniesCompanyIdRouteImport } from './routes/_authenticated/w/$slug/crm/companies/$companyId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareTokenRoute = ShareShareTokenRouteImport.update({
  id: '/share/$shareToken',
  path: '/share/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWSlugRoute = AuthenticatedWSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWSlugIndexRoute = AuthenticatedWSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedWSlugRoute,
} as any)
const AuthenticatedWSlugTeamGoalsRoute =
  AuthenticatedWSlugTeamGoalsRouteImport.update({
    id: '/team-goals',
    path: '/team-goals',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugTasksRoute = AuthenticatedWSlugTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedWSlugRoute,
} as any)
const AuthenticatedWSlugNotificationsRoute =
  AuthenticatedWSlugNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugDocsRoute = AuthenticatedWSlugDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedWSlugRoute,
} as any)
const AuthenticatedWSlugDashboardRoute =
  AuthenticatedWSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSupportIndexRoute =
  AuthenticatedWSlugSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSprintsIndexRoute =
  AuthenticatedWSlugSprintsIndexRouteImport.update({
    id: '/sprints/',
    path: '/sprints/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsIndexRoute =
  AuthenticatedWSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmIndexRoute =
  AuthenticatedWSlugPmIndexRouteImport.update({
    id: '/pm/',
    path: '/pm/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugDocsIndexRoute =
  AuthenticatedWSlugDocsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWSlugDocsRoute,
  } as any)
const AuthenticatedWSlugCrmIndexRoute =
  AuthenticatedWSlugCrmIndexRouteImport.update({
    id: '/crm/',
    path: '/crm/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSupportConversationIdRoute =
  AuthenticatedWSlugSupportConversationIdRouteImport.update({
    id: '/support/$conversationId',
    path: '/support/$conversationId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSprintsSprintIdRoute =
  AuthenticatedWSlugSprintsSprintIdRouteImport.update({
    id: '/sprints/$sprintId',
    path: '/sprints/$sprintId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsWorkflowsRoute =
  AuthenticatedWSlugSettingsWorkflowsRouteImport.update({
    id: '/settings/workflows',
    path: '/settings/workflows',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsTeamsRoute =
  AuthenticatedWSlugSettingsTeamsRouteImport.update({
    id: '/settings/teams',
    path: '/settings/teams',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsStoryTemplatesRoute =
  AuthenticatedWSlugSettingsStoryTemplatesRouteImport.update({
    id: '/settings/story-templates',
    path: '/settings/story-templates',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsRedirectsRoute =
  AuthenticatedWSlugSettingsRedirectsRouteImport.update({
    id: '/settings/redirects',
    path: '/settings/redirects',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsRecurringTasksRoute =
  AuthenticatedWSlugSettingsRecurringTasksRouteImport.update({
    id: '/settings/recurring-tasks',
    path: '/settings/recurring-tasks',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsMembersRoute =
  AuthenticatedWSlugSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsLabelsRoute =
  AuthenticatedWSlugSettingsLabelsRouteImport.update({
    id: '/settings/labels',
    path: '/settings/labels',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsKnowledgeRoute =
  AuthenticatedWSlugSettingsKnowledgeRouteImport.update({
    id: '/settings/knowledge',
    path: '/settings/knowledge',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsInboxesRoutingRoute =
  AuthenticatedWSlugSettingsInboxesRoutingRouteImport.update({
    id: '/settings/inboxes-routing',
    path: '/settings/inboxes-routing',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsImportRoute =
  AuthenticatedWSlugSettingsImportRouteImport.update({
    id: '/settings/import',
    path: '/settings/import',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsHelpcenterRoute =
  AuthenticatedWSlugSettingsHelpcenterRouteImport.update({
    id: '/settings/helpcenter',
    path: '/settings/helpcenter',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsGeneralRoute =
  AuthenticatedWSlugSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsDeliveryRoute =
  AuthenticatedWSlugSettingsDeliveryRouteImport.update({
    id: '/settings/delivery',
    path: '/settings/delivery',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsCrmPipelinesRoute =
  AuthenticatedWSlugSettingsCrmPipelinesRouteImport.update({
    id: '/settings/crm-pipelines',
    path: '/settings/crm-pipelines',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsCrmEmailRoute =
  AuthenticatedWSlugSettingsCrmEmailRouteImport.update({
    id: '/settings/crm-email',
    path: '/settings/crm-email',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsCrmAutonomyRoute =
  AuthenticatedWSlugSettingsCrmAutonomyRouteImport.update({
    id: '/settings/crm-autonomy',
    path: '/settings/crm-autonomy',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsChatGeneralRoute =
  AuthenticatedWSlugSettingsChatGeneralRouteImport.update({
    id: '/settings/chat-general',
    path: '/settings/chat-general',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsAutomationsRoute =
  AuthenticatedWSlugSettingsAutomationsRouteImport.update({
    id: '/settings/automations',
    path: '/settings/automations',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsAiAutomationsRoute =
  AuthenticatedWSlugSettingsAiAutomationsRouteImport.update({
    id: '/settings/ai-automations',
    path: '/settings/ai-automations',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugSettingsSectionRoute =
  AuthenticatedWSlugSettingsSectionRouteImport.update({
    id: '/settings/$section',
    path: '/settings/$section',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmToolCatalogRoute =
  AuthenticatedWSlugPmToolCatalogRouteImport.update({
    id: '/pm/tool-catalog',
    path: '/pm/tool-catalog',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmSupportRoute =
  AuthenticatedWSlugPmSupportRouteImport.update({
    id: '/pm/support',
    path: '/pm/support',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmRoadmapRoute =
  AuthenticatedWSlugPmRoadmapRouteImport.update({
    id: '/pm/roadmap',
    path: '/pm/roadmap',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmReportsRoute =
  AuthenticatedWSlugPmReportsRouteImport.update({
    id: '/pm/reports',
    path: '/pm/reports',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmMyWorkRoute =
  AuthenticatedWSlugPmMyWorkRouteImport.update({
    id: '/pm/my-work',
    path: '/pm/my-work',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmLabelsRoute =
  AuthenticatedWSlugPmLabelsRouteImport.update({
    id: '/pm/labels',
    path: '/pm/labels',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmAgentsRoute =
  AuthenticatedWSlugPmAgentsRouteImport.update({
    id: '/pm/agents',
    path: '/pm/agents',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmAgentRunsRoute =
  AuthenticatedWSlugPmAgentRunsRouteImport.update({
    id: '/pm/agent-runs',
    path: '/pm/agent-runs',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugDocsRecentRoute =
  AuthenticatedWSlugDocsRecentRouteImport.update({
    id: '/recent',
    path: '/recent',
    getParentRoute: () => AuthenticatedWSlugDocsRoute,
  } as any)
const AuthenticatedWSlugDocsMyRoute =
  AuthenticatedWSlugDocsMyRouteImport.update({
    id: '/my',
    path: '/my',
    getParentRoute: () => AuthenticatedWSlugDocsRoute,
  } as any)
const AuthenticatedWSlugDocsDraftsRoute =
  AuthenticatedWSlugDocsDraftsRouteImport.update({
    id: '/drafts',
    path: '/drafts',
    getParentRoute: () => AuthenticatedWSlugDocsRoute,
  } as any)
const AuthenticatedWSlugCrmReviewRoute =
  AuthenticatedWSlugCrmReviewRouteImport.update({
    id: '/crm/review',
    path: '/crm/review',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugCrmInsightsRoute =
  AuthenticatedWSlugCrmInsightsRouteImport.update({
    id: '/crm/insights',
    path: '/crm/insights',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmStoriesIndexRoute =
  AuthenticatedWSlugPmStoriesIndexRouteImport.update({
    id: '/pm/stories/',
    path: '/pm/stories/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmSprintsIndexRoute =
  AuthenticatedWSlugPmSprintsIndexRouteImport.update({
    id: '/pm/sprints/',
    path: '/pm/sprints/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmObjectivesIndexRoute =
  AuthenticatedWSlugPmObjectivesIndexRouteImport.update({
    id: '/pm/objectives/',
    path: '/pm/objectives/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmEpicsIndexRoute =
  AuthenticatedWSlugPmEpicsIndexRouteImport.update({
    id: '/pm/epics/',
    path: '/pm/epics/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugCrmSequencesIndexRoute =
  AuthenticatedWSlugCrmSequencesIndexRouteImport.update({
    id: '/crm/sequences/',
    path: '/crm/sequences/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugCrmListsIndexRoute =
  AuthenticatedWSlugCrmListsIndexRouteImport.update({
    id: '/crm/lists/',
    path: '/crm/lists/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugCrmDealsIndexRoute =
  AuthenticatedWSlugCrmDealsIndexRouteImport.update({
    id: '/crm/deals/',
    path: '/crm/deals/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugCrmContactsIndexRoute =
  AuthenticatedWSlugCrmContactsIndexRouteImport.update({
    id: '/crm/contacts/',
    path: '/crm/contacts/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugCrmCompaniesIndexRoute =
  AuthenticatedWSlugCrmCompaniesIndexRouteImport.update({
    id: '/crm/companies/',
    path: '/crm/companies/',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmStoriesStoryIdRoute =
  AuthenticatedWSlugPmStoriesStoryIdRouteImport.update({
    id: '/pm/stories/$storyId',
    path: '/pm/stories/$storyId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmSprintsSprintIdRoute =
  AuthenticatedWSlugPmSprintsSprintIdRouteImport.update({
    id: '/pm/sprints/$sprintId',
    path: '/pm/sprints/$sprintId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmObjectivesObjectiveIdRoute =
  AuthenticatedWSlugPmObjectivesObjectiveIdRouteImport.update({
    id: '/pm/objectives/$objectiveId',
    path: '/pm/objectives/$objectiveId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmEpicsEpicIdRoute =
  AuthenticatedWSlugPmEpicsEpicIdRouteImport.update({
    id: '/pm/epics/$epicId',
    path: '/pm/epics/$epicId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugPmCodingSessionsSessionIdRoute =
  AuthenticatedWSlugPmCodingSessionsSessionIdRouteImport.update({
    id: '/pm/coding-sessions/$sessionId',
    path: '/pm/coding-sessions/$sessionId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugDocsSpacesSpaceIdRoute =
  AuthenticatedWSlugDocsSpacesSpaceIdRouteImport.update({
    id: '/spaces/$spaceId',
    path: '/spaces/$spaceId',
    getParentRoute: () => AuthenticatedWSlugDocsRoute,
  } as any)
const AuthenticatedWSlugDocsDocumentsDocIdRoute =
  AuthenticatedWSlugDocsDocumentsDocIdRouteImport.update({
    id: '/documents/$docId',
    path: '/documents/$docId',
    getParentRoute: () => AuthenticatedWSlugDocsRoute,
  } as any)
const AuthenticatedWSlugCrmSequencesSequenceIdRoute =
  AuthenticatedWSlugCrmSequencesSequenceIdRouteImport.update({
    id: '/crm/sequences/$sequenceId',
    path: '/crm/sequences/$sequenceId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugCrmDealsDealIdRoute =
  AuthenticatedWSlugCrmDealsDealIdRouteImport.update({
    id: '/crm/deals/$dealId',
    path: '/crm/deals/$dealId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugCrmContactsContactIdRoute =
  AuthenticatedWSlugCrmContactsContactIdRouteImport.update({
    id: '/crm/contacts/$contactId',
    path: '/crm/contacts/$contactId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)
const AuthenticatedWSlugCrmCompaniesCompanyIdRoute =
  AuthenticatedWSlugCrmCompaniesCompanyIdRouteImport.update({
    id: '/crm/companies/$companyId',
    path: '/crm/companies/$companyId',
    getParentRoute: () => AuthenticatedWSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/join/$token': typeof JoinTokenRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/w/$slug': typeof AuthenticatedWSlugRouteWithChildren
  '/w/$slug/dashboard': typeof AuthenticatedWSlugDashboardRoute
  '/w/$slug/docs': typeof AuthenticatedWSlugDocsRouteWithChildren
  '/w/$slug/notifications': typeof AuthenticatedWSlugNotificationsRoute
  '/w/$slug/tasks': typeof AuthenticatedWSlugTasksRoute
  '/w/$slug/team-goals': typeof AuthenticatedWSlugTeamGoalsRoute
  '/w/$slug/': typeof AuthenticatedWSlugIndexRoute
  '/w/$slug/crm/insights': typeof AuthenticatedWSlugCrmInsightsRoute
  '/w/$slug/crm/review': typeof AuthenticatedWSlugCrmReviewRoute
  '/w/$slug/docs/drafts': typeof AuthenticatedWSlugDocsDraftsRoute
  '/w/$slug/docs/my': typeof AuthenticatedWSlugDocsMyRoute
  '/w/$slug/docs/recent': typeof AuthenticatedWSlugDocsRecentRoute
  '/w/$slug/pm/agent-runs': typeof AuthenticatedWSlugPmAgentRunsRoute
  '/w/$slug/pm/agents': typeof AuthenticatedWSlugPmAgentsRoute
  '/w/$slug/pm/labels': typeof AuthenticatedWSlugPmLabelsRoute
  '/w/$slug/pm/my-work': typeof AuthenticatedWSlugPmMyWorkRoute
  '/w/$slug/pm/reports': typeof AuthenticatedWSlugPmReportsRoute
  '/w/$slug/pm/roadmap': typeof AuthenticatedWSlugPmRoadmapRoute
  '/w/$slug/pm/support': typeof AuthenticatedWSlugPmSupportRoute
  '/w/$slug/pm/tool-catalog': typeof AuthenticatedWSlugPmToolCatalogRoute
  '/w/$slug/settings/$section': typeof AuthenticatedWSlugSettingsSectionRoute
  '/w/$slug/settings/ai-automations': typeof AuthenticatedWSlugSettingsAiAutomationsRoute
  '/w/$slug/settings/automations': typeof AuthenticatedWSlugSettingsAutomationsRoute
  '/w/$slug/settings/chat-general': typeof AuthenticatedWSlugSettingsChatGeneralRoute
  '/w/$slug/settings/crm-autonomy': typeof AuthenticatedWSlugSettingsCrmAutonomyRoute
  '/w/$slug/settings/crm-email': typeof AuthenticatedWSlugSettingsCrmEmailRoute
  '/w/$slug/settings/crm-pipelines': typeof AuthenticatedWSlugSettingsCrmPipelinesRoute
  '/w/$slug/settings/delivery': typeof AuthenticatedWSlugSettingsDeliveryRoute
  '/w/$slug/settings/general': typeof AuthenticatedWSlugSettingsGeneralRoute
  '/w/$slug/settings/helpcenter': typeof AuthenticatedWSlugSettingsHelpcenterRoute
  '/w/$slug/settings/import': typeof AuthenticatedWSlugSettingsImportRoute
  '/w/$slug/settings/inboxes-routing': typeof AuthenticatedWSlugSettingsInboxesRoutingRoute
  '/w/$slug/settings/knowledge': typeof AuthenticatedWSlugSettingsKnowledgeRoute
  '/w/$slug/settings/labels': typeof AuthenticatedWSlugSettingsLabelsRoute
  '/w/$slug/settings/members': typeof AuthenticatedWSlugSettingsMembersRoute
  '/w/$slug/settings/recurring-tasks': typeof AuthenticatedWSlugSettingsRecurringTasksRoute
  '/w/$slug/settings/redirects': typeof AuthenticatedWSlugSettingsRedirectsRoute
  '/w/$slug/settings/story-templates': typeof AuthenticatedWSlugSettingsStoryTemplatesRoute
  '/w/$slug/settings/teams': typeof AuthenticatedWSlugSettingsTeamsRoute
  '/w/$slug/settings/workflows': typeof AuthenticatedWSlugSettingsWorkflowsRoute
  '/w/$slug/sprints/$sprintId': typeof AuthenticatedWSlugSprintsSprintIdRoute
  '/w/$slug/support/$conversationId': typeof AuthenticatedWSlugSupportConversationIdRoute
  '/w/$slug/crm/': typeof AuthenticatedWSlugCrmIndexRoute
  '/w/$slug/docs/': typeof AuthenticatedWSlugDocsIndexRoute
  '/w/$slug/pm/': typeof AuthenticatedWSlugPmIndexRoute
  '/w/$slug/settings/': typeof AuthenticatedWSlugSettingsIndexRoute
  '/w/$slug/sprints/': typeof AuthenticatedWSlugSprintsIndexRoute
  '/w/$slug/support/': typeof AuthenticatedWSlugSupportIndexRoute
  '/w/$slug/crm/companies/$companyId': typeof AuthenticatedWSlugCrmCompaniesCompanyIdRoute
  '/w/$slug/crm/contacts/$contactId': typeof AuthenticatedWSlugCrmContactsContactIdRoute
  '/w/$slug/crm/deals/$dealId': typeof AuthenticatedWSlugCrmDealsDealIdRoute
  '/w/$slug/crm/sequences/$sequenceId': typeof AuthenticatedWSlugCrmSequencesSequenceIdRoute
  '/w/$slug/docs/documents/$docId': typeof AuthenticatedWSlugDocsDocumentsDocIdRoute
  '/w/$slug/docs/spaces/$spaceId': typeof AuthenticatedWSlugDocsSpacesSpaceIdRoute
  '/w/$slug/pm/coding-sessions/$sessionId': typeof AuthenticatedWSlugPmCodingSessionsSessionIdRoute
  '/w/$slug/pm/epics/$epicId': typeof AuthenticatedWSlugPmEpicsEpicIdRoute
  '/w/$slug/pm/objectives/$objectiveId': typeof AuthenticatedWSlugPmObjectivesObjectiveIdRoute
  '/w/$slug/pm/sprints/$sprintId': typeof AuthenticatedWSlugPmSprintsSprintIdRoute
  '/w/$slug/pm/stories/$storyId': typeof AuthenticatedWSlugPmStoriesStoryIdRoute
  '/w/$slug/crm/companies/': typeof AuthenticatedWSlugCrmCompaniesIndexRoute
  '/w/$slug/crm/contacts/': typeof AuthenticatedWSlugCrmContactsIndexRoute
  '/w/$slug/crm/deals/': typeof AuthenticatedWSlugCrmDealsIndexRoute
  '/w/$slug/crm/lists/': typeof AuthenticatedWSlugCrmListsIndexRoute
  '/w/$slug/crm/sequences/': typeof AuthenticatedWSlugCrmSequencesIndexRoute
  '/w/$slug/pm/epics/': typeof AuthenticatedWSlugPmEpicsIndexRoute
  '/w/$slug/pm/objectives/': typeof AuthenticatedWSlugPmObjectivesIndexRoute
  '/w/$slug/pm/sprints/': typeof AuthenticatedWSlugPmSprintsIndexRoute
  '/w/$slug/pm/stories/': typeof AuthenticatedWSlugPmStoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/join/$token': typeof JoinTokenRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/w/$slug/dashboard': typeof AuthenticatedWSlugDashboardRoute
  '/w/$slug/notifications': typeof AuthenticatedWSlugNotificationsRoute
  '/w/$slug/tasks': typeof AuthenticatedWSlugTasksRoute
  '/w/$slug/team-goals': typeof AuthenticatedWSlugTeamGoalsRoute
  '/w/$slug': typeof AuthenticatedWSlugIndexRoute
  '/w/$slug/crm/insights': typeof AuthenticatedWSlugCrmInsightsRoute
  '/w/$slug/crm/review': typeof AuthenticatedWSlugCrmReviewRoute
  '/w/$slug/docs/drafts': typeof AuthenticatedWSlugDocsDraftsRoute
  '/w/$slug/docs/my': typeof AuthenticatedWSlugDocsMyRoute
  '/w/$slug/docs/recent': typeof AuthenticatedWSlugDocsRecentRoute
  '/w/$slug/pm/agent-runs': typeof AuthenticatedWSlugPmAgentRunsRoute
  '/w/$slug/pm/agents': typeof AuthenticatedWSlugPmAgentsRoute
  '/w/$slug/pm/labels': typeof AuthenticatedWSlugPmLabelsRoute
  '/w/$slug/pm/my-work': typeof AuthenticatedWSlugPmMyWorkRoute
  '/w/$slug/pm/reports': typeof AuthenticatedWSlugPmReportsRoute
  '/w/$slug/pm/roadmap': typeof AuthenticatedWSlugPmRoadmapRoute
  '/w/$slug/pm/support': typeof AuthenticatedWSlugPmSupportRoute
  '/w/$slug/pm/tool-catalog': typeof AuthenticatedWSlugPmToolCatalogRoute
  '/w/$slug/settings/$section': typeof AuthenticatedWSlugSettingsSectionRoute
  '/w/$slug/settings/ai-automations': typeof AuthenticatedWSlugSettingsAiAutomationsRoute
  '/w/$slug/settings/automations': typeof AuthenticatedWSlugSettingsAutomationsRoute
  '/w/$slug/settings/chat-general': typeof AuthenticatedWSlugSettingsChatGeneralRoute
  '/w/$slug/settings/crm-autonomy': typeof AuthenticatedWSlugSettingsCrmAutonomyRoute
  '/w/$slug/settings/crm-email': typeof AuthenticatedWSlugSettingsCrmEmailRoute
  '/w/$slug/settings/crm-pipelines': typeof AuthenticatedWSlugSettingsCrmPipelinesRoute
  '/w/$slug/settings/delivery': typeof AuthenticatedWSlugSettingsDeliveryRoute
  '/w/$slug/settings/general': typeof AuthenticatedWSlugSettingsGeneralRoute
  '/w/$slug/settings/helpcenter': typeof AuthenticatedWSlugSettingsHelpcenterRoute
  '/w/$slug/settings/import': typeof AuthenticatedWSlugSettingsImportRoute
  '/w/$slug/settings/inboxes-routing': typeof AuthenticatedWSlugSettingsInboxesRoutingRoute
  '/w/$slug/settings/knowledge': typeof AuthenticatedWSlugSettingsKnowledgeRoute
  '/w/$slug/settings/labels': typeof AuthenticatedWSlugSettingsLabelsRoute
  '/w/$slug/settings/members': typeof AuthenticatedWSlugSettingsMembersRoute
  '/w/$slug/settings/recurring-tasks': typeof AuthenticatedWSlugSettingsRecurringTasksRoute
  '/w/$slug/settings/redirects': typeof AuthenticatedWSlugSettingsRedirectsRoute
  '/w/$slug/settings/story-templates': typeof AuthenticatedWSlugSettingsStoryTemplatesRoute
  '/w/$slug/settings/teams': typeof AuthenticatedWSlugSettingsTeamsRoute
  '/w/$slug/settings/workflows': typeof AuthenticatedWSlugSettingsWorkflowsRoute
  '/w/$slug/sprints/$sprintId': typeof AuthenticatedWSlugSprintsSprintIdRoute
  '/w/$slug/support/$conversationId': typeof AuthenticatedWSlugSupportConversationIdRoute
  '/w/$slug/crm': typeof AuthenticatedWSlugCrmIndexRoute
  '/w/$slug/docs': typeof AuthenticatedWSlugDocsIndexRoute
  '/w/$slug/pm': typeof AuthenticatedWSlugPmIndexRoute
  '/w/$slug/settings': typeof AuthenticatedWSlugSettingsIndexRoute
  '/w/$slug/sprints': typeof AuthenticatedWSlugSprintsIndexRoute
  '/w/$slug/support': typeof AuthenticatedWSlugSupportIndexRoute
  '/w/$slug/crm/companies/$companyId': typeof AuthenticatedWSlugCrmCompaniesCompanyIdRoute
  '/w/$slug/crm/contacts/$contactId': typeof AuthenticatedWSlugCrmContactsContactIdRoute
  '/w/$slug/crm/deals/$dealId': typeof AuthenticatedWSlugCrmDealsDealIdRoute
  '/w/$slug/crm/sequences/$sequenceId': typeof AuthenticatedWSlugCrmSequencesSequenceIdRoute
  '/w/$slug/docs/documents/$docId': typeof AuthenticatedWSlugDocsDocumentsDocIdRoute
  '/w/$slug/docs/spaces/$spaceId': typeof AuthenticatedWSlugDocsSpacesSpaceIdRoute
  '/w/$slug/pm/coding-sessions/$sessionId': typeof AuthenticatedWSlugPmCodingSessionsSessionIdRoute
  '/w/$slug/pm/epics/$epicId': typeof AuthenticatedWSlugPmEpicsEpicIdRoute
  '/w/$slug/pm/objectives/$objectiveId': typeof AuthenticatedWSlugPmObjectivesObjectiveIdRoute
  '/w/$slug/pm/sprints/$sprintId': typeof AuthenticatedWSlugPmSprintsSprintIdRoute
  '/w/$slug/pm/stories/$storyId': typeof AuthenticatedWSlugPmStoriesStoryIdRoute
  '/w/$slug/crm/companies': typeof AuthenticatedWSlugCrmCompaniesIndexRoute
  '/w/$slug/crm/contacts': typeof AuthenticatedWSlugCrmContactsIndexRoute
  '/w/$slug/crm/deals': typeof AuthenticatedWSlugCrmDealsIndexRoute
  '/w/$slug/crm/lists': typeof AuthenticatedWSlugCrmListsIndexRoute
  '/w/$slug/crm/sequences': typeof AuthenticatedWSlugCrmSequencesIndexRoute
  '/w/$slug/pm/epics': typeof AuthenticatedWSlugPmEpicsIndexRoute
  '/w/$slug/pm/objectives': typeof AuthenticatedWSlugPmObjectivesIndexRoute
  '/w/$slug/pm/sprints': typeof AuthenticatedWSlugPmSprintsIndexRoute
  '/w/$slug/pm/stories': typeof AuthenticatedWSlugPmStoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/join/$token': typeof JoinTokenRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/_authenticated/w/$slug': typeof AuthenticatedWSlugRouteWithChildren
  '/_authenticated/w/$slug/dashboard': typeof AuthenticatedWSlugDashboardRoute
  '/_authenticated/w/$slug/docs': typeof AuthenticatedWSlugDocsRouteWithChildren
  '/_authenticated/w/$slug/notifications': typeof AuthenticatedWSlugNotificationsRoute
  '/_authenticated/w/$slug/tasks': typeof AuthenticatedWSlugTasksRoute
  '/_authenticated/w/$slug/team-goals': typeof AuthenticatedWSlugTeamGoalsRoute
  '/_authenticated/w/$slug/': typeof AuthenticatedWSlugIndexRoute
  '/_authenticated/w/$slug/crm/insights': typeof AuthenticatedWSlugCrmInsightsRoute
  '/_authenticated/w/$slug/crm/review': typeof AuthenticatedWSlugCrmReviewRoute
  '/_authenticated/w/$slug/docs/drafts': typeof AuthenticatedWSlugDocsDraftsRoute
  '/_authenticated/w/$slug/docs/my': typeof AuthenticatedWSlugDocsMyRoute
  '/_authenticated/w/$slug/docs/recent': typeof AuthenticatedWSlugDocsRecentRoute
  '/_authenticated/w/$slug/pm/agent-runs': typeof AuthenticatedWSlugPmAgentRunsRoute
  '/_authenticated/w/$slug/pm/agents': typeof AuthenticatedWSlugPmAgentsRoute
  '/_authenticated/w/$slug/pm/labels': typeof AuthenticatedWSlugPmLabelsRoute
  '/_authenticated/w/$slug/pm/my-work': typeof AuthenticatedWSlugPmMyWorkRoute
  '/_authenticated/w/$slug/pm/reports': typeof AuthenticatedWSlugPmReportsRoute
  '/_authenticated/w/$slug/pm/roadmap': typeof AuthenticatedWSlugPmRoadmapRoute
  '/_authenticated/w/$slug/pm/support': typeof AuthenticatedWSlugPmSupportRoute
  '/_authenticated/w/$slug/pm/tool-catalog': typeof AuthenticatedWSlugPmToolCatalogRoute
  '/_authenticated/w/$slug/settings/$section': typeof AuthenticatedWSlugSettingsSectionRoute
  '/_authenticated/w/$slug/settings/ai-automations': typeof AuthenticatedWSlugSettingsAiAutomationsRoute
  '/_authenticated/w/$slug/settings/automations': typeof AuthenticatedWSlugSettingsAutomationsRoute
  '/_authenticated/w/$slug/settings/chat-general': typeof AuthenticatedWSlugSettingsChatGeneralRoute
  '/_authenticated/w/$slug/settings/crm-autonomy': typeof AuthenticatedWSlugSettingsCrmAutonomyRoute
  '/_authenticated/w/$slug/settings/crm-email': typeof AuthenticatedWSlugSettingsCrmEmailRoute
  '/_authenticated/w/$slug/settings/crm-pipelines': typeof AuthenticatedWSlugSettingsCrmPipelinesRoute
  '/_authenticated/w/$slug/settings/delivery': typeof AuthenticatedWSlugSettingsDeliveryRoute
  '/_authenticated/w/$slug/settings/general': typeof AuthenticatedWSlugSettingsGeneralRoute
  '/_authenticated/w/$slug/settings/helpcenter': typeof AuthenticatedWSlugSettingsHelpcenterRoute
  '/_authenticated/w/$slug/settings/import': typeof AuthenticatedWSlugSettingsImportRoute
  '/_authenticated/w/$slug/settings/inboxes-routing': typeof AuthenticatedWSlugSettingsInboxesRoutingRoute
  '/_authenticated/w/$slug/settings/knowledge': typeof AuthenticatedWSlugSettingsKnowledgeRoute
  '/_authenticated/w/$slug/settings/labels': typeof AuthenticatedWSlugSettingsLabelsRoute
  '/_authenticated/w/$slug/settings/members': typeof AuthenticatedWSlugSettingsMembersRoute
  '/_authenticated/w/$slug/settings/recurring-tasks': typeof AuthenticatedWSlugSettingsRecurringTasksRoute
  '/_authenticated/w/$slug/settings/redirects': typeof AuthenticatedWSlugSettingsRedirectsRoute
  '/_authenticated/w/$slug/settings/story-templates': typeof AuthenticatedWSlugSettingsStoryTemplatesRoute
  '/_authenticated/w/$slug/settings/teams': typeof AuthenticatedWSlugSettingsTeamsRoute
  '/_authenticated/w/$slug/settings/workflows': typeof AuthenticatedWSlugSettingsWorkflowsRoute
  '/_authenticated/w/$slug/sprints/$sprintId': typeof AuthenticatedWSlugSprintsSprintIdRoute
  '/_authenticated/w/$slug/support/$conversationId': typeof AuthenticatedWSlugSupportConversationIdRoute
  '/_authenticated/w/$slug/crm/': typeof AuthenticatedWSlugCrmIndexRoute
  '/_authenticated/w/$slug/docs/': typeof AuthenticatedWSlugDocsIndexRoute
  '/_authenticated/w/$slug/pm/': typeof AuthenticatedWSlugPmIndexRoute
  '/_authenticated/w/$slug/settings/': typeof AuthenticatedWSlugSettingsIndexRoute
  '/_authenticated/w/$slug/sprints/': typeof AuthenticatedWSlugSprintsIndexRoute
  '/_authenticated/w/$slug/support/': typeof AuthenticatedWSlugSupportIndexRoute
  '/_authenticated/w/$slug/crm/companies/$companyId': typeof AuthenticatedWSlugCrmCompaniesCompanyIdRoute
  '/_authenticated/w/$slug/crm/contacts/$contactId': typeof AuthenticatedWSlugCrmContactsContactIdRoute
  '/_authenticated/w/$slug/crm/deals/$dealId': typeof AuthenticatedWSlugCrmDealsDealIdRoute
  '/_authenticated/w/$slug/crm/sequences/$sequenceId': typeof AuthenticatedWSlugCrmSequencesSequenceIdRoute
  '/_authenticated/w/$slug/docs/documents/$docId': typeof AuthenticatedWSlugDocsDocumentsDocIdRoute
  '/_authenticated/w/$slug/docs/spaces/$spaceId': typeof AuthenticatedWSlugDocsSpacesSpaceIdRoute
  '/_authenticated/w/$slug/pm/coding-sessions/$sessionId': typeof AuthenticatedWSlugPmCodingSessionsSessionIdRoute
  '/_authenticated/w/$slug/pm/epics/$epicId': typeof AuthenticatedWSlugPmEpicsEpicIdRoute
  '/_authenticated/w/$slug/pm/objectives/$objectiveId': typeof AuthenticatedWSlugPmObjectivesObjectiveIdRoute
  '/_authenticated/w/$slug/pm/sprints/$sprintId': typeof AuthenticatedWSlugPmSprintsSprintIdRoute
  '/_authenticated/w/$slug/pm/stories/$storyId': typeof AuthenticatedWSlugPmStoriesStoryIdRoute
  '/_authenticated/w/$slug/crm/companies/': typeof AuthenticatedWSlugCrmCompaniesIndexRoute
  '/_authenticated/w/$slug/crm/contacts/': typeof AuthenticatedWSlugCrmContactsIndexRoute
  '/_authenticated/w/$slug/crm/deals/': typeof AuthenticatedWSlugCrmDealsIndexRoute
  '/_authenticated/w/$slug/crm/lists/': typeof AuthenticatedWSlugCrmListsIndexRoute
  '/_authenticated/w/$slug/crm/sequences/': typeof AuthenticatedWSlugCrmSequencesIndexRoute
  '/_authenticated/w/$slug/pm/epics/': typeof AuthenticatedWSlugPmEpicsIndexRoute
  '/_authenticated/w/$slug/pm/objectives/': typeof AuthenticatedWSlugPmObjectivesIndexRoute
  '/_authenticated/w/$slug/pm/sprints/': typeof AuthenticatedWSlugPmSprintsIndexRoute
  '/_authenticated/w/$slug/pm/stories/': typeof AuthenticatedWSlugPmStoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/profile'
    | '/workspaces'
    | '/join/$token'
    | '/share/$shareToken'
    | '/w/$slug'
    | '/w/$slug/dashboard'
    | '/w/$slug/docs'
    | '/w/$slug/notifications'
    | '/w/$slug/tasks'
    | '/w/$slug/team-goals'
    | '/w/$slug/'
    | '/w/$slug/crm/insights'
    | '/w/$slug/crm/review'
    | '/w/$slug/docs/drafts'
    | '/w/$slug/docs/my'
    | '/w/$slug/docs/recent'
    | '/w/$slug/pm/agent-runs'
    | '/w/$slug/pm/agents'
    | '/w/$slug/pm/labels'
    | '/w/$slug/pm/my-work'
    | '/w/$slug/pm/reports'
    | '/w/$slug/pm/roadmap'
    | '/w/$slug/pm/support'
    | '/w/$slug/pm/tool-catalog'
    | '/w/$slug/settings/$section'
    | '/w/$slug/settings/ai-automations'
    | '/w/$slug/settings/automations'
    | '/w/$slug/settings/chat-general'
    | '/w/$slug/settings/crm-autonomy'
    | '/w/$slug/settings/crm-email'
    | '/w/$slug/settings/crm-pipelines'
    | '/w/$slug/settings/delivery'
    | '/w/$slug/settings/general'
    | '/w/$slug/settings/helpcenter'
    | '/w/$slug/settings/import'
    | '/w/$slug/settings/inboxes-routing'
    | '/w/$slug/settings/knowledge'
    | '/w/$slug/settings/labels'
    | '/w/$slug/settings/members'
    | '/w/$slug/settings/recurring-tasks'
    | '/w/$slug/settings/redirects'
    | '/w/$slug/settings/story-templates'
    | '/w/$slug/settings/teams'
    | '/w/$slug/settings/workflows'
    | '/w/$slug/sprints/$sprintId'
    | '/w/$slug/support/$conversationId'
    | '/w/$slug/crm/'
    | '/w/$slug/docs/'
    | '/w/$slug/pm/'
    | '/w/$slug/settings/'
    | '/w/$slug/sprints/'
    | '/w/$slug/support/'
    | '/w/$slug/crm/companies/$companyId'
    | '/w/$slug/crm/contacts/$contactId'
    | '/w/$slug/crm/deals/$dealId'
    | '/w/$slug/crm/sequences/$sequenceId'
    | '/w/$slug/docs/documents/$docId'
    | '/w/$slug/docs/spaces/$spaceId'
    | '/w/$slug/pm/coding-sessions/$sessionId'
    | '/w/$slug/pm/epics/$epicId'
    | '/w/$slug/pm/objectives/$objectiveId'
    | '/w/$slug/pm/sprints/$sprintId'
    | '/w/$slug/pm/stories/$storyId'
    | '/w/$slug/crm/companies/'
    | '/w/$slug/crm/contacts/'
    | '/w/$slug/crm/deals/'
    | '/w/$slug/crm/lists/'
    | '/w/$slug/crm/sequences/'
    | '/w/$slug/pm/epics/'
    | '/w/$slug/pm/objectives/'
    | '/w/$slug/pm/sprints/'
    | '/w/$slug/pm/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/profile'
    | '/workspaces'
    | '/join/$token'
    | '/share/$shareToken'
    | '/w/$slug/dashboard'
    | '/w/$slug/notifications'
    | '/w/$slug/tasks'
    | '/w/$slug/team-goals'
    | '/w/$slug'
    | '/w/$slug/crm/insights'
    | '/w/$slug/crm/review'
    | '/w/$slug/docs/drafts'
    | '/w/$slug/docs/my'
    | '/w/$slug/docs/recent'
    | '/w/$slug/pm/agent-runs'
    | '/w/$slug/pm/agents'
    | '/w/$slug/pm/labels'
    | '/w/$slug/pm/my-work'
    | '/w/$slug/pm/reports'
    | '/w/$slug/pm/roadmap'
    | '/w/$slug/pm/support'
    | '/w/$slug/pm/tool-catalog'
    | '/w/$slug/settings/$section'
    | '/w/$slug/settings/ai-automations'
    | '/w/$slug/settings/automations'
    | '/w/$slug/settings/chat-general'
    | '/w/$slug/settings/crm-autonomy'
    | '/w/$slug/settings/crm-email'
    | '/w/$slug/settings/crm-pipelines'
    | '/w/$slug/settings/delivery'
    | '/w/$slug/settings/general'
    | '/w/$slug/settings/helpcenter'
    | '/w/$slug/settings/import'
    | '/w/$slug/settings/inboxes-routing'
    | '/w/$slug/settings/knowledge'
    | '/w/$slug/settings/labels'
    | '/w/$slug/settings/members'
    | '/w/$slug/settings/recurring-tasks'
    | '/w/$slug/settings/redirects'
    | '/w/$slug/settings/story-templates'
    | '/w/$slug/settings/teams'
    | '/w/$slug/settings/workflows'
    | '/w/$slug/sprints/$sprintId'
    | '/w/$slug/support/$conversationId'
    | '/w/$slug/crm'
    | '/w/$slug/docs'
    | '/w/$slug/pm'
    | '/w/$slug/settings'
    | '/w/$slug/sprints'
    | '/w/$slug/support'
    | '/w/$slug/crm/companies/$companyId'
    | '/w/$slug/crm/contacts/$contactId'
    | '/w/$slug/crm/deals/$dealId'
    | '/w/$slug/crm/sequences/$sequenceId'
    | '/w/$slug/docs/documents/$docId'
    | '/w/$slug/docs/spaces/$spaceId'
    | '/w/$slug/pm/coding-sessions/$sessionId'
    | '/w/$slug/pm/epics/$epicId'
    | '/w/$slug/pm/objectives/$objectiveId'
    | '/w/$slug/pm/sprints/$sprintId'
    | '/w/$slug/pm/stories/$storyId'
    | '/w/$slug/crm/companies'
    | '/w/$slug/crm/contacts'
    | '/w/$slug/crm/deals'
    | '/w/$slug/crm/lists'
    | '/w/$slug/crm/sequences'
    | '/w/$slug/pm/epics'
    | '/w/$slug/pm/objectives'
    | '/w/$slug/pm/sprints'
    | '/w/$slug/pm/stories'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_authenticated/profile'
    | '/_authenticated/workspaces'
    | '/join/$token'
    | '/share/$shareToken'
    | '/_authenticated/w/$slug'
    | '/_authenticated/w/$slug/dashboard'
    | '/_authenticated/w/$slug/docs'
    | '/_authenticated/w/$slug/notifications'
    | '/_authenticated/w/$slug/tasks'
    | '/_authenticated/w/$slug/team-goals'
    | '/_authenticated/w/$slug/'
    | '/_authenticated/w/$slug/crm/insights'
    | '/_authenticated/w/$slug/crm/review'
    | '/_authenticated/w/$slug/docs/drafts'
    | '/_authenticated/w/$slug/docs/my'
    | '/_authenticated/w/$slug/docs/recent'
    | '/_authenticated/w/$slug/pm/agent-runs'
    | '/_authenticated/w/$slug/pm/agents'
    | '/_authenticated/w/$slug/pm/labels'
    | '/_authenticated/w/$slug/pm/my-work'
    | '/_authenticated/w/$slug/pm/reports'
    | '/_authenticated/w/$slug/pm/roadmap'
    | '/_authenticated/w/$slug/pm/support'
    | '/_authenticated/w/$slug/pm/tool-catalog'
    | '/_authenticated/w/$slug/settings/$section'
    | '/_authenticated/w/$slug/settings/ai-automations'
    | '/_authenticated/w/$slug/settings/automations'
    | '/_authenticated/w/$slug/settings/chat-general'
    | '/_authenticated/w/$slug/settings/crm-autonomy'
    | '/_authenticated/w/$slug/settings/crm-email'
    | '/_authenticated/w/$slug/settings/crm-pipelines'
    | '/_authenticated/w/$slug/settings/delivery'
    | '/_authenticated/w/$slug/settings/general'
    | '/_authenticated/w/$slug/settings/helpcenter'
    | '/_authenticated/w/$slug/settings/import'
    | '/_authenticated/w/$slug/settings/inboxes-routing'
    | '/_authenticated/w/$slug/settings/knowledge'
    | '/_authenticated/w/$slug/settings/labels'
    | '/_authenticated/w/$slug/settings/members'
    | '/_authenticated/w/$slug/settings/recurring-tasks'
    | '/_authenticated/w/$slug/settings/redirects'
    | '/_authenticated/w/$slug/settings/story-templates'
    | '/_authenticated/w/$slug/settings/teams'
    | '/_authenticated/w/$slug/settings/workflows'
    | '/_authenticated/w/$slug/sprints/$sprintId'
    | '/_authenticated/w/$slug/support/$conversationId'
    | '/_authenticated/w/$slug/crm/'
    | '/_authenticated/w/$slug/docs/'
    | '/_authenticated/w/$slug/pm/'
    | '/_authenticated/w/$slug/settings/'
    | '/_authenticated/w/$slug/sprints/'
    | '/_authenticated/w/$slug/support/'
    | '/_authenticated/w/$slug/crm/companies/$companyId'
    | '/_authenticated/w/$slug/crm/contacts/$contactId'
    | '/_authenticated/w/$slug/crm/deals/$dealId'
    | '/_authenticated/w/$slug/crm/sequences/$sequenceId'
    | '/_authenticated/w/$slug/docs/documents/$docId'
    | '/_authenticated/w/$slug/docs/spaces/$spaceId'
    | '/_authenticated/w/$slug/pm/coding-sessions/$sessionId'
    | '/_authenticated/w/$slug/pm/epics/$epicId'
    | '/_authenticated/w/$slug/pm/objectives/$objectiveId'
    | '/_authenticated/w/$slug/pm/sprints/$sprintId'
    | '/_authenticated/w/$slug/pm/stories/$storyId'
    | '/_authenticated/w/$slug/crm/companies/'
    | '/_authenticated/w/$slug/crm/contacts/'
    | '/_authenticated/w/$slug/crm/deals/'
    | '/_authenticated/w/$slug/crm/lists/'
    | '/_authenticated/w/$slug/crm/sequences/'
    | '/_authenticated/w/$slug/pm/epics/'
    | '/_authenticated/w/$slug/pm/objectives/'
    | '/_authenticated/w/$slug/pm/sprints/'
    | '/_authenticated/w/$slug/pm/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ShareShareTokenRoute: typeof ShareShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareToken': {
      id: '/share/$shareToken'
      path: '/share/$shareToken'
      fullPath: '/share/$shareToken'
      preLoaderRoute: typeof ShareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$slug': {
      id: '/_authenticated/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof AuthenticatedWSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$slug/': {
      id: '/_authenticated/w/$slug/'
      path: '/'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof AuthenticatedWSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/team-goals': {
      id: '/_authenticated/w/$slug/team-goals'
      path: '/team-goals'
      fullPath: '/w/$slug/team-goals'
      preLoaderRoute: typeof AuthenticatedWSlugTeamGoalsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/tasks': {
      id: '/_authenticated/w/$slug/tasks'
      path: '/tasks'
      fullPath: '/w/$slug/tasks'
      preLoaderRoute: typeof AuthenticatedWSlugTasksRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/notifications': {
      id: '/_authenticated/w/$slug/notifications'
      path: '/notifications'
      fullPath: '/w/$slug/notifications'
      preLoaderRoute: typeof AuthenticatedWSlugNotificationsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/docs': {
      id: '/_authenticated/w/$slug/docs'
      path: '/docs'
      fullPath: '/w/$slug/docs'
      preLoaderRoute: typeof AuthenticatedWSlugDocsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/dashboard': {
      id: '/_authenticated/w/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/w/$slug/dashboard'
      preLoaderRoute: typeof AuthenticatedWSlugDashboardRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/support/': {
      id: '/_authenticated/w/$slug/support/'
      path: '/support'
      fullPath: '/w/$slug/support/'
      preLoaderRoute: typeof AuthenticatedWSlugSupportIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/sprints/': {
      id: '/_authenticated/w/$slug/sprints/'
      path: '/sprints'
      fullPath: '/w/$slug/sprints/'
      preLoaderRoute: typeof AuthenticatedWSlugSprintsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/': {
      id: '/_authenticated/w/$slug/settings/'
      path: '/settings'
      fullPath: '/w/$slug/settings/'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/': {
      id: '/_authenticated/w/$slug/pm/'
      path: '/pm'
      fullPath: '/w/$slug/pm/'
      preLoaderRoute: typeof AuthenticatedWSlugPmIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/docs/': {
      id: '/_authenticated/w/$slug/docs/'
      path: '/'
      fullPath: '/w/$slug/docs/'
      preLoaderRoute: typeof AuthenticatedWSlugDocsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugDocsRoute
    }
    '/_authenticated/w/$slug/crm/': {
      id: '/_authenticated/w/$slug/crm/'
      path: '/crm'
      fullPath: '/w/$slug/crm/'
      preLoaderRoute: typeof AuthenticatedWSlugCrmIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/support/$conversationId': {
      id: '/_authenticated/w/$slug/support/$conversationId'
      path: '/support/$conversationId'
      fullPath: '/w/$slug/support/$conversationId'
      preLoaderRoute: typeof AuthenticatedWSlugSupportConversationIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/sprints/$sprintId': {
      id: '/_authenticated/w/$slug/sprints/$sprintId'
      path: '/sprints/$sprintId'
      fullPath: '/w/$slug/sprints/$sprintId'
      preLoaderRoute: typeof AuthenticatedWSlugSprintsSprintIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/workflows': {
      id: '/_authenticated/w/$slug/settings/workflows'
      path: '/settings/workflows'
      fullPath: '/w/$slug/settings/workflows'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsWorkflowsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/teams': {
      id: '/_authenticated/w/$slug/settings/teams'
      path: '/settings/teams'
      fullPath: '/w/$slug/settings/teams'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsTeamsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/story-templates': {
      id: '/_authenticated/w/$slug/settings/story-templates'
      path: '/settings/story-templates'
      fullPath: '/w/$slug/settings/story-templates'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsStoryTemplatesRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/redirects': {
      id: '/_authenticated/w/$slug/settings/redirects'
      path: '/settings/redirects'
      fullPath: '/w/$slug/settings/redirects'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsRedirectsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/recurring-tasks': {
      id: '/_authenticated/w/$slug/settings/recurring-tasks'
      path: '/settings/recurring-tasks'
      fullPath: '/w/$slug/settings/recurring-tasks'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsRecurringTasksRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/members': {
      id: '/_authenticated/w/$slug/settings/members'
      path: '/settings/members'
      fullPath: '/w/$slug/settings/members'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/labels': {
      id: '/_authenticated/w/$slug/settings/labels'
      path: '/settings/labels'
      fullPath: '/w/$slug/settings/labels'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsLabelsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/knowledge': {
      id: '/_authenticated/w/$slug/settings/knowledge'
      path: '/settings/knowledge'
      fullPath: '/w/$slug/settings/knowledge'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsKnowledgeRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/inboxes-routing': {
      id: '/_authenticated/w/$slug/settings/inboxes-routing'
      path: '/settings/inboxes-routing'
      fullPath: '/w/$slug/settings/inboxes-routing'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsInboxesRoutingRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/import': {
      id: '/_authenticated/w/$slug/settings/import'
      path: '/settings/import'
      fullPath: '/w/$slug/settings/import'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsImportRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/helpcenter': {
      id: '/_authenticated/w/$slug/settings/helpcenter'
      path: '/settings/helpcenter'
      fullPath: '/w/$slug/settings/helpcenter'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsHelpcenterRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/general': {
      id: '/_authenticated/w/$slug/settings/general'
      path: '/settings/general'
      fullPath: '/w/$slug/settings/general'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/delivery': {
      id: '/_authenticated/w/$slug/settings/delivery'
      path: '/settings/delivery'
      fullPath: '/w/$slug/settings/delivery'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsDeliveryRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/crm-pipelines': {
      id: '/_authenticated/w/$slug/settings/crm-pipelines'
      path: '/settings/crm-pipelines'
      fullPath: '/w/$slug/settings/crm-pipelines'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsCrmPipelinesRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/crm-email': {
      id: '/_authenticated/w/$slug/settings/crm-email'
      path: '/settings/crm-email'
      fullPath: '/w/$slug/settings/crm-email'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsCrmEmailRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/crm-autonomy': {
      id: '/_authenticated/w/$slug/settings/crm-autonomy'
      path: '/settings/crm-autonomy'
      fullPath: '/w/$slug/settings/crm-autonomy'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsCrmAutonomyRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/chat-general': {
      id: '/_authenticated/w/$slug/settings/chat-general'
      path: '/settings/chat-general'
      fullPath: '/w/$slug/settings/chat-general'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsChatGeneralRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/automations': {
      id: '/_authenticated/w/$slug/settings/automations'
      path: '/settings/automations'
      fullPath: '/w/$slug/settings/automations'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsAutomationsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/ai-automations': {
      id: '/_authenticated/w/$slug/settings/ai-automations'
      path: '/settings/ai-automations'
      fullPath: '/w/$slug/settings/ai-automations'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsAiAutomationsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/settings/$section': {
      id: '/_authenticated/w/$slug/settings/$section'
      path: '/settings/$section'
      fullPath: '/w/$slug/settings/$section'
      preLoaderRoute: typeof AuthenticatedWSlugSettingsSectionRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/tool-catalog': {
      id: '/_authenticated/w/$slug/pm/tool-catalog'
      path: '/pm/tool-catalog'
      fullPath: '/w/$slug/pm/tool-catalog'
      preLoaderRoute: typeof AuthenticatedWSlugPmToolCatalogRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/support': {
      id: '/_authenticated/w/$slug/pm/support'
      path: '/pm/support'
      fullPath: '/w/$slug/pm/support'
      preLoaderRoute: typeof AuthenticatedWSlugPmSupportRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/roadmap': {
      id: '/_authenticated/w/$slug/pm/roadmap'
      path: '/pm/roadmap'
      fullPath: '/w/$slug/pm/roadmap'
      preLoaderRoute: typeof AuthenticatedWSlugPmRoadmapRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/reports': {
      id: '/_authenticated/w/$slug/pm/reports'
      path: '/pm/reports'
      fullPath: '/w/$slug/pm/reports'
      preLoaderRoute: typeof AuthenticatedWSlugPmReportsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/my-work': {
      id: '/_authenticated/w/$slug/pm/my-work'
      path: '/pm/my-work'
      fullPath: '/w/$slug/pm/my-work'
      preLoaderRoute: typeof AuthenticatedWSlugPmMyWorkRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/labels': {
      id: '/_authenticated/w/$slug/pm/labels'
      path: '/pm/labels'
      fullPath: '/w/$slug/pm/labels'
      preLoaderRoute: typeof AuthenticatedWSlugPmLabelsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/agents': {
      id: '/_authenticated/w/$slug/pm/agents'
      path: '/pm/agents'
      fullPath: '/w/$slug/pm/agents'
      preLoaderRoute: typeof AuthenticatedWSlugPmAgentsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/agent-runs': {
      id: '/_authenticated/w/$slug/pm/agent-runs'
      path: '/pm/agent-runs'
      fullPath: '/w/$slug/pm/agent-runs'
      preLoaderRoute: typeof AuthenticatedWSlugPmAgentRunsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/docs/recent': {
      id: '/_authenticated/w/$slug/docs/recent'
      path: '/recent'
      fullPath: '/w/$slug/docs/recent'
      preLoaderRoute: typeof AuthenticatedWSlugDocsRecentRouteImport
      parentRoute: typeof AuthenticatedWSlugDocsRoute
    }
    '/_authenticated/w/$slug/docs/my': {
      id: '/_authenticated/w/$slug/docs/my'
      path: '/my'
      fullPath: '/w/$slug/docs/my'
      preLoaderRoute: typeof AuthenticatedWSlugDocsMyRouteImport
      parentRoute: typeof AuthenticatedWSlugDocsRoute
    }
    '/_authenticated/w/$slug/docs/drafts': {
      id: '/_authenticated/w/$slug/docs/drafts'
      path: '/drafts'
      fullPath: '/w/$slug/docs/drafts'
      preLoaderRoute: typeof AuthenticatedWSlugDocsDraftsRouteImport
      parentRoute: typeof AuthenticatedWSlugDocsRoute
    }
    '/_authenticated/w/$slug/crm/review': {
      id: '/_authenticated/w/$slug/crm/review'
      path: '/crm/review'
      fullPath: '/w/$slug/crm/review'
      preLoaderRoute: typeof AuthenticatedWSlugCrmReviewRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/crm/insights': {
      id: '/_authenticated/w/$slug/crm/insights'
      path: '/crm/insights'
      fullPath: '/w/$slug/crm/insights'
      preLoaderRoute: typeof AuthenticatedWSlugCrmInsightsRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/stories/': {
      id: '/_authenticated/w/$slug/pm/stories/'
      path: '/pm/stories'
      fullPath: '/w/$slug/pm/stories/'
      preLoaderRoute: typeof AuthenticatedWSlugPmStoriesIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/sprints/': {
      id: '/_authenticated/w/$slug/pm/sprints/'
      path: '/pm/sprints'
      fullPath: '/w/$slug/pm/sprints/'
      preLoaderRoute: typeof AuthenticatedWSlugPmSprintsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/objectives/': {
      id: '/_authenticated/w/$slug/pm/objectives/'
      path: '/pm/objectives'
      fullPath: '/w/$slug/pm/objectives/'
      preLoaderRoute: typeof AuthenticatedWSlugPmObjectivesIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/epics/': {
      id: '/_authenticated/w/$slug/pm/epics/'
      path: '/pm/epics'
      fullPath: '/w/$slug/pm/epics/'
      preLoaderRoute: typeof AuthenticatedWSlugPmEpicsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/crm/sequences/': {
      id: '/_authenticated/w/$slug/crm/sequences/'
      path: '/crm/sequences'
      fullPath: '/w/$slug/crm/sequences/'
      preLoaderRoute: typeof AuthenticatedWSlugCrmSequencesIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/crm/lists/': {
      id: '/_authenticated/w/$slug/crm/lists/'
      path: '/crm/lists'
      fullPath: '/w/$slug/crm/lists/'
      preLoaderRoute: typeof AuthenticatedWSlugCrmListsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/crm/deals/': {
      id: '/_authenticated/w/$slug/crm/deals/'
      path: '/crm/deals'
      fullPath: '/w/$slug/crm/deals/'
      preLoaderRoute: typeof AuthenticatedWSlugCrmDealsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/crm/contacts/': {
      id: '/_authenticated/w/$slug/crm/contacts/'
      path: '/crm/contacts'
      fullPath: '/w/$slug/crm/contacts/'
      preLoaderRoute: typeof AuthenticatedWSlugCrmContactsIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/crm/companies/': {
      id: '/_authenticated/w/$slug/crm/companies/'
      path: '/crm/companies'
      fullPath: '/w/$slug/crm/companies/'
      preLoaderRoute: typeof AuthenticatedWSlugCrmCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/stories/$storyId': {
      id: '/_authenticated/w/$slug/pm/stories/$storyId'
      path: '/pm/stories/$storyId'
      fullPath: '/w/$slug/pm/stories/$storyId'
      preLoaderRoute: typeof AuthenticatedWSlugPmStoriesStoryIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/sprints/$sprintId': {
      id: '/_authenticated/w/$slug/pm/sprints/$sprintId'
      path: '/pm/sprints/$sprintId'
      fullPath: '/w/$slug/pm/sprints/$sprintId'
      preLoaderRoute: typeof AuthenticatedWSlugPmSprintsSprintIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/objectives/$objectiveId': {
      id: '/_authenticated/w/$slug/pm/objectives/$objectiveId'
      path: '/pm/objectives/$objectiveId'
      fullPath: '/w/$slug/pm/objectives/$objectiveId'
      preLoaderRoute: typeof AuthenticatedWSlugPmObjectivesObjectiveIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/epics/$epicId': {
      id: '/_authenticated/w/$slug/pm/epics/$epicId'
      path: '/pm/epics/$epicId'
      fullPath: '/w/$slug/pm/epics/$epicId'
      preLoaderRoute: typeof AuthenticatedWSlugPmEpicsEpicIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/pm/coding-sessions/$sessionId': {
      id: '/_authenticated/w/$slug/pm/coding-sessions/$sessionId'
      path: '/pm/coding-sessions/$sessionId'
      fullPath: '/w/$slug/pm/coding-sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedWSlugPmCodingSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/docs/spaces/$spaceId': {
      id: '/_authenticated/w/$slug/docs/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/w/$slug/docs/spaces/$spaceId'
      preLoaderRoute: typeof AuthenticatedWSlugDocsSpacesSpaceIdRouteImport
      parentRoute: typeof AuthenticatedWSlugDocsRoute
    }
    '/_authenticated/w/$slug/docs/documents/$docId': {
      id: '/_authenticated/w/$slug/docs/documents/$docId'
      path: '/documents/$docId'
      fullPath: '/w/$slug/docs/documents/$docId'
      preLoaderRoute: typeof AuthenticatedWSlugDocsDocumentsDocIdRouteImport
      parentRoute: typeof AuthenticatedWSlugDocsRoute
    }
    '/_authenticated/w/$slug/crm/sequences/$sequenceId': {
      id: '/_authenticated/w/$slug/crm/sequences/$sequenceId'
      path: '/crm/sequences/$sequenceId'
      fullPath: '/w/$slug/crm/sequences/$sequenceId'
      preLoaderRoute: typeof AuthenticatedWSlugCrmSequencesSequenceIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/crm/deals/$dealId': {
      id: '/_authenticated/w/$slug/crm/deals/$dealId'
      path: '/crm/deals/$dealId'
      fullPath: '/w/$slug/crm/deals/$dealId'
      preLoaderRoute: typeof AuthenticatedWSlugCrmDealsDealIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/crm/contacts/$contactId': {
      id: '/_authenticated/w/$slug/crm/contacts/$contactId'
      path: '/crm/contacts/$contactId'
      fullPath: '/w/$slug/crm/contacts/$contactId'
      preLoaderRoute: typeof AuthenticatedWSlugCrmContactsContactIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
    '/_authenticated/w/$slug/crm/companies/$companyId': {
      id: '/_authenticated/w/$slug/crm/companies/$companyId'
      path: '/crm/companies/$companyId'
      fullPath: '/w/$slug/crm/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedWSlugCrmCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedWSlugRoute
    }
  }
}

interface AuthenticatedWSlugDocsRouteChildren {
  AuthenticatedWSlugDocsDraftsRoute: typeof AuthenticatedWSlugDocsDraftsRoute
  AuthenticatedWSlugDocsMyRoute: typeof AuthenticatedWSlugDocsMyRoute
  AuthenticatedWSlugDocsRecentRoute: typeof AuthenticatedWSlugDocsRecentRoute
  AuthenticatedWSlugDocsIndexRoute: typeof AuthenticatedWSlugDocsIndexRoute
  AuthenticatedWSlugDocsDocumentsDocIdRoute: typeof AuthenticatedWSlugDocsDocumentsDocIdRoute
  AuthenticatedWSlugDocsSpacesSpaceIdRoute: typeof AuthenticatedWSlugDocsSpacesSpaceIdRoute
}

const AuthenticatedWSlugDocsRouteChildren: AuthenticatedWSlugDocsRouteChildren =
  {
    AuthenticatedWSlugDocsDraftsRoute: AuthenticatedWSlugDocsDraftsRoute,
    AuthenticatedWSlugDocsMyRoute: AuthenticatedWSlugDocsMyRoute,
    AuthenticatedWSlugDocsRecentRoute: AuthenticatedWSlugDocsRecentRoute,
    AuthenticatedWSlugDocsIndexRoute: AuthenticatedWSlugDocsIndexRoute,
    AuthenticatedWSlugDocsDocumentsDocIdRoute:
      AuthenticatedWSlugDocsDocumentsDocIdRoute,
    AuthenticatedWSlugDocsSpacesSpaceIdRoute:
      AuthenticatedWSlugDocsSpacesSpaceIdRoute,
  }

const AuthenticatedWSlugDocsRouteWithChildren =
  AuthenticatedWSlugDocsRoute._addFileChildren(
    AuthenticatedWSlugDocsRouteChildren,
  )

interface AuthenticatedWSlugRouteChildren {
  AuthenticatedWSlugDashboardRoute: typeof AuthenticatedWSlugDashboardRoute
  AuthenticatedWSlugDocsRoute: typeof AuthenticatedWSlugDocsRouteWithChildren
  AuthenticatedWSlugNotificationsRoute: typeof AuthenticatedWSlugNotificationsRoute
  AuthenticatedWSlugTasksRoute: typeof AuthenticatedWSlugTasksRoute
  AuthenticatedWSlugTeamGoalsRoute: typeof AuthenticatedWSlugTeamGoalsRoute
  AuthenticatedWSlugIndexRoute: typeof AuthenticatedWSlugIndexRoute
  AuthenticatedWSlugCrmInsightsRoute: typeof AuthenticatedWSlugCrmInsightsRoute
  AuthenticatedWSlugCrmReviewRoute: typeof AuthenticatedWSlugCrmReviewRoute
  AuthenticatedWSlugPmAgentRunsRoute: typeof AuthenticatedWSlugPmAgentRunsRoute
  AuthenticatedWSlugPmAgentsRoute: typeof AuthenticatedWSlugPmAgentsRoute
  AuthenticatedWSlugPmLabelsRoute: typeof AuthenticatedWSlugPmLabelsRoute
  AuthenticatedWSlugPmMyWorkRoute: typeof AuthenticatedWSlugPmMyWorkRoute
  AuthenticatedWSlugPmReportsRoute: typeof AuthenticatedWSlugPmReportsRoute
  AuthenticatedWSlugPmRoadmapRoute: typeof AuthenticatedWSlugPmRoadmapRoute
  AuthenticatedWSlugPmSupportRoute: typeof AuthenticatedWSlugPmSupportRoute
  AuthenticatedWSlugPmToolCatalogRoute: typeof AuthenticatedWSlugPmToolCatalogRoute
  AuthenticatedWSlugSettingsSectionRoute: typeof AuthenticatedWSlugSettingsSectionRoute
  AuthenticatedWSlugSettingsAiAutomationsRoute: typeof AuthenticatedWSlugSettingsAiAutomationsRoute
  AuthenticatedWSlugSettingsAutomationsRoute: typeof AuthenticatedWSlugSettingsAutomationsRoute
  AuthenticatedWSlugSettingsChatGeneralRoute: typeof AuthenticatedWSlugSettingsChatGeneralRoute
  AuthenticatedWSlugSettingsCrmAutonomyRoute: typeof AuthenticatedWSlugSettingsCrmAutonomyRoute
  AuthenticatedWSlugSettingsCrmEmailRoute: typeof AuthenticatedWSlugSettingsCrmEmailRoute
  AuthenticatedWSlugSettingsCrmPipelinesRoute: typeof AuthenticatedWSlugSettingsCrmPipelinesRoute
  AuthenticatedWSlugSettingsDeliveryRoute: typeof AuthenticatedWSlugSettingsDeliveryRoute
  AuthenticatedWSlugSettingsGeneralRoute: typeof AuthenticatedWSlugSettingsGeneralRoute
  AuthenticatedWSlugSettingsHelpcenterRoute: typeof AuthenticatedWSlugSettingsHelpcenterRoute
  AuthenticatedWSlugSettingsImportRoute: typeof AuthenticatedWSlugSettingsImportRoute
  AuthenticatedWSlugSettingsInboxesRoutingRoute: typeof AuthenticatedWSlugSettingsInboxesRoutingRoute
  AuthenticatedWSlugSettingsKnowledgeRoute: typeof AuthenticatedWSlugSettingsKnowledgeRoute
  AuthenticatedWSlugSettingsLabelsRoute: typeof AuthenticatedWSlugSettingsLabelsRoute
  AuthenticatedWSlugSettingsMembersRoute: typeof AuthenticatedWSlugSettingsMembersRoute
  AuthenticatedWSlugSettingsRecurringTasksRoute: typeof AuthenticatedWSlugSettingsRecurringTasksRoute
  AuthenticatedWSlugSettingsRedirectsRoute: typeof AuthenticatedWSlugSettingsRedirectsRoute
  AuthenticatedWSlugSettingsStoryTemplatesRoute: typeof AuthenticatedWSlugSettingsStoryTemplatesRoute
  AuthenticatedWSlugSettingsTeamsRoute: typeof AuthenticatedWSlugSettingsTeamsRoute
  AuthenticatedWSlugSettingsWorkflowsRoute: typeof AuthenticatedWSlugSettingsWorkflowsRoute
  AuthenticatedWSlugSprintsSprintIdRoute: typeof AuthenticatedWSlugSprintsSprintIdRoute
  AuthenticatedWSlugSupportConversationIdRoute: typeof AuthenticatedWSlugSupportConversationIdRoute
  AuthenticatedWSlugCrmIndexRoute: typeof AuthenticatedWSlugCrmIndexRoute
  AuthenticatedWSlugPmIndexRoute: typeof AuthenticatedWSlugPmIndexRoute
  AuthenticatedWSlugSettingsIndexRoute: typeof AuthenticatedWSlugSettingsIndexRoute
  AuthenticatedWSlugSprintsIndexRoute: typeof AuthenticatedWSlugSprintsIndexRoute
  AuthenticatedWSlugSupportIndexRoute: typeof AuthenticatedWSlugSupportIndexRoute
  AuthenticatedWSlugCrmCompaniesCompanyIdRoute: typeof AuthenticatedWSlugCrmCompaniesCompanyIdRoute
  AuthenticatedWSlugCrmContactsContactIdRoute: typeof AuthenticatedWSlugCrmContactsContactIdRoute
  AuthenticatedWSlugCrmDealsDealIdRoute: typeof AuthenticatedWSlugCrmDealsDealIdRoute
  AuthenticatedWSlugCrmSequencesSequenceIdRoute: typeof AuthenticatedWSlugCrmSequencesSequenceIdRoute
  AuthenticatedWSlugPmCodingSessionsSessionIdRoute: typeof AuthenticatedWSlugPmCodingSessionsSessionIdRoute
  AuthenticatedWSlugPmEpicsEpicIdRoute: typeof AuthenticatedWSlugPmEpicsEpicIdRoute
  AuthenticatedWSlugPmObjectivesObjectiveIdRoute: typeof AuthenticatedWSlugPmObjectivesObjectiveIdRoute
  AuthenticatedWSlugPmSprintsSprintIdRoute: typeof AuthenticatedWSlugPmSprintsSprintIdRoute
  AuthenticatedWSlugPmStoriesStoryIdRoute: typeof AuthenticatedWSlugPmStoriesStoryIdRoute
  AuthenticatedWSlugCrmCompaniesIndexRoute: typeof AuthenticatedWSlugCrmCompaniesIndexRoute
  AuthenticatedWSlugCrmContactsIndexRoute: typeof AuthenticatedWSlugCrmContactsIndexRoute
  AuthenticatedWSlugCrmDealsIndexRoute: typeof AuthenticatedWSlugCrmDealsIndexRoute
  AuthenticatedWSlugCrmListsIndexRoute: typeof AuthenticatedWSlugCrmListsIndexRoute
  AuthenticatedWSlugCrmSequencesIndexRoute: typeof AuthenticatedWSlugCrmSequencesIndexRoute
  AuthenticatedWSlugPmEpicsIndexRoute: typeof AuthenticatedWSlugPmEpicsIndexRoute
  AuthenticatedWSlugPmObjectivesIndexRoute: typeof AuthenticatedWSlugPmObjectivesIndexRoute
  AuthenticatedWSlugPmSprintsIndexRoute: typeof AuthenticatedWSlugPmSprintsIndexRoute
  AuthenticatedWSlugPmStoriesIndexRoute: typeof AuthenticatedWSlugPmStoriesIndexRoute
}

const AuthenticatedWSlugRouteChildren: AuthenticatedWSlugRouteChildren = {
  AuthenticatedWSlugDashboardRoute: AuthenticatedWSlugDashboardRoute,
  AuthenticatedWSlugDocsRoute: AuthenticatedWSlugDocsRouteWithChildren,
  AuthenticatedWSlugNotificationsRoute: AuthenticatedWSlugNotificationsRoute,
  AuthenticatedWSlugTasksRoute: AuthenticatedWSlugTasksRoute,
  AuthenticatedWSlugTeamGoalsRoute: AuthenticatedWSlugTeamGoalsRoute,
  AuthenticatedWSlugIndexRoute: AuthenticatedWSlugIndexRoute,
  AuthenticatedWSlugCrmInsightsRoute: AuthenticatedWSlugCrmInsightsRoute,
  AuthenticatedWSlugCrmReviewRoute: AuthenticatedWSlugCrmReviewRoute,
  AuthenticatedWSlugPmAgentRunsRoute: AuthenticatedWSlugPmAgentRunsRoute,
  AuthenticatedWSlugPmAgentsRoute: AuthenticatedWSlugPmAgentsRoute,
  AuthenticatedWSlugPmLabelsRoute: AuthenticatedWSlugPmLabelsRoute,
  AuthenticatedWSlugPmMyWorkRoute: AuthenticatedWSlugPmMyWorkRoute,
  AuthenticatedWSlugPmReportsRoute: AuthenticatedWSlugPmReportsRoute,
  AuthenticatedWSlugPmRoadmapRoute: AuthenticatedWSlugPmRoadmapRoute,
  AuthenticatedWSlugPmSupportRoute: AuthenticatedWSlugPmSupportRoute,
  AuthenticatedWSlugPmToolCatalogRoute: AuthenticatedWSlugPmToolCatalogRoute,
  AuthenticatedWSlugSettingsSectionRoute:
    AuthenticatedWSlugSettingsSectionRoute,
  AuthenticatedWSlugSettingsAiAutomationsRoute:
    AuthenticatedWSlugSettingsAiAutomationsRoute,
  AuthenticatedWSlugSettingsAutomationsRoute:
    AuthenticatedWSlugSettingsAutomationsRoute,
  AuthenticatedWSlugSettingsChatGeneralRoute:
    AuthenticatedWSlugSettingsChatGeneralRoute,
  AuthenticatedWSlugSettingsCrmAutonomyRoute:
    AuthenticatedWSlugSettingsCrmAutonomyRoute,
  AuthenticatedWSlugSettingsCrmEmailRoute:
    AuthenticatedWSlugSettingsCrmEmailRoute,
  AuthenticatedWSlugSettingsCrmPipelinesRoute:
    AuthenticatedWSlugSettingsCrmPipelinesRoute,
  AuthenticatedWSlugSettingsDeliveryRoute:
    AuthenticatedWSlugSettingsDeliveryRoute,
  AuthenticatedWSlugSettingsGeneralRoute:
    AuthenticatedWSlugSettingsGeneralRoute,
  AuthenticatedWSlugSettingsHelpcenterRoute:
    AuthenticatedWSlugSettingsHelpcenterRoute,
  AuthenticatedWSlugSettingsImportRoute: AuthenticatedWSlugSettingsImportRoute,
  AuthenticatedWSlugSettingsInboxesRoutingRoute:
    AuthenticatedWSlugSettingsInboxesRoutingRoute,
  AuthenticatedWSlugSettingsKnowledgeRoute:
    AuthenticatedWSlugSettingsKnowledgeRoute,
  AuthenticatedWSlugSettingsLabelsRoute: AuthenticatedWSlugSettingsLabelsRoute,
  AuthenticatedWSlugSettingsMembersRoute:
    AuthenticatedWSlugSettingsMembersRoute,
  AuthenticatedWSlugSettingsRecurringTasksRoute:
    AuthenticatedWSlugSettingsRecurringTasksRoute,
  AuthenticatedWSlugSettingsRedirectsRoute:
    AuthenticatedWSlugSettingsRedirectsRoute,
  AuthenticatedWSlugSettingsStoryTemplatesRoute:
    AuthenticatedWSlugSettingsStoryTemplatesRoute,
  AuthenticatedWSlugSettingsTeamsRoute: AuthenticatedWSlugSettingsTeamsRoute,
  AuthenticatedWSlugSettingsWorkflowsRoute:
    AuthenticatedWSlugSettingsWorkflowsRoute,
  AuthenticatedWSlugSprintsSprintIdRoute:
    AuthenticatedWSlugSprintsSprintIdRoute,
  AuthenticatedWSlugSupportConversationIdRoute:
    AuthenticatedWSlugSupportConversationIdRoute,
  AuthenticatedWSlugCrmIndexRoute: AuthenticatedWSlugCrmIndexRoute,
  AuthenticatedWSlugPmIndexRoute: AuthenticatedWSlugPmIndexRoute,
  AuthenticatedWSlugSettingsIndexRoute: AuthenticatedWSlugSettingsIndexRoute,
  AuthenticatedWSlugSprintsIndexRoute: AuthenticatedWSlugSprintsIndexRoute,
  AuthenticatedWSlugSupportIndexRoute: AuthenticatedWSlugSupportIndexRoute,
  AuthenticatedWSlugCrmCompaniesCompanyIdRoute:
    AuthenticatedWSlugCrmCompaniesCompanyIdRoute,
  AuthenticatedWSlugCrmContactsContactIdRoute:
    AuthenticatedWSlugCrmContactsContactIdRoute,
  AuthenticatedWSlugCrmDealsDealIdRoute: AuthenticatedWSlugCrmDealsDealIdRoute,
  AuthenticatedWSlugCrmSequencesSequenceIdRoute:
    AuthenticatedWSlugCrmSequencesSequenceIdRoute,
  AuthenticatedWSlugPmCodingSessionsSessionIdRoute:
    AuthenticatedWSlugPmCodingSessionsSessionIdRoute,
  AuthenticatedWSlugPmEpicsEpicIdRoute: AuthenticatedWSlugPmEpicsEpicIdRoute,
  AuthenticatedWSlugPmObjectivesObjectiveIdRoute:
    AuthenticatedWSlugPmObjectivesObjectiveIdRoute,
  AuthenticatedWSlugPmSprintsSprintIdRoute:
    AuthenticatedWSlugPmSprintsSprintIdRoute,
  AuthenticatedWSlugPmStoriesStoryIdRoute:
    AuthenticatedWSlugPmStoriesStoryIdRoute,
  AuthenticatedWSlugCrmCompaniesIndexRoute:
    AuthenticatedWSlugCrmCompaniesIndexRoute,
  AuthenticatedWSlugCrmContactsIndexRoute:
    AuthenticatedWSlugCrmContactsIndexRoute,
  AuthenticatedWSlugCrmDealsIndexRoute: AuthenticatedWSlugCrmDealsIndexRoute,
  AuthenticatedWSlugCrmListsIndexRoute: AuthenticatedWSlugCrmListsIndexRoute,
  AuthenticatedWSlugCrmSequencesIndexRoute:
    AuthenticatedWSlugCrmSequencesIndexRoute,
  AuthenticatedWSlugPmEpicsIndexRoute: AuthenticatedWSlugPmEpicsIndexRoute,
  AuthenticatedWSlugPmObjectivesIndexRoute:
    AuthenticatedWSlugPmObjectivesIndexRoute,
  AuthenticatedWSlugPmSprintsIndexRoute: AuthenticatedWSlugPmSprintsIndexRoute,
  AuthenticatedWSlugPmStoriesIndexRoute: AuthenticatedWSlugPmStoriesIndexRoute,
}

const AuthenticatedWSlugRouteWithChildren =
  AuthenticatedWSlugRoute._addFileChildren(AuthenticatedWSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedWSlugRoute: typeof AuthenticatedWSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedWSlugRoute: AuthenticatedWSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  JoinTokenRoute: JoinTokenRoute,
  ShareShareTokenRoute: ShareShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
