// Command generate-commercial-event-catalog regenerates the Go and Rust origin-gate catalogs.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type catalog struct {
	ServerOnlyEventNames    []string `json:"server_only_event_names"`
	ServerOnlyCompanyFields []string `json:"server_only_company_fields"`
}

func main() {
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	sourcePath := filepath.Join(root, "server/internal/eventcatalog/commercial_events.json")
	data, err := os.ReadFile(sourcePath)
	if err != nil {
		panic(err)
	}
	var values catalog
	if err := json.Unmarshal(data, &values); err != nil {
		panic(err)
	}
	sort.Strings(values.ServerOnlyEventNames)
	sort.Strings(values.ServerOnlyCompanyFields)
	if err := os.WriteFile(
		filepath.Join(root, "server/internal/eventcatalog/commercial_generated.go"),
		[]byte(renderGo(values)), 0o644,
	); err != nil {
		panic(err)
	}
	if err := os.WriteFile(
		filepath.Join(root, "events-pipeline/rust-capture/src/commercial_event_catalog_generated.rs"),
		[]byte(renderRust(values)), 0o644,
	); err != nil {
		panic(err)
	}
}

func renderGo(values catalog) string {
	return fmt.Sprintf(`// Code generated by scripts/generate-commercial-event-catalog.go; DO NOT EDIT.
package eventcatalog

// ServerOnlyEventNames contains events rejected when presented with browser credentials.
var ServerOnlyEventNames = map[string]struct{}{%s
}

// ServerOnlyCompanyFields contains protected company payload fields.
var ServerOnlyCompanyFields = map[string]struct{}{%s
}

// IsServerOnlyEvent reports whether an event requires a server credential.
func IsServerOnlyEvent(name string) bool { _, ok := ServerOnlyEventNames[name]; return ok }
// IsServerOnlyCompanyField reports whether a company field requires a server credential.
func IsServerOnlyCompanyField(name string) bool { _, ok := ServerOnlyCompanyFields[name]; return ok }
`, goEntries(values.ServerOnlyEventNames), goEntries(values.ServerOnlyCompanyFields))
}

func goEntries(values []string) string {
	var lines []string
	for _, value := range values {
		lines = append(lines, fmt.Sprintf("\n\t%q: {},", value))
	}
	return strings.Join(lines, "")
}

func renderRust(values catalog) string {
	return fmt.Sprintf(`// Code generated by scripts/generate-commercial-event-catalog.go; DO NOT EDIT.
pub const SERVER_ONLY_EVENT_NAMES: &[&str] = &[%s
];
pub const SERVER_ONLY_COMPANY_FIELDS: &[&str] = &[%s
];
pub fn is_server_only_event(name: &str) -> bool { SERVER_ONLY_EVENT_NAMES.binary_search(&name).is_ok() }
pub fn has_server_only_company_field(company: &std::collections::HashMap<String, serde_json::Value>) -> bool {
    SERVER_ONLY_COMPANY_FIELDS.iter().any(|field| {
        company.contains_key(*field)
            || company.get("custom")
                .and_then(serde_json::Value::as_object)
                .is_some_and(|custom| custom.contains_key(*field))
    })
}

#[cfg(test)]
mod tests {
    use serde::Deserialize;

    #[derive(Deserialize)]
    struct SourceCatalog {
        server_only_event_names: Vec<String>,
        server_only_company_fields: Vec<String>,
    }

    #[test]
    fn generated_catalog_matches_shared_source() {
        let source: SourceCatalog = serde_json::from_str(include_str!(
            "../../../server/internal/eventcatalog/commercial_events.json"
        ))
        .expect("shared commercial event catalog must parse");
        assert_eq!(source.server_only_event_names, super::SERVER_ONLY_EVENT_NAMES);
        assert_eq!(
            source.server_only_company_fields,
            super::SERVER_ONLY_COMPANY_FIELDS
        );
    }
}
`, rustEntries(values.ServerOnlyEventNames), rustEntries(values.ServerOnlyCompanyFields))
}

func rustEntries(values []string) string {
	var lines []string
	for _, value := range values {
		lines = append(lines, fmt.Sprintf("\n    %q,", value))
	}
	return strings.Join(lines, "")
}
