server_name: $NATS_SERVER_NAME
port: 4222
http_port: 8222
max_payload: 8MB

jetstream {
  store_dir: /data
  cipher: chachapoly
  key: "$JS_ENCRYPTION_KEY"
  sync_interval: "2m"
}

tls {
  cert_file: /etc/nats/tls/server.crt
  key_file: /etc/nats/tls/server.key
  ca_file: /etc/nats/tls/ca.crt
  verify: true
  min_version: "1.3"
}

cluster {
  name: helpin-e2e
  port: 6222
  routes: [
    nats-route://nats-0:6222,
    nats-route://nats-1:6222,
    nats-route://nats-2:6222
  ]
  tls {
    cert_file: /etc/nats/tls/server.crt
    key_file: /etc/nats/tls/server.key
    ca_file: /etc/nats/tls/ca.crt
    min_version: "1.3"
  }
}
