export interface GoalCreationData {
  // Step 1: Basic Info
  title: string
  description: string
  priority: 'high' | 'medium' | 'low'
  category: string
  start_date: string
  end_date: string

  // Step 2: Target Setting
  metric_type: 'currency' | 'percentage' | 'number' | 'custom'
  target_value: number
  current_baseline: number
  unit_label?: string // for custom types
  success_criteria: string

  // Step 3: Team Assignment
  team_assignments: TeamAssignment[]

  // Step 4: Sprint Planning
  sprint_milestones: SprintMilestoneCreation[]

  // Generated data
  auto_generated_team_goals: AutoGeneratedTeamGoal[]
}

export interface TeamAssignment {
  team_id: string
  team_name: string
  contribution_percentage: number
  target_value: number
  rationale: string
}

export interface SprintMilestoneCreation {
  sprint_number: number
  target_value: number
  milestone_description: string
  key_deliverables: string[]
  team_allocations: { [team_id: string]: number }
}

export interface AutoGeneratedTeamGoal {
  team_id: string
  team_name: string
  title: string
  description: string
  target_value: number
  contribution_percentage: number
  sprint_breakdown: {
    sprint_number: number
    target_value: number
    description: string
    key_tasks: string[]
  }[]
  key_results: {
    title: string
    target_value: number
    unit: string
  }[]
}

export interface GoalTemplate {
  id: string
  name: string
  description: string
  category: string
  default_data: Partial<GoalCreationData>
  suggested_teams: string[]
  typical_sprint_breakdown: number[] // percentages for each sprint
}

export const GOAL_CATEGORIES = [
  'Revenue Growth',
  'Customer Acquisition',
  'Performance & Reliability',
  'Customer Satisfaction',
  'Product Development',
  'Market Expansion',
  'Operational Efficiency',
  'Team Development',
  'Strategic Initiative'
] as const

export const METRIC_TYPES = [
  { value: 'currency', label: 'Currency ($)', example: '$1,000,000' },
  { value: 'percentage', label: 'Percentage (%)', example: '25%' },
  { value: 'number', label: 'Number/Count', example: '1,000 users' },
  { value: 'custom', label: 'Custom Unit', example: 'Points, Score, etc.' }
] as const