const setupActionRoutes: Record<string, (slug: string) => string> = {
  workspace_context: (slug) => `/w/${slug}/settings/general`,
  workspace_teams: (slug) => `/w/${slug}/settings/teams`,
  workspace_members: (slug) => `/w/${slug}/settings/members`,
  pm_create_task: (slug) => `/w/${slug}/pm/tasks`,
  pm_epics: (slug) => `/w/${slug}/pm/epics`,
  pm_tasks: (slug) => `/w/${slug}/pm/tasks`,
  pm_sprints: (slug) => `/w/${slug}/pm/sprints`,
  product_agent: (slug) => `/w/${slug}/automation/agents`,
  git_settings: (slug) => `/w/${slug}/settings/repositories`,
  support_email_inbox: (slug) => `/w/${slug}/settings/inboxes-routing?tab=email`,
  support_live_chat: (slug) => `/w/${slug}/settings/chat-general`,
  support_help_docs: (slug) => `/w/${slug}/docs`,
  support_brand_knowledge: (slug) => `/w/${slug}/settings/knowledge`,
  support_team_inboxes: (slug) => `/w/${slug}/settings/inboxes-routing?tab=inboxes`,
  support_routing: (slug) => `/w/${slug}/settings/inboxes-routing?tab=routing`,
  support_inbox: (slug) => `/w/${slug}/support`,
  support_ai: (slug) => `/w/${slug}/settings/support-ai-assistant`,
  support_coverage: (slug) => `/w/${slug}/support/coverage`,
  docs_home: (slug) => `/w/${slug}/docs`,
  help_center_article_publish: (slug) => `/w/${slug}/docs`,
  help_center_settings: (slug) => `/w/${slug}/settings/helpcenter`,
  help_center_widget: (slug) => `/w/${slug}/settings/chat-general`,
  internal_docs_agent_knowledge: (slug) => `/w/${slug}/automation/agents`,
  internal_docs_agent_run: (slug) => `/w/${slug}/automation/agents`,
  crm_contacts: (slug) => `/w/${slug}/crm/contacts`,
  crm_companies: (slug) => `/w/${slug}/crm/companies`,
  crm_pipelines: (slug) => `/w/${slug}/settings/crm-pipelines`,
  crm_deals: (slug) => `/w/${slug}/crm/deals`,
  crm_email: (slug) => `/w/${slug}/settings/crm-email`,
  crm_autonomy: (slug) => `/w/${slug}/settings/crm-autonomy`,
  crm_review: (slug) => `/w/${slug}/crm/review`,
  automation_flows: (slug) => `/w/${slug}/automation/flows`,
  automation_agents: (slug) => `/w/${slug}/automation/agents`,
  automation_custom_agent: (slug) => `/w/${slug}/automation/agents`,
  automation_approval_guard: (slug) => `/w/${slug}/automation/agents`,
};

export function resolveSetupAction(key: string, slug: string) {
  return setupActionRoutes[key]?.(slug);
}
